/* ===== Séries d'exercices curatées — Mathématiques 1ère Bac Sciences Maths (programme marocain) =====
   Clés = titres EXACTS des chapitres (window.EDU_SUBJECTS.maths.chapters).
   Chaque exercice : { niv:'Application'|'Moyen'|'Défi', en:énoncé, hint:indice, sol:correction } (HTML + LaTeX $…$). */
window.PB_EXOS = window.PB_EXOS || {};
Object.assign(window.PB_EXOS, {

"Notions de logique": [
 { niv:"Application",
   en:"Écrire la négation de chacune des propositions : (a) $P:\\ \\forall x\\in\\mathbb{R},\\ x^2+1>0$ ; (b) $Q:\\ \\exists n\\in\\mathbb{N},\\ 2n=n^2$. Préciser si $P$ est vraie ou fausse.",
   hint:"La négation échange $\\forall$ et $\\exists$, et nie la propriété : la négation de $>$ est $\\le$, celle de $=$ est $\\ne$.",
   sol:"(a) $\\overline{P}:\\ \\exists x\\in\\mathbb{R},\\ x^2+1\\le 0$. Comme $x^2\\ge 0$, on a $x^2+1\\ge 1>0$ pour tout réel $x$ : donc $P$ est <b>vraie</b> (et $\\overline P$ fausse).<br>(b) $\\overline{Q}:\\ \\forall n\\in\\mathbb{N},\\ 2n\\ne n^2$. ($Q$ est vraie : pour $n=0$ et $n=2$ on a $2n=n^2$.)" },
 { niv:"Application",
   en:"Montrer, à l'aide d'une table de vérité, que $(P\\Rightarrow Q)$ est équivalente à $(\\overline{P}\\ \\lor\\ Q)$.",
   hint:"Il y a 4 cas selon que $P$ et $Q$ sont vraies (V) ou fausses (F). Compare les deux dernières colonnes.",
   sol:"<table class='exo-tab'><tr><th>$P$</th><th>$Q$</th><th>$P\\Rightarrow Q$</th><th>$\\overline P\\lor Q$</th></tr><tr><td>V</td><td>V</td><td>V</td><td>V</td></tr><tr><td>V</td><td>F</td><td>F</td><td>F</td></tr><tr><td>F</td><td>V</td><td>V</td><td>V</td></tr><tr><td>F</td><td>F</td><td>V</td><td>V</td></tr></table>Les colonnes $(P\\Rightarrow Q)$ et $(\\overline P\\lor Q)$ sont identiques : les deux propositions sont donc <b>équivalentes</b>." },
 { niv:"Moyen",
   en:"Soit $n\\in\\mathbb{Z}$. Montrer, en raisonnant par contraposée, que : si $n^2$ est pair alors $n$ est pair.",
   hint:"La contraposée de « si $n^2$ pair alors $n$ pair » est « si $n$ impair alors $n^2$ impair ». Écris $n=2k+1$.",
   sol:"Contraposée : « si $n$ est impair, alors $n^2$ est impair ». Supposons $n$ impair : $n=2k+1$ avec $k\\in\\mathbb{Z}$. Alors $n^2=(2k+1)^2=4k^2+4k+1=2(2k^2+2k)+1$, qui est impair. La contraposée est vraie, donc l'implication de départ l'est aussi : si $n^2$ est pair, alors $n$ est pair." },
 { niv:"Moyen",
   en:"Démontrer par récurrence que : $\\forall n\\in\\mathbb{N}^*,\\quad 1+2+3+\\cdots+n=\\dfrac{n(n+1)}{2}.$",
   hint:"Initialisation à $n=1$. Pour l'hérédité, ajoute $(n+1)$ aux deux membres de l'hypothèse de récurrence.",
   sol:"<b>Initialisation</b> ($n=1$) : à gauche $1$ ; à droite $\\frac{1\\cdot 2}{2}=1$. Vrai.<br><b>Hérédité</b> : supposons $1+\\cdots+n=\\frac{n(n+1)}{2}$. Alors $1+\\cdots+n+(n+1)=\\frac{n(n+1)}{2}+(n+1)=(n+1)\\left(\\frac{n}{2}+1\\right)=\\frac{(n+1)(n+2)}{2}$, qui est la formule au rang $n+1$.<br>Par récurrence, la propriété est vraie pour tout $n\\in\\mathbb{N}^*$." },
 { niv:"Défi",
   en:"Montrer, par un raisonnement par l'absurde, que $\\sqrt{2}$ est irrationnel.",
   hint:"Suppose $\\sqrt2=\\frac{p}{q}$ avec la fraction $\\frac pq$ irréductible, puis montre que $p$ et $q$ sont tous deux pairs.",
   sol:"Supposons par l'absurde $\\sqrt2=\\frac pq$ avec $p,q\\in\\mathbb{N}^*$ et $\\frac pq$ <b>irréductible</b>. Alors $2=\\frac{p^2}{q^2}$, donc $p^2=2q^2$ : $p^2$ est pair, donc $p$ est pair, $p=2k$. D'où $4k^2=2q^2$, soit $q^2=2k^2$ : $q^2$ est pair, donc $q$ est pair. Ainsi $p$ et $q$ sont pairs : $\\frac pq$ n'est pas irréductible — <b>contradiction</b>. Donc $\\sqrt2\\notin\\mathbb{Q}$." }
],

"Ensembles et applications": [
 { niv:"Application",
   en:"On donne $A=\\{1,2,3,4,6\\}$ et $B=\\{2,4,5,6\\}$, parties de $E=\\{1,2,3,4,5,6\\}$. Déterminer $A\\cup B$, $A\\cap B$, $A\\setminus B$ et $\\overline{A}$ (complémentaire dans $E$).",
   hint:"$A\\setminus B$ = éléments de $A$ absents de $B$ ; $\\overline A=E\\setminus A$.",
   sol:"$A\\cup B=\\{1,2,3,4,5,6\\}$ ; $A\\cap B=\\{2,4,6\\}$ ; $A\\setminus B=\\{1,3\\}$ ; $\\overline A=\\{5\\}$." },
 { niv:"Application",
   en:"Dans une classe de $30$ élèves, $18$ étudient l'anglais, $15$ l'espagnol et $7$ les deux. Combien étudient au moins une de ces langues ? Combien n'en étudient aucune ?",
   hint:"$\\operatorname{card}(A\\cup B)=\\operatorname{card}(A)+\\operatorname{card}(B)-\\operatorname{card}(A\\cap B)$.",
   sol:"$\\operatorname{card}(A\\cup B)=18+15-7=26$ élèves étudient au moins une langue. Aucune : $30-26=4$ élèves." },
 { niv:"Moyen",
   en:"Soient $A,B,C$ trois parties d'un ensemble $E$. Démontrer que $A\\cap(B\\cup C)=(A\\cap B)\\cup(A\\cap C)$.",
   hint:"Prends $x$ quelconque et traduis « $x\\in\\ldots$ » avec $\\land$ et $\\lor$, puis utilise la distributivité logique.",
   sol:"Soit $x\\in E$. $x\\in A\\cap(B\\cup C)\\iff (x\\in A)\\land\\big((x\\in B)\\lor(x\\in C)\\big)$. Par distributivité de $\\land$ sur $\\lor$ : $\\iff\\big((x\\in A)\\land(x\\in B)\\big)\\lor\\big((x\\in A)\\land(x\\in C)\\big)\\iff x\\in (A\\cap B)\\cup(A\\cap C)$. Les deux ensembles ont les mêmes éléments, donc ils sont égaux." },
 { niv:"Moyen",
   en:"Soit $f:\\mathbb{R}\\to\\mathbb{R}$ définie par $f(x)=2x-3$. Montrer que $f$ est bijective et déterminer $f^{-1}$.",
   hint:"Résous l'équation $f(x)=y$ d'inconnue $x$ : si elle a une solution unique pour tout $y$, $f$ est bijective.",
   sol:"Soit $y\\in\\mathbb{R}$. $f(x)=y\\iff 2x-3=y\\iff x=\\frac{y+3}{2}$. Pour tout $y$ il existe un <b>unique</b> $x$ : $f$ est bijective. Sa réciproque est $f^{-1}(x)=\\frac{x+3}{2}$." },
 { niv:"Défi",
   en:"Soit $f:\\mathbb{R}\\to\\mathbb{R},\\ f(x)=x^2$. (a) $f$ est-elle injective ? surjective ? (b) Mêmes questions pour $g:[0,+\\infty[\\to[0,+\\infty[,\\ g(x)=x^2$.",
   hint:"Pour l'injectivité, cherche deux antécédents distincts ; pour la surjectivité, cherche si tout élément de l'arrivée a un antécédent.",
   sol:"(a) $f(-1)=f(1)=1$ : deux antécédents distincts $\\Rightarrow f$ <b>non injective</b>. Et $-1$ n'a pas d'antécédent ($x^2=-1$ impossible dans $\\mathbb{R}$) $\\Rightarrow f$ <b>non surjective</b>.<br>(b) Sur $[0,+\\infty[$ : si $a,b\\ge0$ et $a^2=b^2$ alors $a=b$ : $g$ est <b>injective</b>. Pour tout $y\\ge0$, $x=\\sqrt y\\ge0$ donne $g(x)=y$ : $g$ est <b>surjective</b>. Donc $g$ est <b>bijective</b>, de réciproque $g^{-1}(x)=\\sqrt x$." }
],

"Généralités sur les fonctions numériques": [
 { niv:"Application",
   en:"Déterminer l'ensemble de définition de $f(x)=\\dfrac{\\sqrt{x-1}}{x-3}$.",
   hint:"Il faut à la fois $x-1\\ge 0$ (racine) et $x-3\\ne 0$ (dénominateur).",
   sol:"Conditions : $x-1\\ge0\\iff x\\ge1$ et $x-3\\ne0\\iff x\\ne3$. Donc $D_f=[1,3[\\,\\cup\\,]3,+\\infty[$." },
 { niv:"Application",
   en:"Étudier la parité de $f(x)=x^3-x$ et de $g(x)=x^2+\\cos x$ sur $\\mathbb{R}$.",
   hint:"Calcule $f(-x)$ et $g(-x)$, puis compare à $f(x)$ et $-f(x)$.",
   sol:"$\\mathbb{R}$ est symétrique par rapport à $0$. $f(-x)=-x^3+x=-(x^3-x)=-f(x)$ : $f$ est <b>impaire</b>. $g(-x)=x^2+\\cos(-x)=x^2+\\cos x=g(x)$ : $g$ est <b>paire</b>." },
 { niv:"Moyen",
   en:"Soit $f(x)=\\dfrac{2x+1}{x-1}$ sur $]1,+\\infty[$. Étudier son sens de variation.",
   hint:"Écris $f$ sous la forme $2+\\dfrac{3}{x-1}$.",
   sol:"$f(x)=\\frac{2(x-1)+3}{x-1}=2+\\frac{3}{x-1}$. Sur $]1,+\\infty[$, $x\\mapsto x-1$ est croissante et strictement positive, donc $x\\mapsto\\frac{3}{x-1}$ est <b>décroissante</b>, donc $f$ est <b>strictement décroissante</b>. (Vérif : $f(2)=5$, $f(4)=3$.)" },
 { niv:"Moyen",
   en:"Soit $f(x)=x^2-4x+5$. Écrire $f$ sous forme canonique, puis déterminer son minimum et le point où il est atteint.",
   hint:"$x^2-4x=(x-2)^2-4$.",
   sol:"$f(x)=(x-2)^2-4+5=(x-2)^2+1$. Comme $(x-2)^2\\ge0$, on a $f(x)\\ge1$ avec égalité ssi $x=2$. Le <b>minimum</b> de $f$ vaut $\\boxed{1}$, atteint en $x=2$." },
 { niv:"Défi",
   en:"Montrer que $f(x)=\\dfrac{x}{1+x^2}$ vérifie $-\\dfrac12\\le f(x)\\le \\dfrac12$ pour tout $x\\in\\mathbb{R}$ (donc $f$ est bornée).",
   hint:"Étudie le signe de $\\dfrac12-f(x)$ et de $f(x)+\\dfrac12$ ; pense à $(1\\mp x)^2\\ge0$.",
   sol:"Pour tout $x$, $1+x^2>0$. On a $\\frac12-f(x)=\\frac{(1+x^2)-2x}{2(1+x^2)}=\\frac{(1-x)^2}{2(1+x^2)}\\ge0$, donc $f(x)\\le\\frac12$. De même $f(x)+\\frac12=\\frac{(1+x)^2}{2(1+x^2)}\\ge0$, donc $f(x)\\ge-\\frac12$. Ainsi $-\\frac12\\le f(x)\\le\\frac12$ ; les bornes sont atteintes en $x=1$ et $x=-1$." }
],

"Le barycentre dans le plan": [
 { niv:"Application",
   en:"Soient $A$ et $B$ deux points et $G$ le barycentre de $(A,2)$ et $(B,3)$. Exprimer $\\vec{AG}$ en fonction de $\\vec{AB}$.",
   hint:"Par définition $2\\vec{GA}+3\\vec{GB}=\\vec0$. Écris $\\vec{GB}=\\vec{GA}+\\vec{AB}$.",
   sol:"$2\\vec{GA}+3\\vec{GB}=\\vec0$ et $\\vec{GB}=\\vec{GA}+\\vec{AB}$, donc $5\\vec{GA}+3\\vec{AB}=\\vec0\\Rightarrow\\vec{GA}=-\\frac35\\vec{AB}$, d'où $\\vec{AG}=\\frac35\\vec{AB}$. $G$ est aux $\\frac35$ de $[AB]$ à partir de $A$." },
 { niv:"Application",
   en:"Soit $ABC$ un triangle et $G$ l'isobarycentre de $A,B,C$. Montrer que $\\vec{AG}=\\dfrac13(\\vec{AB}+\\vec{AC})$.",
   hint:"$\\vec{GA}+\\vec{GB}+\\vec{GC}=\\vec0$, puis $\\vec{GB}=\\vec{GA}+\\vec{AB}$ et $\\vec{GC}=\\vec{GA}+\\vec{AC}$.",
   sol:"$\\vec{GA}+\\vec{GB}+\\vec{GC}=\\vec0$. En remplaçant : $3\\vec{GA}+\\vec{AB}+\\vec{AC}=\\vec0\\Rightarrow\\vec{AG}=\\frac13(\\vec{AB}+\\vec{AC})$. $G$ est le <b>centre de gravité</b> du triangle." },
 { niv:"Moyen",
   en:"Réduire, pour tout point $M$ du plan, le vecteur $\\vec{u}(M)=2\\vec{MA}+3\\vec{MB}$ en faisant apparaître le barycentre $G$ de $(A,2),(B,3)$.",
   hint:"Introduis $G$ : $\\vec{MA}=\\vec{MG}+\\vec{GA}$, etc., puis utilise $2\\vec{GA}+3\\vec{GB}=\\vec0$.",
   sol:"$2\\vec{MA}+3\\vec{MB}=2(\\vec{MG}+\\vec{GA})+3(\\vec{MG}+\\vec{GB})=5\\vec{MG}+(2\\vec{GA}+3\\vec{GB})=5\\vec{MG}$. Donc $\\vec{u}(M)=5\\vec{MG}$ pour tout $M$." },
 { niv:"Moyen",
   en:"Avec $G$ le barycentre de $(A,2),(B,3)$, déterminer l'ensemble des points $M$ tels que $\\lVert 2\\vec{MA}+3\\vec{MB}\\rVert=10$.",
   hint:"Utilise la réduction de l'exercice précédent : $2\\vec{MA}+3\\vec{MB}=5\\vec{MG}$.",
   sol:"$\\lVert5\\vec{MG}\\rVert=10\\iff 5\\,MG=10\\iff MG=2$. L'ensemble cherché est le <b>cercle de centre $G$ et de rayon $2$</b>." },
 { niv:"Défi",
   en:"Soit $ABC$ un triangle, $I$ le milieu de $[BC]$ et $G$ l'isobarycentre de $A,B,C$. Montrer que $A$, $G$, $I$ sont alignés et préciser la position de $G$ sur $[AI]$.",
   hint:"$I$ est le barycentre de $(B,1),(C,1)$ ; utilise l'associativité du barycentre pour regrouper $B$ et $C$.",
   sol:"$I$ est le barycentre de $(B,1),(C,1)$. Par <b>associativité</b>, $G$ (barycentre de $(A,1),(B,1),(C,1)$) est le barycentre de $(A,1)$ et $(I,2)$. Donc $\\vec{AG}=\\frac{2}{1+2}\\vec{AI}=\\frac23\\vec{AI}$ : $A,G,I$ sont <b>alignés</b> et $G$ est aux deux tiers de $[AI]$ à partir de $A$." }
],

"Produit scalaire et applications": [
 { niv:"Application",
   en:"Dans un repère orthonormé, on donne $\\vec u(1,2)$ et $\\vec v(3,-1)$. Calculer $\\vec u\\cdot\\vec v$ et dire si $\\vec u$ et $\\vec v$ sont orthogonaux.",
   hint:"En repère orthonormé, $\\vec u\\cdot\\vec v=x_ux_v+y_uy_v$ ; orthogonaux $\\iff$ produit scalaire nul.",
   sol:"$\\vec u\\cdot\\vec v=1\\times3+2\\times(-1)=3-2=1$. Comme $\\vec u\\cdot\\vec v=1\\ne0$, les vecteurs ne sont <b>pas orthogonaux</b>." },
 { niv:"Application",
   en:"Soit $ABC$ un triangle tel que $AB=5$, $AC=3$ et $\\widehat{A}=60^\\circ$. Calculer $\\vec{AB}\\cdot\\vec{AC}$.",
   hint:"$\\vec{AB}\\cdot\\vec{AC}=AB\\times AC\\times\\cos\\widehat{A}$.",
   sol:"$\\vec{AB}\\cdot\\vec{AC}=AB\\times AC\\times\\cos 60^\\circ=5\\times3\\times\\frac12=\\frac{15}{2}=7{,}5$." },
 { niv:"Moyen",
   en:"Dans un triangle $ABC$, on a $AB=7$, $AC=5$ et $\\widehat{A}=60^\\circ$. Calculer $BC$ (relation d'Al-Kashi).",
   hint:"$BC^2=AB^2+AC^2-2\\,AB\\cdot AC\\cos\\widehat{A}$.",
   sol:"$BC^2=7^2+5^2-2\\times7\\times5\\times\\cos60^\\circ=49+25-70\\times\\frac12=74-35=39$. Donc $BC=\\sqrt{39}\\approx6{,}24$." },
 { niv:"Moyen",
   en:"Soient $A$ et $B$ deux points fixes. Déterminer l'ensemble des points $M$ du plan tels que $\\vec{MA}\\cdot\\vec{MB}=0$.",
   hint:"$\\vec{MA}\\cdot\\vec{MB}=0$ signifie que les vecteurs sont orthogonaux, donc que l'angle $\\widehat{AMB}$ est droit.",
   sol:"$\\vec{MA}\\cdot\\vec{MB}=0\\iff \\vec{MA}\\perp\\vec{MB}\\iff \\widehat{AMB}=90^\\circ$ (ou $M\\in\\{A,B\\}$). L'ensemble cherché est le <b>cercle de diamètre $[AB]$</b>." },
 { niv:"Défi",
   en:"Soit $I$ le milieu de $[AB]$. Démontrer le théorème de la médiane : pour tout point $M$, $MA^2+MB^2=2\\,MI^2+\\dfrac{AB^2}{2}$.",
   hint:"Écris $\\vec{MA}=\\vec{MI}+\\vec{IA}$ et $\\vec{MB}=\\vec{MI}+\\vec{IB}$, avec $\\vec{IB}=-\\vec{IA}$, puis développe les carrés scalaires.",
   sol:"Comme $I$ est le milieu de $[AB]$, $\\vec{IB}=-\\vec{IA}$. Donc $MA^2=\\lVert\\vec{MI}+\\vec{IA}\\rVert^2=MI^2+2\\vec{MI}\\cdot\\vec{IA}+IA^2$ et $MB^2=\\lVert\\vec{MI}-\\vec{IA}\\rVert^2=MI^2-2\\vec{MI}\\cdot\\vec{IA}+IA^2$. En additionnant, les doubles produits s'éliminent : $MA^2+MB^2=2MI^2+2IA^2$. Or $IA=\\frac{AB}{2}$, donc $2IA^2=\\frac{AB^2}{2}$, d'où $MA^2+MB^2=2MI^2+\\frac{AB^2}{2}$." }
],

"Calcul trigonométrique": [
 { niv:"Application",
   en:"Résoudre dans $[0,2\\pi[$ l'équation $\\cos x=\\dfrac12$.",
   hint:"$\\cos x=\\cos\\frac{\\pi}{3}$ ; les solutions sont $x=\\frac{\\pi}{3}+2k\\pi$ ou $x=-\\frac{\\pi}{3}+2k\\pi$.",
   sol:"$\\cos x=\\frac12=\\cos\\frac{\\pi}{3}\\iff x\\equiv\\pm\\frac{\\pi}{3}\\ [2\\pi]$. Sur $[0,2\\pi[$ : $x=\\frac{\\pi}{3}$ ou $x=2\\pi-\\frac{\\pi}{3}=\\frac{5\\pi}{3}$. $S=\\left\\{\\frac{\\pi}{3},\\ \\frac{5\\pi}{3}\\right\\}$." },
 { niv:"Application",
   en:"Résoudre dans $[0,2\\pi[$ l'équation $\\sin x=\\dfrac{\\sqrt3}{2}$.",
   hint:"$\\sin x=\\sin\\frac{\\pi}{3}$ ; solutions $x=\\frac{\\pi}{3}+2k\\pi$ ou $x=\\pi-\\frac{\\pi}{3}+2k\\pi$.",
   sol:"$\\sin x=\\frac{\\sqrt3}{2}=\\sin\\frac{\\pi}{3}\\iff x\\equiv\\frac{\\pi}{3}\\ [2\\pi]$ ou $x\\equiv\\pi-\\frac{\\pi}{3}=\\frac{2\\pi}{3}\\ [2\\pi]$. Sur $[0,2\\pi[$ : $S=\\left\\{\\frac{\\pi}{3},\\ \\frac{2\\pi}{3}\\right\\}$." },
 { niv:"Moyen",
   en:"Simplifier l'expression $A=\\cos\\!\\left(\\dfrac{\\pi}{2}-x\\right)+\\sin(\\pi-x)$.",
   hint:"Utilise les angles associés : $\\cos\\!\\left(\\frac{\\pi}{2}-x\\right)=\\sin x$ et $\\sin(\\pi-x)=\\sin x$.",
   sol:"$\\cos\\!\\left(\\frac{\\pi}{2}-x\\right)=\\sin x$ et $\\sin(\\pi-x)=\\sin x$, donc $A=\\sin x+\\sin x=2\\sin x$." },
 { niv:"Moyen",
   en:"Démontrer l'identité : $\\cos(a+b)\\cos(a-b)=\\cos^2 a-\\sin^2 b$.",
   hint:"Développe chaque facteur avec les formules d'addition, puis utilise $\\cos^2 b=1-\\sin^2 b$ et $\\sin^2 a=1-\\cos^2 a$.",
   sol:"$\\cos(a+b)\\cos(a-b)=(\\cos a\\cos b-\\sin a\\sin b)(\\cos a\\cos b+\\sin a\\sin b)=\\cos^2 a\\cos^2 b-\\sin^2 a\\sin^2 b$. On remplace $\\cos^2 b=1-\\sin^2 b$ et $\\sin^2 a=1-\\cos^2 a$ : $=\\cos^2 a(1-\\sin^2 b)-(1-\\cos^2 a)\\sin^2 b=\\cos^2 a-\\cos^2 a\\sin^2 b-\\sin^2 b+\\cos^2 a\\sin^2 b=\\cos^2 a-\\sin^2 b.$" },
 { niv:"Défi",
   en:"Résoudre dans $[0,2\\pi[$ l'équation $2\\cos^2 x-3\\cos x+1=0$.",
   hint:"Pose $c=\\cos x$ et résous l'équation du second degré $2c^2-3c+1=0$, puis reviens à $x$ (avec $-1\\le c\\le1$).",
   sol:"Avec $c=\\cos x$ : $2c^2-3c+1=0$, discriminant $\\Delta=9-8=1$, donc $c=\\frac{3\\pm1}{4}$ : $c=1$ ou $c=\\frac12$. <br>$\\cos x=1\\iff x=0$. $\\cos x=\\frac12\\iff x=\\frac{\\pi}{3}$ ou $x=\\frac{5\\pi}{3}$. D'où $S=\\left\\{0,\\ \\frac{\\pi}{3},\\ \\frac{5\\pi}{3}\\right\\}$." }
],

"Suites numériques": [
 { niv:"Application",
   en:"Soit la suite définie par $u_n=3n-2$ pour $n\\in\\mathbb{N}$. Calculer $u_0,u_1,u_2$ et montrer que $(u_n)$ est arithmétique en précisant sa raison.",
   hint:"Calcule $u_{n+1}-u_n$ : si c'est une constante, la suite est arithmétique.",
   sol:"$u_0=-2$, $u_1=1$, $u_2=4$. $u_{n+1}-u_n=[3(n+1)-2]-[3n-2]=3$ (constante) : $(u_n)$ est <b>arithmétique</b> de raison $r=3$ et de premier terme $u_0=-2$." },
 { niv:"Application",
   en:"Soit $v_n=2\\times 3^{\\,n}$ pour $n\\in\\mathbb{N}$. Montrer que $(v_n)$ est géométrique et donner sa raison.",
   hint:"Calcule le quotient $\\dfrac{v_{n+1}}{v_n}$.",
   sol:"$\\frac{v_{n+1}}{v_n}=\\frac{2\\times3^{\\,n+1}}{2\\times3^{\\,n}}=3$ (constante) : $(v_n)$ est <b>géométrique</b> de raison $q=3$ et de premier terme $v_0=2$." },
 { niv:"Moyen",
   en:"Soit $(u_n)$ définie par $u_0=1$ et $u_{n+1}=2u_n+3$. On pose $w_n=u_n+3$. Montrer que $(w_n)$ est géométrique, puis exprimer $u_n$ en fonction de $n$.",
   hint:"Calcule $w_{n+1}=u_{n+1}+3$ et factorise pour faire apparaître $w_n=u_n+3$.",
   sol:"$w_{n+1}=u_{n+1}+3=2u_n+3+3=2u_n+6=2(u_n+3)=2w_n$ : $(w_n)$ est géométrique de raison $2$, $w_0=u_0+3=4$. Donc $w_n=4\\times2^{\\,n}=2^{\\,n+2}$, d'où $u_n=w_n-3=2^{\\,n+2}-3$." },
 { niv:"Moyen",
   en:"Calculer la somme $S=1+2+3+\\cdots+100$, puis démontrer que la somme des $n$ premiers nombres impairs vaut $1+3+5+\\cdots+(2n-1)=n^2$.",
   hint:"Pour $S$, utilise $1+2+\\cdots+n=\\frac{n(n+1)}{2}$. Pour les impairs, écris la somme comme (somme jusqu'à $2n$) moins (somme des pairs).",
   sol:"$S=\\frac{100\\times101}{2}=5050$.<br>Somme des impairs : $\\sum_{k=1}^{n}(2k-1)=2\\sum_{k=1}^{n}k-\\sum_{k=1}^{n}1=2\\cdot\\frac{n(n+1)}{2}-n=n(n+1)-n=n^2.$" },
 { niv:"Défi",
   en:"Soit $(u_n)$ définie par $u_0=0$ et $u_{n+1}=\\dfrac12 u_n+1$. On pose $t_n=u_n-2$. Montrer que $(t_n)$ est géométrique, exprimer $u_n$, puis étudier le sens de variation de $(u_n)$.",
   hint:"Le nombre $2$ est le point fixe ($\\ell=\\frac12\\ell+1$). Calcule $t_{n+1}=u_{n+1}-2$.",
   sol:"$t_{n+1}=u_{n+1}-2=\\frac12u_n+1-2=\\frac12u_n-1=\\frac12(u_n-2)=\\frac12 t_n$ : $(t_n)$ est géométrique de raison $\\frac12$, $t_0=u_0-2=-2$. Donc $t_n=-2\\left(\\frac12\\right)^{n}$ et $u_n=2+t_n=2-2\\left(\\frac12\\right)^{n}=2-\\left(\\frac12\\right)^{n-1}$.<br>Comme $t_n=-\\frac{2}{2^{n}}$ croît (vers $0$), $(u_n)$ est <b>strictement croissante</b> et majorée par $2$." }
],

"Limite d'une fonction numérique": [
 { niv:"Application",
   en:"Calculer $\\displaystyle\\lim_{x\\to 2}\\frac{x^2-4}{x-2}$.",
   hint:"Forme indéterminée $\\frac00$ : factorise le numérateur avec l'identité $x^2-4=(x-2)(x+2)$.",
   sol:"$\\frac{x^2-4}{x-2}=\\frac{(x-2)(x+2)}{x-2}=x+2$ (pour $x\\ne2$). Donc $\\displaystyle\\lim_{x\\to2}\\frac{x^2-4}{x-2}=2+2=4$." },
 { niv:"Application",
   en:"Calculer $\\displaystyle\\lim_{x\\to+\\infty}\\frac{3x^2-5}{x^2+1}$.",
   hint:"En $+\\infty$, mets en facteur le terme dominant $x^2$ au numérateur et au dénominateur.",
   sol:"$\\frac{3x^2-5}{x^2+1}=\\frac{x^2\\left(3-\\frac{5}{x^2}\\right)}{x^2\\left(1+\\frac{1}{x^2}\\right)}=\\frac{3-\\frac{5}{x^2}}{1+\\frac{1}{x^2}}\\xrightarrow[x\\to+\\infty]{}\\frac{3}{1}=3.$" },
 { niv:"Moyen",
   en:"Calculer $\\displaystyle\\lim_{x\\to 0}\\frac{\\sqrt{x+1}-1}{x}$.",
   hint:"Multiplie par la quantité conjuguée $\\sqrt{x+1}+1$.",
   sol:"$\\frac{\\sqrt{x+1}-1}{x}=\\frac{(\\sqrt{x+1}-1)(\\sqrt{x+1}+1)}{x(\\sqrt{x+1}+1)}=\\frac{(x+1)-1}{x(\\sqrt{x+1}+1)}=\\frac{x}{x(\\sqrt{x+1}+1)}=\\frac{1}{\\sqrt{x+1}+1}.$ D'où la limite $\\displaystyle\\lim_{x\\to0}=\\frac{1}{1+1}=\\frac12.$" },
 { niv:"Moyen",
   en:"Calculer $\\displaystyle\\lim_{x\\to+\\infty}\\left(\\sqrt{x^2+x}-x\\right)$.",
   hint:"Forme $\\infty-\\infty$ : multiplie par le conjugué $\\sqrt{x^2+x}+x$.",
   sol:"$\\sqrt{x^2+x}-x=\\frac{(x^2+x)-x^2}{\\sqrt{x^2+x}+x}=\\frac{x}{\\sqrt{x^2+x}+x}=\\frac{x}{x\\left(\\sqrt{1+\\frac1x}+1\\right)}=\\frac{1}{\\sqrt{1+\\frac1x}+1}\\xrightarrow[x\\to+\\infty]{}\\frac{1}{1+1}=\\frac12.$" },
 { niv:"Défi",
   en:"Soit $n\\in\\mathbb{N}^*$. Calculer $\\displaystyle\\lim_{x\\to 1}\\frac{x^n-1}{x-1}$.",
   hint:"Rappelle la factorisation $x^n-1=(x-1)(x^{n-1}+x^{n-2}+\\cdots+x+1)$.",
   sol:"$x^n-1=(x-1)(x^{n-1}+x^{n-2}+\\cdots+x+1)$, donc pour $x\\ne1$ : $\\frac{x^n-1}{x-1}=x^{n-1}+x^{n-2}+\\cdots+x+1$ ($n$ termes). En $x=1$, chaque terme vaut $1$ : $\\displaystyle\\lim_{x\\to1}\\frac{x^n-1}{x-1}=\\underbrace{1+1+\\cdots+1}_{n}=n.$" }
],

"Dérivation": [
 { niv:"Application",
   en:"Calculer la dérivée de $f(x)=3x^2-5x+2$, puis la valeur $f'(1)$.",
   hint:"$(x^2)'=2x$, $(x)'=1$, la dérivée d'une constante est nulle.",
   sol:"$f'(x)=6x-5$. Donc $f'(1)=6-5=1$." },
 { niv:"Application",
   en:"Déterminer l'équation de la tangente à la courbe de $f(x)=x^2$ au point d'abscisse $x_0=3$.",
   hint:"L'équation de la tangente en $x_0$ est $y=f'(x_0)(x-x_0)+f(x_0)$.",
   sol:"$f'(x)=2x$ donc $f'(3)=6$ et $f(3)=9$. Tangente : $y=6(x-3)+9=6x-9$." },
 { niv:"Moyen",
   en:"Dériver $g(x)=\\dfrac{2x+1}{x-1}$ sur $\\mathbb{R}\\setminus\\{1\\}$ et déterminer le signe de $g'$.",
   hint:"Utilise $\\left(\\dfrac{u}{v}\\right)'=\\dfrac{u'v-uv'}{v^2}$ avec $u=2x+1$, $v=x-1$.",
   sol:"$g'(x)=\\frac{2(x-1)-(2x+1)\\cdot1}{(x-1)^2}=\\frac{2x-2-2x-1}{(x-1)^2}=\\frac{-3}{(x-1)^2}$. Comme $(x-1)^2>0$, on a $g'(x)<0$ : $g$ est <b>strictement décroissante</b> sur $]-\\infty,1[$ et sur $]1,+\\infty[$." },
 { niv:"Moyen",
   en:"Soit $f(x)=x^3-3x+1$. Étudier les variations de $f$ sur $\\mathbb{R}$ (signe de $f'$, extremums).",
   hint:"$f'(x)=3x^2-3=3(x-1)(x+1)$ ; étudie son signe.",
   sol:"$f'(x)=3x^2-3=3(x^2-1)=3(x-1)(x+1)$. $f'(x)>0$ sur $]-\\infty,-1[$ et $]1,+\\infty[$, $f'(x)<0$ sur $]-1,1[$. Donc $f$ est croissante puis décroissante puis croissante. <b>Maximum local</b> en $x=-1$ : $f(-1)=-1+3+1=3$ ; <b>minimum local</b> en $x=1$ : $f(1)=1-3+1=-1$." },
 { niv:"Défi",
   en:"Montrer que pour tout $x\\ge 0$, $\\sqrt{1+x}\\le 1+\\dfrac{x}{2}$.",
   hint:"Étudie la fonction $h(x)=1+\\dfrac{x}{2}-\\sqrt{1+x}$ sur $[0,+\\infty[$ : calcule $h'$, son signe, et $h(0)$.",
   sol:"Posons $h(x)=1+\\frac{x}{2}-\\sqrt{1+x}$ sur $[0,+\\infty[$. Alors $h'(x)=\\frac12-\\frac{1}{2\\sqrt{1+x}}=\\frac{\\sqrt{1+x}-1}{2\\sqrt{1+x}}$. Pour $x\\ge0$, $\\sqrt{1+x}\\ge1$ donc $h'(x)\\ge0$ : $h$ est croissante. Comme $h(0)=1-1=0$, on a $h(x)\\ge h(0)=0$ pour tout $x\\ge0$, c'est-à-dire $1+\\frac{x}{2}\\ge\\sqrt{1+x}$." }
],

"La rotation dans le plan": [
 { niv:"Application",
   en:"Le plan est muni d'un repère orthonormé direct. Soit $r$ la rotation de centre $O$ et d'angle $+\\dfrac{\\pi}{2}$. Déterminer l'image du point $A(3,1)$ par $r$.",
   hint:"Une rotation de centre $O$ et d'angle $+\\dfrac{\\pi}{2}$ transforme le point de coordonnées $(x,y)$ en $(-y,x)$.",
   sol:"La rotation de centre $O$ et d'angle $+\\frac{\\pi}{2}$ envoie $(x,y)$ sur $(-y,x)$. Donc l'image de $A(3,1)$ est $A'(-1,3)$." },
 { niv:"Application",
   en:"Soit $r$ la rotation de centre $\\Omega$ et d'angle $\\theta$, et $A$ un point tel que $A\\ne\\Omega$. On pose $B=r(A)$. Comparer $\\Omega A$ et $\\Omega B$, et donner la mesure de l'angle orienté $(\\overrightarrow{\\Omega A},\\overrightarrow{\\Omega B})$.",
   hint:"Une rotation est une isométrie qui conserve les distances au centre, et l'angle de rotation est $\\theta$.",
   sol:"Par définition d'une rotation de centre $\\Omega$ et d'angle $\\theta$ : $\\Omega B=\\Omega A$ (les distances au centre sont conservées) et $(\\overrightarrow{\\Omega A},\\overrightarrow{\\Omega B})\\equiv\\theta\\ [2\\pi]$." },
 { niv:"Moyen",
   en:"Soit $ABC$ un triangle équilatéral direct de centre $G$. Soit $r$ la rotation de centre $G$ qui transforme $A$ en $B$. Déterminer l'angle de $r$, puis les images de $B$ et de $C$.",
   hint:"Dans un triangle équilatéral direct, $G$ voit $A,B,C$ sous des angles de $\\dfrac{2\\pi}{3}$.",
   sol:"On a $GA=GB=GC$ et $(\\overrightarrow{GA},\\overrightarrow{GB})=\\frac{2\\pi}{3}$, donc l'angle de $r$ est $\\frac{2\\pi}{3}$. La rotation permute les sommets dans le sens direct : $r(B)=C$ et $r(C)=A$." },
 { niv:"Moyen",
   en:"Soit $r$ une rotation de centre $O$ et d'angle $\\theta$. On considère le cercle $\\mathscr{C}$ de centre $I$ et de rayon $R$. Déterminer l'image de $\\mathscr{C}$ par $r$.",
   hint:"Une rotation est une isométrie : elle conserve les longueurs, donc les rayons.",
   sol:"Une rotation est une isométrie. L'image du cercle $\\mathscr{C}(I,R)$ est donc le cercle de même rayon $R$ et de centre $I'=r(I)$ : $r(\\mathscr{C})=\\mathscr{C}(I',R)$." },
 { niv:"Défi",
   en:"Soit $ABC$ un triangle équilatéral direct et $r$ la rotation de centre $A$ et d'angle $+\\dfrac{\\pi}{3}$. Pour un point $M$ quelconque du plan, on pose $M'=r(M)$. Montrer que $r(B)=C$, puis que $BM=CM'$.",
   hint:"Vérifie d'abord $r(B)=C$ à l'aide de $AB=AC$ et de l'angle $\\widehat{BAC}$, puis utilise que $r$ conserve les distances.",
   sol:"Comme $ABC$ est équilatéral direct, $AB=AC$ et $(\\overrightarrow{AB},\\overrightarrow{AC})=+\\frac{\\pi}{3}$ : la rotation de centre $A$ et d'angle $+\\frac{\\pi}{3}$ vérifie donc $r(B)=C$. Puisque $r$ est une isométrie et que $r(B)=C$, $r(M)=M'$, on a $BM=r(B)\\,r(M)=CM'$." }
],

"Étude et représentation des fonctions": [
 { niv:"Application",
   en:"Soit $f(x)=x^2-4x+3$. Écrire $f$ sous forme canonique, donner les coordonnées du sommet de la parabole et le sens de variation de $f$.",
   hint:"Forme canonique : $f(x)=(x-\\alpha)^2+\\beta$ avec $\\alpha=-\\dfrac{b}{2a}$.",
   sol:"$f(x)=x^2-4x+3=(x-2)^2-4+3=(x-2)^2-1$. Le sommet est $S(2,-1)$. $f$ est <b>décroissante</b> sur $]-\\infty,2]$ et <b>croissante</b> sur $[2,+\\infty[$." },
 { niv:"Application",
   en:"Soit $f(x)=\\dfrac{2x-1}{x+1}$. Déterminer son domaine de définition, montrer que $f(x)=2-\\dfrac{3}{x+1}$, puis en déduire le sens de variation de $f$.",
   hint:"Écris $2x-1=2(x+1)-3$ pour faire la division.",
   sol:"Domaine : $D_f=\\mathbb{R}\\setminus\\{-1\\}$. Comme $2x-1=2(x+1)-3$, on a $f(x)=2-\\frac{3}{x+1}$. Alors $f'(x)=\\frac{3}{(x+1)^2}>0$ : $f$ est <b>strictement croissante</b> sur $]-\\infty,-1[$ et sur $]-1,+\\infty[$ (asymptotes : $x=-1$ et $y=2$)." },
 { niv:"Moyen",
   en:"Soit $f(x)=x^3-3x$ sur $\\mathbb{R}$. Étudier la parité de $f$, ses variations et ses extremums locaux.",
   hint:"$f(-x)=-f(x)$ ; puis étudie le signe de $f'(x)=3x^2-3$.",
   sol:"$f(-x)=-x^3+3x=-f(x)$ : $f$ est <b>impaire</b>. $f'(x)=3x^2-3=3(x-1)(x+1)$ : $f'>0$ sur $]-\\infty,-1[$ et $]1,+\\infty[$, $f'<0$ sur $]-1,1[$. <b>Maximum local</b> en $x=-1$ : $f(-1)=2$ ; <b>minimum local</b> en $x=1$ : $f(1)=-2$." },
 { niv:"Moyen",
   en:"Soit $f(x)=\\dfrac{x}{x^2+1}$. Étudier la parité de $f$, ses limites en $\\pm\\infty$, et montrer que pour tout réel $x$, $-\\dfrac12\\le f(x)\\le \\dfrac12$.",
   hint:"Étudie le signe de $f(x)-\\dfrac12$ et de $f(x)+\\dfrac12$.",
   sol:"$f(-x)=-f(x)$ : $f$ est <b>impaire</b>. En $\\pm\\infty$, $f(x)\\sim\\frac{x}{x^2}=\\frac1x\\to 0$. De plus $f(x)-\\frac12=\\frac{2x-(x^2+1)}{2(x^2+1)}=\\frac{-(x-1)^2}{2(x^2+1)}\\le 0$ et $f(x)+\\frac12=\\frac{(x+1)^2}{2(x^2+1)}\\ge 0$. Donc $-\\frac12\\le f(x)\\le\\frac12$." },
 { niv:"Défi",
   en:"Soit $f(x)=\\dfrac{x^2+x+1}{x+1}$ définie sur $\\mathbb{R}\\setminus\\{-1\\}$. Montrer que $f(x)=x+\\dfrac{1}{x+1}$, déterminer l'asymptote oblique en $\\pm\\infty$, puis étudier les variations de $f$.",
   hint:"Division euclidienne : $x^2+x+1=(x+1)\\,x+1$. Puis calcule $f'$ et factorise.",
   sol:"$x^2+x+1=x(x+1)+1$ donc $f(x)=x+\\frac{1}{x+1}$. Comme $\\frac{1}{x+1}\\to 0$ en $\\pm\\infty$, la droite $y=x$ est <b>asymptote oblique</b>. $f'(x)=1-\\frac{1}{(x+1)^2}=\\frac{(x+1)^2-1}{(x+1)^2}=\\frac{x(x+2)}{(x+1)^2}$ : $f'>0$ sur $]-\\infty,-2[$ et $]0,+\\infty[$, $f'<0$ sur $]-2,-1[$ et $]-1,0[$. Maximum local en $x=-2$ : $f(-2)=-3$ ; minimum local en $x=0$ : $f(0)=1$." }
],

"Étude analytique du cercle": [
 { niv:"Application",
   en:"Déterminer une équation du cercle de centre $I(1,-2)$ et de rayon $3$.",
   hint:"Un cercle de centre $(a,b)$ et de rayon $R$ a pour équation $(x-a)^2+(y-b)^2=R^2$.",
   sol:"$(x-1)^2+(y+2)^2=9$." },
 { niv:"Application",
   en:"Soit l'ensemble $\\Gamma$ d'équation $x^2+y^2-4x+6y-3=0$. Montrer que $\\Gamma$ est un cercle et préciser son centre et son rayon.",
   hint:"Regroupe les termes en $x$ et en $y$ puis complète les carrés.",
   sol:"$x^2-4x+y^2+6y-3=0\\iff (x-2)^2-4+(y+3)^2-9-3=0\\iff (x-2)^2+(y+3)^2=16$. C'est le cercle de <b>centre $I(2,-3)$</b> et de <b>rayon $4$</b>." },
 { niv:"Moyen",
   en:"Dans un repère orthonormé, on donne $A(1,2)$ et $B(5,4)$. Déterminer une équation du cercle de diamètre $[AB]$.",
   hint:"$M$ appartient au cercle de diamètre $[AB]$ $\\iff \\overrightarrow{MA}\\cdot\\overrightarrow{MB}=0$.",
   sol:"$M(x,y)$ est sur le cercle $\\iff \\overrightarrow{MA}\\cdot\\overrightarrow{MB}=0\\iff (x-1)(x-5)+(y-2)(y-4)=0$. En développant : $x^2+y^2-6x-6y+13=0$, soit $(x-3)^2+(y-3)^2=5$ (centre le milieu $(3,3)$, rayon $\\sqrt5$)." },
 { niv:"Moyen",
   en:"On considère le cercle $\\mathscr{C}$ d'équation $(x-2)^2+(y-1)^2=4$ et la droite $(D):x+y-1=0$. Étudier la position relative de $(D)$ et de $\\mathscr{C}$.",
   hint:"Compare la distance du centre $I$ à la droite $(D)$ avec le rayon $R$.",
   sol:"Centre $I(2,1)$, rayon $R=2$. La distance de $I$ à $(D)$ est $d=\\frac{|2+1-1|}{\\sqrt{1^2+1^2}}=\\frac{2}{\\sqrt2}=\\sqrt2\\approx1{,}41$. Comme $d<R$, la droite $(D)$ est <b>sécante</b> au cercle (deux points d'intersection)." },
 { niv:"Défi",
   en:"Soit $\\mathscr{C}$ le cercle d'équation $x^2+y^2=25$ et $A(3,4)$. Vérifier que $A\\in\\mathscr{C}$, puis déterminer une équation de la tangente à $\\mathscr{C}$ en $A$.",
   hint:"La tangente en $A$ est perpendiculaire à $(OA)$ ; pour $x^2+y^2=R^2$ elle s'écrit $x\\,x_A+y\\,y_A=R^2$.",
   sol:"$3^2+4^2=9+16=25$ donc $A\\in\\mathscr{C}$. La tangente en $A$ est perpendiculaire au rayon $(OA)$. Pour le cercle $x^2+y^2=25$, elle a pour équation $x\\,x_A+y\\,y_A=25$, soit $3x+4y=25$ (qui passe bien par $A$ car $9+16=25$)." }
],

"Dénombrement": [
 { niv:"Application",
   en:"Combien d'anagrammes (mots, ayant un sens ou non) peut-on former avec les $5$ lettres distinctes du mot « MATHS » ?",
   hint:"C'est le nombre de permutations de $5$ lettres distinctes.",
   sol:"Chaque anagramme est une permutation des $5$ lettres distinctes : il y en a $5!=120$." },
 { niv:"Application",
   en:"Dans un groupe de $10$ personnes, de combien de façons peut-on choisir un comité de $3$ personnes ?",
   hint:"L'ordre ne compte pas : c'est une combinaison $\\binom{10}{3}$.",
   sol:"$\\binom{10}{3}=\\dfrac{10\\times9\\times8}{3\\times2\\times1}=120$ façons." },
 { niv:"Moyen",
   en:"Combien de codes de $4$ chiffres, tous distincts, peut-on former avec les chiffres de $0$ à $9$ ?",
   hint:"Les chiffres sont ordonnés et distincts : c'est un arrangement $A_{10}^{4}$.",
   sol:"$A_{10}^{4}=10\\times9\\times8\\times7=5040$ codes." },
 { niv:"Moyen",
   en:"Une urne contient $5$ boules rouges et $3$ boules vertes. On tire simultanément $3$ boules. Combien de tirages contiennent exactement $2$ boules rouges ?",
   hint:"Choisis $2$ rouges parmi $5$ ET $1$ verte parmi $3$, puis multiplie.",
   sol:"On choisit $2$ rouges parmi $5$ et $1$ verte parmi $3$ : $\\binom{5}{2}\\times\\binom{3}{1}=10\\times3=30$ tirages (sur $\\binom{8}{3}=56$ tirages possibles)." },
 { niv:"Défi",
   en:"Combien d'anagrammes distinctes peut-on former avec les lettres du mot « ANANAS » ?",
   hint:"Permutations avec répétitions : $\\dfrac{n!}{n_1!\\,n_2!\\cdots}$. Ici la lettre A est répétée $3$ fois et N $2$ fois.",
   sol:"Le mot « ANANAS » a $6$ lettres avec A répété $3$ fois et N répété $2$ fois. Le nombre d'anagrammes distinctes est $\\dfrac{6!}{3!\\,2!}=\\dfrac{720}{6\\times2}=60$." }
],

"Arithmétique dans ℤ": [
 { niv:"Application",
   en:"Déterminer $\\operatorname{pgcd}(48,36)$ à l'aide de l'algorithme d'Euclide.",
   hint:"Divisions successives : remplace $(a,b)$ par $(b,\\ \\text{reste de } a\\div b)$ jusqu'à un reste nul.",
   sol:"$48=36\\times1+12$, puis $36=12\\times3+0$. Le dernier reste non nul est $12$, donc $\\operatorname{pgcd}(48,36)=12$." },
 { niv:"Application",
   en:"Soit $a\\in\\mathbb{Z}$ tel que $a\\equiv 3\\ [7]$. Montrer que $a^2\\equiv 2\\ [7]$.",
   hint:"Élève la congruence au carré.",
   sol:"Si $a\\equiv3\\ [7]$ alors $a^2\\equiv3^2=9\\equiv2\\ [7]$ (car $9=7+2$)." },
 { niv:"Moyen",
   en:"Résoudre dans $\\mathbb{Z}$ la congruence $2x\\equiv 1\\ [5]$.",
   hint:"Cherche l'inverse de $2$ modulo $5$, c'est-à-dire un entier $u$ tel que $2u\\equiv1\\ [5]$.",
   sol:"On a $2\\times3=6\\equiv1\\ [5]$, donc $3$ est l'inverse de $2$ modulo $5$. En multipliant par $3$ : $x\\equiv3\\ [5]$. L'ensemble des solutions est $\\{3+5k,\\ k\\in\\mathbb{Z}\\}$." },
 { niv:"Moyen",
   en:"Déterminer le reste de la division euclidienne de $2^{100}$ par $7$.",
   hint:"Calcule $2^3\\bmod 7$, puis utilise $100=3\\times33+1$.",
   sol:"$2^3=8\\equiv1\\ [7]$. Donc $2^{100}=2^{3\\times33+1}=(2^3)^{33}\\times2\\equiv1^{33}\\times2=2\\ [7]$. Le reste est $\\boxed{2}$." },
 { niv:"Défi",
   en:"Montrer que pour tout entier $n\\in\\mathbb{Z}$, le nombre $n^3-n$ est divisible par $6$.",
   hint:"Factorise $n^3-n=(n-1)\\,n\\,(n+1)$ : trois entiers consécutifs.",
   sol:"$n^3-n=n(n^2-1)=(n-1)\\,n\\,(n+1)$ : c'est le produit de trois entiers consécutifs. Parmi trois entiers consécutifs, il y en a au moins un divisible par $2$ et au moins un divisible par $3$. Le produit est donc divisible par $2$ et par $3$ ; comme $\\operatorname{pgcd}(2,3)=1$, il est divisible par $6$." }
],

"Vecteurs de l'espace": [
 { niv:"Application",
   en:"Dans un repère orthonormé de l'espace, on donne $A(1,0,2)$ et $B(3,1,1)$. Déterminer les coordonnées de $\\overrightarrow{AB}$ et sa norme $\\lVert\\overrightarrow{AB}\\rVert$.",
   hint:"$\\overrightarrow{AB}=(x_B-x_A,\\ y_B-y_A,\\ z_B-z_A)$ et $\\lVert\\vec u\\rVert=\\sqrt{x^2+y^2+z^2}$.",
   sol:"$\\overrightarrow{AB}=(3-1,\\ 1-0,\\ 1-2)=(2,1,-1)$. Donc $\\lVert\\overrightarrow{AB}\\rVert=\\sqrt{2^2+1^2+(-1)^2}=\\sqrt{6}$." },
 { niv:"Application",
   en:"On considère $\\vec u(1,2,-1)$ et $\\vec v(-2,-4,2)$. Montrer que $\\vec u$ et $\\vec v$ sont colinéaires.",
   hint:"Cherche un réel $k$ tel que $\\vec v=k\\,\\vec u$.",
   sol:"On remarque que $\\vec v=(-2,-4,2)=-2\\,(1,2,-1)=-2\\,\\vec u$. Il existe donc $k=-2$ tel que $\\vec v=k\\vec u$ : $\\vec u$ et $\\vec v$ sont <b>colinéaires</b>." },
 { niv:"Moyen",
   en:"On donne $\\vec u(1,0,1)$, $\\vec v(0,1,1)$ et $\\vec w(1,1,2)$. Montrer que ces trois vecteurs sont coplanaires.",
   hint:"Trois vecteurs sont coplanaires si l'un est combinaison linéaire des deux autres : cherche $a,b$ tels que $\\vec w=a\\vec u+b\\vec v$.",
   sol:"Cherchons $a,b$ tels que $\\vec w=a\\vec u+b\\vec v$, soit $(a,\\ b,\\ a+b)=(1,1,2)$. On obtient $a=1$, $b=1$ et $a+b=2$ (vérifié). Donc $\\vec w=\\vec u+\\vec v$ : les trois vecteurs sont <b>coplanaires</b>." },
 { niv:"Moyen",
   en:"On donne $A(1,1,0)$, $B(2,3,1)$ et $C(0,-1,-1)$. Montrer que les points $A$, $B$ et $C$ sont alignés.",
   hint:"Montre que $\\overrightarrow{AB}$ et $\\overrightarrow{AC}$ sont colinéaires.",
   sol:"$\\overrightarrow{AB}=(1,2,1)$ et $\\overrightarrow{AC}=(-1,-2,-1)=-\\overrightarrow{AB}$. Les vecteurs $\\overrightarrow{AB}$ et $\\overrightarrow{AC}$ sont colinéaires, donc les points $A$, $B$, $C$ sont <b>alignés</b>." },
 { niv:"Défi",
   en:"On donne $A(1,0,0)$, $B(0,1,0)$, $C(0,0,1)$ et $D(-1,1,1)$. Montrer que les points $A$, $B$, $C$ et $D$ sont coplanaires.",
   hint:"Il suffit de montrer que $\\overrightarrow{AD}$ est une combinaison linéaire de $\\overrightarrow{AB}$ et $\\overrightarrow{AC}$.",
   sol:"$\\overrightarrow{AB}=(-1,1,0)$, $\\overrightarrow{AC}=(-1,0,1)$, $\\overrightarrow{AD}=(-2,1,1)$. Cherchons $a,b$ tels que $\\overrightarrow{AD}=a\\overrightarrow{AB}+b\\overrightarrow{AC}=(-a-b,\\ a,\\ b)$. On obtient $a=1$, $b=1$ et $-a-b=-2$ (vérifié). Donc $\\overrightarrow{AD}=\\overrightarrow{AB}+\\overrightarrow{AC}$ : les quatre points sont <b>coplanaires</b>." }
],

"Géométrie dans l'espace (droites et plans)": [
 { niv:"Application",
   en:"Soit un cube $ABCDEFGH$ ($ABCD$ la face du bas, $EFGH$ celle du haut, $E$ au-dessus de $A$, etc.). Citer : une arête parallèle à $(AB)$, une arête sécante à $(AB)$, et une arête non coplanaire avec $(AB)$.",
   hint:"Repère les arêtes parallèles, celles qui se coupent, et celles qui ne sont dans aucun plan commun avec $(AB)$.",
   sol:"Parallèle à $(AB)$ : $(DC)$ (ou $(EF)$, $(HG)$). Sécante à $(AB)$ : $(AD)$ (ou $(BC)$, $(AE)$, $(BF)$). Non coplanaire (droites <b>gauches</b>) avec $(AB)$ : $(CG)$ (ou $(DH)$)." },
 { niv:"Application",
   en:"Vrai ou faux, en justifiant : « Deux droites de l'espace qui n'ont aucun point commun sont parallèles. »",
   hint:"Pense aux droites non coplanaires.",
   sol:"<b>Faux.</b> Deux droites sans point commun peuvent être <b>non coplanaires</b> (gauches). Le parallélisme exige en plus qu'elles soient coplanaires (situées dans un même plan)." },
 { niv:"Moyen",
   en:"Soit un cube $ABCDEFGH$. Montrer que la droite $(AB)$ est parallèle au plan $(EFG)$.",
   hint:"Trouve dans le plan $(EFG)$ une droite parallèle à $(AB)$.",
   sol:"$ABFE$ est un carré, donc $(AB)\\parallel(EF)$. Or $(EF)\\subset(EFG)$ et $(AB)\\not\\subset(EFG)$. Une droite parallèle à une droite d'un plan (sans être incluse dans ce plan) est parallèle à ce plan : donc $(AB)\\parallel(EFG)$." },
 { niv:"Moyen",
   en:"Deux plans $P$ et $P'$ se coupent selon une droite $\\Delta$. Une droite $d$ incluse dans $P$ et une droite $d'$ incluse dans $P'$ vérifient $d\\parallel d'$. Que peut-on dire de la droite $\\Delta$ ? Énoncer le résultat utilisé.",
   hint:"C'est exactement le « théorème du toit ».",
   sol:"D'après le <b>théorème du toit</b> : si $d\\parallel d'$ avec $d\\subset P$, $d'\\subset P'$ et $P\\cap P'=\\Delta$, alors la droite d'intersection $\\Delta$ est parallèle à $d$ (et à $d'$)." },
 { niv:"Défi",
   en:"Soit $ABCD$ un tétraèdre. On note $I$ et $J$ les milieux respectifs de $[AB]$ et $[AC]$. Montrer que la droite $(IJ)$ est parallèle au plan $(BCD)$.",
   hint:"Applique le théorème des milieux dans le triangle $ABC$, puis « une droite parallèle à une droite d'un plan est parallèle à ce plan ».",
   sol:"Dans le triangle $ABC$, $I$ et $J$ sont les milieux de $[AB]$ et $[AC]$, donc d'après le théorème des milieux $(IJ)\\parallel(BC)$. Or $(BC)\\subset(BCD)$ et $(IJ)\\not\\subset(BCD)$. Une droite parallèle à une droite d'un plan (sans y être incluse) est parallèle à ce plan : donc $(IJ)\\parallel(BCD)$." }
],

"Produit scalaire dans l'espace": [
 { niv:"Application",
   en:"Dans un repère orthonormé, on donne $\\vec u(1,2,-1)$ et $\\vec v(3,-1,2)$. Calculer le produit scalaire $\\vec u\\cdot\\vec v$.",
   hint:"En repère orthonormé, $\\vec u\\cdot\\vec v=xx'+yy'+zz'$.",
   sol:"$\\vec u\\cdot\\vec v=1\\times3+2\\times(-1)+(-1)\\times2=3-2-2=-1$." },
 { niv:"Application",
   en:"On donne $\\vec u(1,1,0)$ et $\\vec v(1,-1,2)$. Montrer que $\\vec u$ et $\\vec v$ sont orthogonaux.",
   hint:"$\\vec u\\perp\\vec v\\iff\\vec u\\cdot\\vec v=0$.",
   sol:"$\\vec u\\cdot\\vec v=1\\times1+1\\times(-1)+0\\times2=1-1+0=0$. Donc $\\vec u$ et $\\vec v$ sont <b>orthogonaux</b>." },
 { niv:"Moyen",
   en:"On donne $A(1,0,1)$, $B(2,1,0)$ et $C(0,2,1)$. Calculer $\\overrightarrow{AB}\\cdot\\overrightarrow{AC}$, puis $\\cos\\widehat{A}$.",
   hint:"$\\cos\\widehat{A}=\\dfrac{\\overrightarrow{AB}\\cdot\\overrightarrow{AC}}{\\lVert\\overrightarrow{AB}\\rVert\\,\\lVert\\overrightarrow{AC}\\rVert}$.",
   sol:"$\\overrightarrow{AB}=(1,1,-1)$, $\\overrightarrow{AC}=(-1,2,0)$. Alors $\\overrightarrow{AB}\\cdot\\overrightarrow{AC}=-1+2+0=1$. De plus $\\lVert\\overrightarrow{AB}\\rVert=\\sqrt3$ et $\\lVert\\overrightarrow{AC}\\rVert=\\sqrt5$, donc $\\cos\\widehat{A}=\\dfrac{1}{\\sqrt3\\,\\sqrt5}=\\dfrac{1}{\\sqrt{15}}$ (soit $\\widehat{A}\\approx75{,}0^\\circ$)." },
 { niv:"Moyen",
   en:"Déterminer une équation cartésienne du plan $P$ passant par $A(1,0,2)$ et de vecteur normal $\\vec n(2,-1,3)$.",
   hint:"$M(x,y,z)\\in P\\iff \\vec n\\cdot\\overrightarrow{AM}=0$.",
   sol:"$M(x,y,z)\\in P\\iff\\vec n\\cdot\\overrightarrow{AM}=0\\iff 2(x-1)-1(y-0)+3(z-2)=0$, soit $2x-y+3z-8=0$." },
 { niv:"Défi",
   en:"Soient $A$ et $B$ deux points fixes de l'espace. Montrer que l'ensemble des points $M$ tels que $\\overrightarrow{MA}\\cdot\\overrightarrow{MB}=0$ est la sphère de diamètre $[AB]$.",
   hint:"Introduis le milieu $I$ de $[AB]$ et écris $\\overrightarrow{MA}=\\overrightarrow{MI}+\\overrightarrow{IA}$, avec $\\overrightarrow{IB}=-\\overrightarrow{IA}$.",
   sol:"Soit $I$ le milieu de $[AB]$, donc $\\overrightarrow{IB}=-\\overrightarrow{IA}$. Alors $\\overrightarrow{MA}\\cdot\\overrightarrow{MB}=(\\overrightarrow{MI}+\\overrightarrow{IA})\\cdot(\\overrightarrow{MI}-\\overrightarrow{IA})=MI^2-IA^2$. Donc $\\overrightarrow{MA}\\cdot\\overrightarrow{MB}=0\\iff MI^2=IA^2\\iff MI=\\dfrac{AB}{2}$. C'est la sphère de centre $I$ et de rayon $\\dfrac{AB}{2}$, c'est-à-dire la <b>sphère de diamètre $[AB]$</b>." }
],

"Produit vectoriel dans l'espace": [
 { niv:"Application",
   en:"Calculer le produit vectoriel $\\vec u\\wedge\\vec v$ pour $\\vec u(1,0,0)$ et $\\vec v(0,1,0)$.",
   hint:"$\\vec u\\wedge\\vec v=(yz'-zy',\\ zx'-xz',\\ xy'-yx')$.",
   sol:"$\\vec u\\wedge\\vec v=(0\\cdot0-0\\cdot1,\\ 0\\cdot0-1\\cdot0,\\ 1\\cdot1-0\\cdot0)=(0,0,1)$." },
 { niv:"Application",
   en:"Calculer $\\vec u\\wedge\\vec v$ pour $\\vec u(1,2,-1)$ et $\\vec v(2,1,1)$.",
   hint:"Applique la formule composante par composante.",
   sol:"$\\vec u\\wedge\\vec v=\\big(2\\cdot1-(-1)\\cdot1,\\ (-1)\\cdot2-1\\cdot1,\\ 1\\cdot1-2\\cdot2\\big)=(2+1,\\ -2-1,\\ 1-4)=(3,-3,-3)$." },
 { niv:"Moyen",
   en:"On donne $A(0,0,0)$, $B(1,2,0)$ et $C(0,1,3)$. Calculer l'aire du triangle $ABC$.",
   hint:"L'aire du triangle vaut $\\dfrac12\\lVert\\overrightarrow{AB}\\wedge\\overrightarrow{AC}\\rVert$.",
   sol:"$\\overrightarrow{AB}=(1,2,0)$, $\\overrightarrow{AC}=(0,1,3)$. $\\overrightarrow{AB}\\wedge\\overrightarrow{AC}=(2\\cdot3-0\\cdot1,\\ 0\\cdot0-1\\cdot3,\\ 1\\cdot1-2\\cdot0)=(6,-3,1)$. Donc l'aire $=\\dfrac12\\sqrt{6^2+(-3)^2+1^2}=\\dfrac12\\sqrt{46}$." },
 { niv:"Moyen",
   en:"On donne $\\vec u(1,2,3)$ et $\\vec v(2,4,6)$. En calculant $\\vec u\\wedge\\vec v$, montrer que $\\vec u$ et $\\vec v$ sont colinéaires.",
   hint:"Deux vecteurs sont colinéaires si et seulement si leur produit vectoriel est le vecteur nul.",
   sol:"$\\vec u\\wedge\\vec v=(2\\cdot6-3\\cdot4,\\ 3\\cdot2-1\\cdot6,\\ 1\\cdot4-2\\cdot2)=(12-12,\\ 6-6,\\ 4-4)=(0,0,0)=\\vec0$. Comme $\\vec u\\wedge\\vec v=\\vec0$, les vecteurs $\\vec u$ et $\\vec v$ sont <b>colinéaires</b> (en effet $\\vec v=2\\vec u$)." },
 { niv:"Défi",
   en:"Soit le tétraèdre $ABCD$ avec $A(0,0,0)$, $B(1,0,0)$, $C(0,1,0)$ et $D(0,0,1)$. Montrer que son volume vaut $\\dfrac16$ à l'aide du produit mixte $V=\\dfrac16\\big\\lvert(\\overrightarrow{AB}\\wedge\\overrightarrow{AC})\\cdot\\overrightarrow{AD}\\big\\rvert$.",
   hint:"Calcule d'abord $\\overrightarrow{AB}\\wedge\\overrightarrow{AC}$, puis le produit scalaire avec $\\overrightarrow{AD}$, enfin divise par $6$.",
   sol:"$\\overrightarrow{AB}=(1,0,0)$, $\\overrightarrow{AC}=(0,1,0)$, $\\overrightarrow{AD}=(0,0,1)$. $\\overrightarrow{AB}\\wedge\\overrightarrow{AC}=(0\\cdot0-0\\cdot1,\\ 0\\cdot0-1\\cdot0,\\ 1\\cdot1-0\\cdot0)=(0,0,1)$. Puis $(\\overrightarrow{AB}\\wedge\\overrightarrow{AC})\\cdot\\overrightarrow{AD}=(0,0,1)\\cdot(0,0,1)=1$. Donc $V=\\dfrac16\\lvert1\\rvert=\\dfrac16$." }
]

});
