/* ===== Séries d'exercices curatées — Physique-Chimie 1ère Bac Sciences Maths (programme marocain) =====
   Clés = titres EXACTS des chapitres (window.EDU_SUBJECTS.pc.chapters), préfixe « Physique — » / « Chimie — » compris.
   Chaque exercice : { niv:'Application'|'Moyen'|'Défi', en, hint, sol } (HTML + LaTeX $…$).
   Les exercices « Défi » marqués 🏅 sont de niveau/format olympiades. On prend g = 9,8 N/kg sauf mention. */
window.PB_EXOS = window.PB_EXOS || {};
Object.assign(window.PB_EXOS, {

"Physique — Rotation d'un solide autour d'un axe fixe": [
 { niv:"Application",
   en:"Un disque tourne uniformément autour de son axe à la fréquence $N=300\\ \\text{tr/min}$. Calculer sa vitesse angulaire $\\omega$ en $\\text{rad/s}$.",
   hint:"$\\omega=2\\pi n$ où $n$ est la fréquence en tours par seconde : $n=\\dfrac{N}{60}$.",
   sol:"$n=\\dfrac{300}{60}=5\\ \\text{tr/s}$, donc $\\omega=2\\pi n=2\\pi\\times5=10\\pi\\approx31{,}4\\ \\text{rad/s}$." },
 { niv:"Application",
   en:"Un point $M$ d'un solide en rotation se situe à la distance $R=20\\ \\text{cm}$ de l'axe. La vitesse angulaire est $\\omega=10\\ \\text{rad/s}$. Déterminer la vitesse linéaire $v$ de $M$.",
   hint:"$v=R\\,\\omega$ avec $R$ en mètres.",
   sol:"$R=0{,}20\\ \\text{m}$, donc $v=R\\,\\omega=0{,}20\\times10=2\\ \\text{m/s}$." },
 { niv:"Moyen",
   en:"Une roue de rayon $R=30\\ \\text{cm}$ tourne uniformément ; un point de sa jante parcourt une distance de $6\\ \\text{m}$ en $2\\ \\text{s}$. Calculer la vitesse linéaire $v$, la vitesse angulaire $\\omega$ et la fréquence de rotation $f$.",
   hint:"$v=\\dfrac{d}{t}$ ; $\\omega=\\dfrac{v}{R}$ ; $f=\\dfrac{\\omega}{2\\pi}$.",
   sol:"$v=\\dfrac{6}{2}=3\\ \\text{m/s}$. $\\omega=\\dfrac{v}{R}=\\dfrac{3}{0{,}30}=10\\ \\text{rad/s}$. $f=\\dfrac{\\omega}{2\\pi}=\\dfrac{10}{2\\pi}\\approx1{,}59\\ \\text{Hz}$ (soit $\\approx95{,}5\\ \\text{tr/min}$)." },
 { niv:"Moyen",
   en:"Un solide part à l'instant $t=0$ de l'abscisse angulaire $\\theta_0=0$ et tourne uniformément à $\\omega=4\\ \\text{rad/s}$. Déterminer son abscisse angulaire $\\theta$ à $t=5\\ \\text{s}$, puis le nombre de tours effectués.",
   hint:"$\\theta=\\theta_0+\\omega t$ ; nombre de tours $=\\dfrac{\\theta}{2\\pi}$.",
   sol:"$\\theta=\\omega t=4\\times5=20\\ \\text{rad}$. Nombre de tours $=\\dfrac{20}{2\\pi}\\approx3{,}18$ tours." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> Deux poulies de rayons $R_1=10\\ \\text{cm}$ et $R_2=25\\ \\text{cm}$ sont reliées par une courroie inextensible qui ne glisse pas. La petite poulie tourne à $N_1=600\\ \\text{tr/min}$. (a) Calculer la vitesse linéaire $v$ de la courroie. (b) En déduire la vitesse angulaire $\\omega_2$ et la fréquence $N_2$ de la grande poulie.",
   hint:"La courroie impose la <b>même vitesse linéaire</b> aux deux jantes : $R_1\\omega_1=R_2\\omega_2=v$.",
   sol:"$\\omega_1=\\dfrac{2\\pi N_1}{60}=\\dfrac{2\\pi\\times600}{60}=20\\pi\\ \\text{rad/s}$. (a) $v=R_1\\omega_1=0{,}10\\times20\\pi=2\\pi\\approx6{,}28\\ \\text{m/s}$. (b) $\\omega_2=\\dfrac{v}{R_2}=\\dfrac{2\\pi}{0{,}25}=8\\pi\\ \\text{rad/s}$, et $N_2=\\dfrac{60\\,\\omega_2}{2\\pi}=\\dfrac{60\\times8\\pi}{2\\pi}=240\\ \\text{tr/min}$. (La grande poulie tourne moins vite, comme attendu.)" }
],

"Physique — Travail et puissance d'une force": [
 { niv:"Application",
   en:"Une force constante horizontale $F=50\\ \\text{N}$ déplace un objet de $d=8\\ \\text{m}$ dans sa propre direction. Calculer le travail $W$ de $\\vec F$.",
   hint:"$W=F\\,d\\cos\\alpha$, avec ici $\\alpha=0$.",
   sol:"$W=F\\,d\\cos0^\\circ=50\\times8\\times1=400\\ \\text{J}$." },
 { niv:"Application",
   en:"On soulève verticalement, à vitesse constante, une masse $m=5\\ \\text{kg}$ d'une hauteur $h=2\\ \\text{m}$. Calculer le travail du poids. (On prend $g=9{,}8\\ \\text{N/kg}$.)",
   hint:"Le poids est dirigé vers le bas et le déplacement vers le haut : le travail est <b>résistant</b>, $W=-mgh$.",
   sol:"$W(\\vec P)=-mgh=-5\\times9{,}8\\times2=-98\\ \\text{J}$ (travail résistant)." },
 { niv:"Moyen",
   en:"Un traîneau est tiré par une corde faisant un angle $\\alpha=30^\\circ$ avec l'horizontale, avec une force $F=120\\ \\text{N}$, sur une distance $d=15\\ \\text{m}$. (a) Calculer le travail de $\\vec F$. (b) Si le trajet dure $10\\ \\text{s}$, calculer la puissance moyenne.",
   hint:"$W=F\\,d\\cos\\alpha$ ; $P=\\dfrac{W}{t}$.",
   sol:"(a) $W=F\\,d\\cos30^\\circ=120\\times15\\times\\dfrac{\\sqrt3}{2}\\approx1559\\ \\text{J}$. (b) $P=\\dfrac{W}{t}=\\dfrac{1559}{10}\\approx156\\ \\text{W}$." },
 { niv:"Moyen",
   en:"Une voiture roule à vitesse constante $v=20\\ \\text{m/s}$. Le moteur exerce une force motrice $F=800\\ \\text{N}$ (dans le sens du mouvement, égale en norme aux frottements). Calculer la puissance développée.",
   hint:"Pour une force dans le sens du mouvement à vitesse $v$ : $P=F\\,v$.",
   sol:"$P=F\\,v=800\\times20=16\\,000\\ \\text{W}=16\\ \\text{kW}$." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> Un bloc de masse $m=2\\ \\text{kg}$ glisse en <b>descendant</b> un plan incliné d'angle $\\alpha=30^\\circ$, sur une longueur $L=4\\ \\text{m}$. Une force de frottement $f=3\\ \\text{N}$ s'oppose au mouvement. ($g=9{,}8\\ \\text{N/kg}$.) Calculer les travaux du poids, de la force de frottement et de la réaction normale, puis le travail total des forces.",
   hint:"La normale ne travaille pas. Le poids travaille par sa composante le long du plan : $W(\\vec P)=+mg\\,L\\sin\\alpha$ en descente.",
   sol:"Déplacement de norme $L=4\\ \\text{m}$ le long du plan. Poids : $W(\\vec P)=+mgL\\sin\\alpha=2\\times9{,}8\\times4\\times0{,}5=+39{,}2\\ \\text{J}$ (moteur). Frottement : $W(\\vec f)=-f\\,L=-3\\times4=-12\\ \\text{J}$. Réaction normale : $W(\\vec N)=0$ (perpendiculaire au déplacement). Travail total : $W_{\\text{tot}}=39{,}2-12+0=+27{,}2\\ \\text{J}$." }
],

"Physique — Travail et énergie cinétique": [
 { niv:"Application",
   en:"Une voiture de masse $m=1200\\ \\text{kg}$ roule à $v=25\\ \\text{m/s}$. Calculer son énergie cinétique.",
   hint:"$E_c=\\dfrac12 m v^2$.",
   sol:"$E_c=\\dfrac12\\times1200\\times25^2=\\dfrac12\\times1200\\times625=375\\,000\\ \\text{J}=375\\ \\text{kJ}$." },
 { niv:"Application",
   en:"Une balle de masse $m=50\\ \\text{g}$ passe de la vitesse $v_0=10\\ \\text{m/s}$ à $v=30\\ \\text{m/s}$. Calculer la variation de son énergie cinétique.",
   hint:"$\\Delta E_c=\\dfrac12 m\\,(v^2-v_0^2)$, avec $m$ en kg.",
   sol:"$m=0{,}05\\ \\text{kg}$. $\\Delta E_c=\\dfrac12\\times0{,}05\\times(30^2-10^2)=\\dfrac12\\times0{,}05\\times800=20\\ \\text{J}$." },
 { niv:"Moyen",
   en:"Une voiture de masse $m=1000\\ \\text{kg}$ freine et s'arrête sur une distance $d=50\\ \\text{m}$ en partant de $v=20\\ \\text{m/s}$. À l'aide du théorème de l'énergie cinétique, calculer la force de freinage moyenne (supposée constante et opposée au mouvement).",
   hint:"$\\Delta E_c=W(\\vec F_{\\text{frein}})=-F\\,d$.",
   sol:"$\\Delta E_c=0-\\dfrac12\\times1000\\times20^2=-200\\,000\\ \\text{J}$. Or $\\Delta E_c=-F\\,d$, donc $F=\\dfrac{200\\,000}{50}=4000\\ \\text{N}$." },
 { niv:"Moyen",
   en:"Un objet de masse $m=2\\ \\text{kg}$ est lâché sans vitesse initiale et tombe en chute libre d'une hauteur $h=5\\ \\text{m}$ (on néglige l'air, $g=9{,}8\\ \\text{N/kg}$). Déterminer sa vitesse en arrivant au sol avec le théorème de l'énergie cinétique.",
   hint:"Seul le poids travaille : $\\dfrac12 m v^2=mgh$, d'où $v=\\sqrt{2gh}$.",
   sol:"$\\dfrac12 m v^2 - 0 = W(\\vec P)=mgh$, donc $v=\\sqrt{2gh}=\\sqrt{2\\times9{,}8\\times5}=\\sqrt{98}\\approx9{,}9\\ \\text{m/s}$." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> Une bille de masse $m=0{,}2\\ \\text{kg}$ est fixée à l'extrémité d'un fil de longueur $L=1\\ \\text{m}$ ; on la lâche sans vitesse depuis la position horizontale (fil tendu). ($g=9{,}8\\ \\text{N/kg}$, frottements négligés.) (a) Déterminer la vitesse de la bille au point le plus bas. (b) En déduire la tension du fil en ce point.",
   hint:"(a) Théorème de l'énergie cinétique : $\\dfrac12 m v^2=mgL$. (b) Au point bas, la résultante est centripète : $T-mg=\\dfrac{m v^2}{L}$.",
   sol:"(a) La bille descend d'une hauteur $h=L$. $\\dfrac12 m v^2=mgL\\Rightarrow v=\\sqrt{2gL}=\\sqrt{2\\times9{,}8\\times1}\\approx4{,}43\\ \\text{m/s}$. (b) Au point le plus bas, $T-mg=\\dfrac{m v^2}{L}$ avec $v^2=2gL$, donc $T=mg+\\dfrac{m\\,(2gL)}{L}=mg+2mg=3mg=3\\times0{,}2\\times9{,}8=5{,}88\\ \\text{N}$." }
],

"Physique — Énergie potentielle de pesanteur et énergie mécanique": [
 { niv:"Application",
   en:"Un objet de masse $m=3\\ \\text{kg}$ se trouve à l'altitude $z=4\\ \\text{m}$ au-dessus du sol pris comme référence ($g=9{,}8\\ \\text{N/kg}$). Calculer son énergie potentielle de pesanteur.",
   hint:"$E_{pp}=mgz$ (référence : $E_{pp}=0$ au sol).",
   sol:"$E_{pp}=mgz=3\\times9{,}8\\times4=117{,}6\\ \\text{J}$." },
 { niv:"Application",
   en:"À un instant donné, un objet possède une énergie cinétique $E_c=10\\ \\text{J}$ et une énergie potentielle $E_{pp}=6\\ \\text{J}$. Calculer son énergie mécanique.",
   hint:"$E_m=E_c+E_{pp}$.",
   sol:"$E_m=E_c+E_{pp}=10+6=16\\ \\text{J}$." },
 { niv:"Moyen",
   en:"Un enfant descend un toboggan sans frottement, en partant sans vitesse d'une hauteur $h=2{,}5\\ \\text{m}$. ($g=9{,}8\\ \\text{N/kg}$.) Déterminer sa vitesse en bas par conservation de l'énergie mécanique.",
   hint:"Sans frottement $E_m$ se conserve : $mgh=\\dfrac12 m v^2$.",
   sol:"$mgh=\\dfrac12 m v^2\\Rightarrow v=\\sqrt{2gh}=\\sqrt{2\\times9{,}8\\times2{,}5}=\\sqrt{49}=7\\ \\text{m/s}$." },
 { niv:"Moyen",
   en:"Une bille est lancée verticalement vers le haut avec une vitesse $v_0=12\\ \\text{m/s}$ (frottements négligés, $g=9{,}8\\ \\text{N/kg}$). Déterminer la hauteur maximale atteinte par conservation de l'énergie mécanique.",
   hint:"Au sommet $v=0$, donc $\\dfrac12 m v_0^2=mg\\,h_{\\max}$.",
   sol:"$\\dfrac12 m v_0^2=mg\\,h_{\\max}\\Rightarrow h_{\\max}=\\dfrac{v_0^2}{2g}=\\dfrac{12^2}{2\\times9{,}8}=\\dfrac{144}{19{,}6}\\approx7{,}35\\ \\text{m}$." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> Un skieur de masse $m=70\\ \\text{kg}$ part du repos en haut d'une piste de hauteur $h=40\\ \\text{m}$. En bas, sa vitesse mesurée est $v=25\\ \\text{m/s}$. ($g=9{,}8\\ \\text{N/kg}$, référence en bas de piste.) (a) Calculer l'énergie mécanique en haut et en bas. (b) En déduire l'énergie dissipée par frottement, puis la force de frottement moyenne si la piste a une longueur $L=120\\ \\text{m}$.",
   hint:"Ici $E_m$ n'est pas conservée : $\\Delta E_m=W(\\vec f)=-f\\,L$.",
   sol:"(a) En haut ($v=0$) : $E_m^{\\text{haut}}=mgh=70\\times9{,}8\\times40=27\\,440\\ \\text{J}$. En bas ($z=0$) : $E_m^{\\text{bas}}=\\dfrac12 m v^2=\\dfrac12\\times70\\times25^2=21\\,875\\ \\text{J}$. (b) $\\Delta E_m=21\\,875-27\\,440=-5565\\ \\text{J}$ : l'énergie dissipée est $5565\\ \\text{J}$. Comme $|W(\\vec f)|=f\\,L$, on a $f=\\dfrac{5565}{120}\\approx46{,}4\\ \\text{N}$." }
],

"Physique — Travail et énergie interne": [
 { niv:"Application",
   en:"On chauffe une masse $m=0{,}5\\ \\text{kg}$ d'eau de $20\\,^\\circ\\text{C}$ à $60\\,^\\circ\\text{C}$. La capacité thermique massique de l'eau est $c=4185\\ \\text{J·kg}^{-1}\\text{·K}^{-1}$. Calculer la chaleur reçue par l'eau.",
   hint:"$Q=mc\\,\\Delta T$, avec $\\Delta T$ en $^\\circ\\text{C}$ ou en $\\text{K}$ (même valeur pour une variation).",
   sol:"$Q=mc\\,\\Delta T=0{,}5\\times4185\\times(60-20)=0{,}5\\times4185\\times40=83\\,700\\ \\text{J}\\approx83{,}7\\ \\text{kJ}$." },
 { niv:"Application",
   en:"Un bloc de fer de masse $m=2\\ \\text{kg}$ ($c=450\\ \\text{J·kg}^{-1}\\text{·K}^{-1}$) reçoit une chaleur $Q=9000\\ \\text{J}$. Déterminer l'élévation de sa température.",
   hint:"$\\Delta T=\\dfrac{Q}{mc}$.",
   sol:"$\\Delta T=\\dfrac{Q}{mc}=\\dfrac{9000}{2\\times450}=10\\,^\\circ\\text{C}$." },
 { niv:"Moyen",
   en:"On frotte un bloc de cuivre de masse $m=0{,}3\\ \\text{kg}$ ($c=385\\ \\text{J·kg}^{-1}\\text{·K}^{-1}$) : un travail $W=1200\\ \\text{J}$ lui est fourni et se convertit entièrement en énergie interne, sans transfert thermique ($Q=0$). Déterminer l'élévation de température.",
   hint:"Premier principe : $\\Delta U=W+Q$. Ici $Q=0$, donc $\\Delta U=W=mc\\,\\Delta T$.",
   sol:"$\\Delta U=W+Q=1200+0=1200\\ \\text{J}$. Or $\\Delta U=mc\\,\\Delta T$, donc $\\Delta T=\\dfrac{\\Delta U}{mc}=\\dfrac{1200}{0{,}3\\times385}\\approx10{,}4\\,^\\circ\\text{C}$." },
 { niv:"Moyen",
   en:"Dans un calorimètre (dont on néglige la capacité), on mélange $m_1=200\\ \\text{g}$ d'eau à $70\\,^\\circ\\text{C}$ avec $m_2=300\\ \\text{g}$ d'eau à $20\\,^\\circ\\text{C}$. Déterminer la température d'équilibre.",
   hint:"Chaleur cédée par l'eau chaude = chaleur reçue par l'eau froide : $m_1 c(\\theta_1-\\theta_e)=m_2 c(\\theta_e-\\theta_2)$.",
   sol:"$m_1(\\theta_1-\\theta_e)=m_2(\\theta_e-\\theta_2)\\Rightarrow 200(70-\\theta_e)=300(\\theta_e-20)$, soit $14000-200\\theta_e=300\\theta_e-6000$, d'où $500\\theta_e=20000$ et $\\theta_e=40\\,^\\circ\\text{C}$." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> Une balle de plomb de masse $m=50\\ \\text{g}$ tombe sans vitesse initiale d'une hauteur $h=20\\ \\text{m}$ et s'immobilise au sol. On admet que toute son énergie cinétique acquise se convertit en énergie interne de la balle (aucun transfert vers le sol). $c_{\\text{plomb}}=128\\ \\text{J·kg}^{-1}\\text{·K}^{-1}$, $g=9{,}8\\ \\text{N/kg}$. Calculer l'élévation de température de la balle.",
   hint:"L'énergie cinétique à l'impact vaut $mgh$ ; elle devient $\\Delta U=mc\\,\\Delta T$. La masse se simplifie.",
   sol:"À l'impact, l'énergie cinétique vaut $E_c=mgh$. Elle se convertit en énergie interne : $mgh=mc\\,\\Delta T$, donc $\\Delta T=\\dfrac{gh}{c}=\\dfrac{9{,}8\\times20}{128}=\\dfrac{196}{128}\\approx1{,}53\\,^\\circ\\text{C}$ (indépendant de la masse)." }
],

"Physique — Énergie thermique et transferts thermiques": [
 { niv:"Application",
   en:"Citer les trois modes de transfert thermique et donner un exemple concret de chacun.",
   hint:"Pense à un solide, à un fluide en mouvement, et à un transfert possible même dans le vide.",
   sol:"<b>Conduction</b> : de proche en proche dans un solide (ex. une barre métallique chauffée à une extrémité). <b>Convection</b> : par déplacement de matière dans un fluide (ex. l'eau qui bout, l'air d'un radiateur). <b>Rayonnement</b> : par ondes électromagnétiques, même dans le vide (ex. la chaleur du Soleil)." },
 { niv:"Application",
   en:"Quelle chaleur faut-il fournir pour faire fondre $m=100\\ \\text{g}$ de glace à $0\\,^\\circ\\text{C}$ ? Chaleur latente de fusion de la glace : $L_f=334\\ \\text{kJ·kg}^{-1}$.",
   hint:"Lors d'un changement d'état, la température reste constante : $Q=m\\,L_f$.",
   sol:"$Q=m\\,L_f=0{,}100\\times334\\,000=33\\,400\\ \\text{J}=33{,}4\\ \\text{kJ}$." },
 { niv:"Moyen",
   en:"On veut chauffer $m=200\\ \\text{g}$ de glace de $-10\\,^\\circ\\text{C}$ jusqu'à l'obtention d'eau liquide à $0\\,^\\circ\\text{C}$. Données : $c_{\\text{glace}}=2100\\ \\text{J·kg}^{-1}\\text{·K}^{-1}$, $L_f=334\\,000\\ \\text{J·kg}^{-1}$. Calculer la chaleur totale nécessaire.",
   hint:"Deux étapes : réchauffer la glace ($Q_1=mc\\,\\Delta T$) puis la fondre ($Q_2=mL_f$).",
   sol:"$Q_1=mc_{\\text{glace}}\\Delta T=0{,}2\\times2100\\times10=4200\\ \\text{J}$. $Q_2=mL_f=0{,}2\\times334\\,000=66\\,800\\ \\text{J}$. Total : $Q=Q_1+Q_2=71\\,000\\ \\text{J}=71\\ \\text{kJ}$." },
 { niv:"Moyen",
   en:"Quelle chaleur faut-il pour amener $m=500\\ \\text{g}$ d'eau de $25\\,^\\circ\\text{C}$ à $100\\,^\\circ\\text{C}$ puis la vaporiser entièrement ? Données : $c_{\\text{eau}}=4185\\ \\text{J·kg}^{-1}\\text{·K}^{-1}$, $L_v=2{,}26\\times10^{6}\\ \\text{J·kg}^{-1}$.",
   hint:"Réchauffement $Q_1=mc\\,\\Delta T$ puis vaporisation $Q_2=mL_v$.",
   sol:"$Q_1=mc\\,\\Delta T=0{,}5\\times4185\\times75\\approx156\\,900\\ \\text{J}\\approx157\\ \\text{kJ}$. $Q_2=mL_v=0{,}5\\times2{,}26\\times10^{6}=1{,}13\\times10^{6}\\ \\text{J}=1130\\ \\text{kJ}$. Total $\\approx1287\\ \\text{kJ}$." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> On plonge un glaçon de masse $m_g=50\\ \\text{g}$ à $0\\,^\\circ\\text{C}$ dans $m_e=250\\ \\text{g}$ d'eau à $30\\,^\\circ\\text{C}$, dans un récipient calorifugé. Données : $c_{\\text{eau}}=4185\\ \\text{J·kg}^{-1}\\text{·K}^{-1}$, $L_f=334\\,000\\ \\text{J·kg}^{-1}$. (a) Montrer que toute la glace fond. (b) Calculer la température finale du mélange.",
   hint:"(a) Compare l'énergie libérée par l'eau chaude en refroidissant jusqu'à $0\\,^\\circ\\text{C}$ à l'énergie de fusion. (b) Bilan : $m_e c(30-\\theta_e)=m_g L_f+m_g c\\,\\theta_e$.",
   sol:"(a) En refroidissant de $30\\,^\\circ\\text{C}$ à $0\\,^\\circ\\text{C}$, l'eau chaude libère $Q=m_e c\\times30=0{,}25\\times4185\\times30\\approx31\\,388\\ \\text{J}$. Faire fondre la glace demande $m_g L_f=0{,}05\\times334\\,000=16\\,700\\ \\text{J}$. Comme $31\\,388>16\\,700$, <b>toute la glace fond</b>. (b) Bilan thermique : $m_e c(30-\\theta_e)=m_g L_f+m_g c\\,\\theta_e$, soit $1046{,}25\\,(30-\\theta_e)=16\\,700+209{,}25\\,\\theta_e$. On obtient $31\\,388-1046{,}25\\,\\theta_e=16\\,700+209{,}25\\,\\theta_e$, d'où $1255{,}5\\,\\theta_e=14\\,688$ et $\\theta_e\\approx11{,}7\\,^\\circ\\text{C}$." }
],

"Chimie — L'importance de la mesure en chimie": [
 { niv:"Application",
   en:"Un échantillon de masse $m=200\\ \\text{g}$ occupe un volume $V=250\\ \\text{mL}$. Calculer sa masse volumique $\\rho$ (en $\\text{g/mL}$ puis en $\\text{kg/m}^3$).",
   hint:"$\\rho=\\dfrac{m}{V}$.",
   sol:"$\\rho=\\dfrac{m}{V}=\\dfrac{200}{250}=0{,}8\\ \\text{g/mL}=800\\ \\text{kg/m}^3$." },
 { niv:"Application",
   en:"Un liquide a une masse volumique $\\rho=1250\\ \\text{kg/m}^3$. Calculer sa densité $d$ (on prend $\\rho_{\\text{eau}}=1000\\ \\text{kg/m}^3$).",
   hint:"$d=\\dfrac{\\rho}{\\rho_{\\text{eau}}}$ (grandeur sans unité).",
   sol:"$d=\\dfrac{\\rho}{\\rho_{\\text{eau}}}=\\dfrac{1250}{1000}=1{,}25$." },
 { niv:"Moyen",
   en:"On souhaite prélever un volume $V=500\\ \\text{mL}$ d'éthanol de masse volumique $\\rho=0{,}79\\ \\text{g/mL}$. Quelle masse d'éthanol faut-il peser ?",
   hint:"$m=\\rho\\,V$.",
   sol:"$m=\\rho\\,V=0{,}79\\times500=395\\ \\text{g}$." },
 { niv:"Moyen",
   en:"On mesure les côtés d'un rectangle : $L=12{,}30\\ \\text{cm}$ et $\\ell=4{,}5\\ \\text{cm}$. Calculer l'aire et l'exprimer avec le nombre correct de chiffres significatifs.",
   hint:"Le résultat d'un produit garde le nombre de chiffres significatifs de la donnée la moins précise.",
   sol:"$A=L\\times\\ell=12{,}30\\times4{,}5=55{,}35\\ \\text{cm}^2$. Comme $\\ell=4{,}5$ n'a que $2$ chiffres significatifs, on écrit $A\\approx55\\ \\text{cm}^2$." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> Un lingot d'alliage cuivre-aluminium de masse $m=1\\ \\text{kg}$ a un volume $V=200\\ \\text{cm}^3$. Données : $\\rho_{\\text{Cu}}=8{,}96\\ \\text{g/cm}^3$, $\\rho_{\\text{Al}}=2{,}70\\ \\text{g/cm}^3$ (volumes supposés additifs). Déterminer les masses de cuivre et d'aluminium.",
   hint:"Pose le système $\\begin{cases}V_{\\text{Cu}}+V_{\\text{Al}}=200\\\\ 8{,}96\\,V_{\\text{Cu}}+2{,}70\\,V_{\\text{Al}}=1000\\end{cases}$ (volumes en $\\text{cm}^3$, masses en $\\text{g}$).",
   sol:"En remplaçant $V_{\\text{Al}}=200-V_{\\text{Cu}}$ : $8{,}96\\,V_{\\text{Cu}}+2{,}70\\,(200-V_{\\text{Cu}})=1000\\Rightarrow 6{,}26\\,V_{\\text{Cu}}=460\\Rightarrow V_{\\text{Cu}}\\approx73{,}5\\ \\text{cm}^3$ et $V_{\\text{Al}}\\approx126{,}5\\ \\text{cm}^3$. D'où $m_{\\text{Cu}}=8{,}96\\times73{,}5\\approx659\\ \\text{g}$ et $m_{\\text{Al}}=2{,}70\\times126{,}5\\approx341\\ \\text{g}$ (somme $\\approx1000\\ \\text{g}$)." }
],

"Chimie — Grandeurs liées à la quantité de matière (mole, concentration)": [
 { niv:"Application",
   en:"Calculer la quantité de matière contenue dans $m=18\\ \\text{g}$ d'eau. Donnée : $M(\\text{H}_2\\text{O})=18\\ \\text{g/mol}$.",
   hint:"$n=\\dfrac{m}{M}$.",
   sol:"$n=\\dfrac{m}{M}=\\dfrac{18}{18}=1\\ \\text{mol}$." },
 { niv:"Application",
   en:"Calculer le nombre d'entités contenues dans $n=0{,}5\\ \\text{mol}$. Donnée : $N_A=6{,}022\\times10^{23}\\ \\text{mol}^{-1}$.",
   hint:"$N=n\\,N_A$.",
   sol:"$N=n\\,N_A=0{,}5\\times6{,}022\\times10^{23}=3{,}011\\times10^{23}$ entités." },
 { niv:"Moyen",
   en:"On dissout $m=20\\ \\text{g}$ de chlorure de sodium $\\text{NaCl}$ ($M=58{,}5\\ \\text{g/mol}$) dans de l'eau pour obtenir $V=500\\ \\text{mL}$ de solution. Calculer la concentration molaire $C$.",
   hint:"$n=\\dfrac{m}{M}$ puis $C=\\dfrac{n}{V}$ (avec $V$ en litres).",
   sol:"$n=\\dfrac{20}{58{,}5}\\approx0{,}342\\ \\text{mol}$. $C=\\dfrac{n}{V}=\\dfrac{0{,}342}{0{,}500}\\approx0{,}68\\ \\text{mol/L}$." },
 { niv:"Moyen",
   en:"On veut préparer $V_2=250\\ \\text{mL}$ d'une solution de concentration $C_2=0{,}1\\ \\text{mol/L}$ à partir d'une solution mère de concentration $C_1=0{,}5\\ \\text{mol/L}$. Quel volume $V_1$ de solution mère faut-il prélever ?",
   hint:"Conservation de la quantité de matière lors d'une dilution : $C_1 V_1=C_2 V_2$.",
   sol:"$C_1 V_1=C_2 V_2\\Rightarrow V_1=\\dfrac{C_2 V_2}{C_1}=\\dfrac{0{,}1\\times250}{0{,}5}=50\\ \\text{mL}$." },
 { niv:"Défi",
   en:"🏅 <b>Type olympiades.</b> On dispose d'un volume $V=2{,}24\\ \\text{L}$ de dioxygène $\\text{O}_2$ mesuré dans les CNTP ($V_m=22{,}4\\ \\text{L/mol}$). (a) Calculer la quantité de matière et le nombre de molécules. (b) En déduire la masse de ce gaz ($M(\\text{O}_2)=32\\ \\text{g/mol}$). (c) Ce dioxygène réagit totalement selon $\\text{C}+\\text{O}_2\\rightarrow\\text{CO}_2$. Calculer la masse de carbone consommée ($M(\\text{C})=12$) et la masse de $\\text{CO}_2$ formée ($M(\\text{CO}_2)=44$).",
   hint:"$n=\\dfrac{V}{V_m}$ ; $N=n\\,N_A$ ; la stœchiométrie est $1:1:1$.",
   sol:"(a) $n=\\dfrac{V}{V_m}=\\dfrac{2{,}24}{22{,}4}=0{,}1\\ \\text{mol}$, soit $N=0{,}1\\times6{,}022\\times10^{23}=6{,}022\\times10^{22}$ molécules. (b) $m(\\text{O}_2)=nM=0{,}1\\times32=3{,}2\\ \\text{g}$. (c) D'après $\\text{C}+\\text{O}_2\\rightarrow\\text{CO}_2$ : $n(\\text{C})=n(\\text{O}_2)=0{,}1\\ \\text{mol}\\Rightarrow m(\\text{C})=0{,}1\\times12=1{,}2\\ \\text{g}$ ; $n(\\text{CO}_2)=0{,}1\\ \\text{mol}\\Rightarrow m(\\text{CO}_2)=0{,}1\\times44=4{,}4\\ \\text{g}$." }
]

});
