/* ===== Séries d'exercices curatées — Mathématiques 1ère Bac Sciences Maths (programme marocain) =====
   Clés = titres EXACTS des chapitres (window.EDU_SUBJECTS.maths.chapters).
   Chaque exercice : { niv:'Application'|'Moyen'|'Défi', en:énoncé, hint:indice, sol:correction } (HTML + LaTeX $…$). */
window.PB_EXOS = window.PB_EXOS || {};
Object.assign(window.PB_EXOS, {

"Notions de logique": [
 { niv:"Application",
   en:"Écrire la négation de chacune des propositions : (a) $P:\\ \\forall x\\in\\mathbb{R},\\ x^2+1>0$ ; (b) $Q:\\ \\exists n\\in\\mathbb{N},\\ 2n=n^2$. Préciser si $P$ est vraie ou fausse.",
   hint:"La négation échange $\\forall$ et $\\exists$, et nie la propriété : la négation de $>$ est $\\le$, celle de $=$ est $\\ne$.",
   sol:"(a) $\\overline{P}:\\ \\exists x\\in\\mathbb{R},\\ x^2+1\\le 0$. Comme $x^2\\ge 0$, on a $x^2+1\\ge 1>0$ pour tout réel $x$ : donc $P$ est <b>vraie</b> (et $\\overline P$ fausse).<br>(b) $\\overline{Q}:\\ \\forall n\\in\\mathbb{N},\\ 2n\\ne n^2$. ($Q$ est vraie : pour $n=0$ et $n=2$ on a $2n=n^2$.)" },
 { niv:"Application",
   en:"Montrer, à l'aide d'une table de vérité, que $(P\\Rightarrow Q)$ est équivalente à $(\\overline{P}\\ \\lor\\ Q)$.",
   hint:"Il y a 4 cas selon que $P$ et $Q$ sont vraies (V) ou fausses (F). Compare les deux dernières colonnes.",
   sol:"<table class='exo-tab'><tr><th>$P$</th><th>$Q$</th><th>$P\\Rightarrow Q$</th><th>$\\overline P\\lor Q$</th></tr><tr><td>V</td><td>V</td><td>V</td><td>V</td></tr><tr><td>V</td><td>F</td><td>F</td><td>F</td></tr><tr><td>F</td><td>V</td><td>V</td><td>V</td></tr><tr><td>F</td><td>F</td><td>V</td><td>V</td></tr></table>Les colonnes $(P\\Rightarrow Q)$ et $(\\overline P\\lor Q)$ sont identiques : les deux propositions sont donc <b>équivalentes</b>." },
 { niv:"Moyen",
   en:"Soit $n\\in\\mathbb{Z}$. Montrer, en raisonnant par contraposée, que : si $n^2$ est pair alors $n$ est pair.",
   hint:"La contraposée de « si $n^2$ pair alors $n$ pair » est « si $n$ impair alors $n^2$ impair ». Écris $n=2k+1$.",
   sol:"Contraposée : « si $n$ est impair, alors $n^2$ est impair ». Supposons $n$ impair : $n=2k+1$ avec $k\\in\\mathbb{Z}$. Alors $n^2=(2k+1)^2=4k^2+4k+1=2(2k^2+2k)+1$, qui est impair. La contraposée est vraie, donc l'implication de départ l'est aussi : si $n^2$ est pair, alors $n$ est pair." },
 { niv:"Moyen",
   en:"Démontrer par récurrence que : $\\forall n\\in\\mathbb{N}^*,\\quad 1+2+3+\\cdots+n=\\dfrac{n(n+1)}{2}.$",
   hint:"Initialisation à $n=1$. Pour l'hérédité, ajoute $(n+1)$ aux deux membres de l'hypothèse de récurrence.",
   sol:"<b>Initialisation</b> ($n=1$) : à gauche $1$ ; à droite $\\frac{1\\cdot 2}{2}=1$. Vrai.<br><b>Hérédité</b> : supposons $1+\\cdots+n=\\frac{n(n+1)}{2}$. Alors $1+\\cdots+n+(n+1)=\\frac{n(n+1)}{2}+(n+1)=(n+1)\\left(\\frac{n}{2}+1\\right)=\\frac{(n+1)(n+2)}{2}$, qui est la formule au rang $n+1$.<br>Par récurrence, la propriété est vraie pour tout $n\\in\\mathbb{N}^*$." },
 { niv:"Défi",
   en:"Montrer, par un raisonnement par l'absurde, que $\\sqrt{2}$ est irrationnel.",
   hint:"Suppose $\\sqrt2=\\frac{p}{q}$ avec la fraction $\\frac pq$ irréductible, puis montre que $p$ et $q$ sont tous deux pairs.",
   sol:"Supposons par l'absurde $\\sqrt2=\\frac pq$ avec $p,q\\in\\mathbb{N}^*$ et $\\frac pq$ <b>irréductible</b>. Alors $2=\\frac{p^2}{q^2}$, donc $p^2=2q^2$ : $p^2$ est pair, donc $p$ est pair, $p=2k$. D'où $4k^2=2q^2$, soit $q^2=2k^2$ : $q^2$ est pair, donc $q$ est pair. Ainsi $p$ et $q$ sont pairs : $\\frac pq$ n'est pas irréductible — <b>contradiction</b>. Donc $\\sqrt2\\notin\\mathbb{Q}$." }
],

"Ensembles et applications": [
 { niv:"Application",
   en:"On donne $A=\\{1,2,3,4,6\\}$ et $B=\\{2,4,5,6\\}$, parties de $E=\\{1,2,3,4,5,6\\}$. Déterminer $A\\cup B$, $A\\cap B$, $A\\setminus B$ et $\\overline{A}$ (complémentaire dans $E$).",
   hint:"$A\\setminus B$ = éléments de $A$ absents de $B$ ; $\\overline A=E\\setminus A$.",
   sol:"$A\\cup B=\\{1,2,3,4,5,6\\}$ ; $A\\cap B=\\{2,4,6\\}$ ; $A\\setminus B=\\{1,3\\}$ ; $\\overline A=\\{5\\}$." },
 { niv:"Application",
   en:"Dans une classe de $30$ élèves, $18$ étudient l'anglais, $15$ l'espagnol et $7$ les deux. Combien étudient au moins une de ces langues ? Combien n'en étudient aucune ?",
   hint:"$\\operatorname{card}(A\\cup B)=\\operatorname{card}(A)+\\operatorname{card}(B)-\\operatorname{card}(A\\cap B)$.",
   sol:"$\\operatorname{card}(A\\cup B)=18+15-7=26$ élèves étudient au moins une langue. Aucune : $30-26=4$ élèves." },
 { niv:"Moyen",
   en:"Soient $A,B,C$ trois parties d'un ensemble $E$. Démontrer que $A\\cap(B\\cup C)=(A\\cap B)\\cup(A\\cap C)$.",
   hint:"Prends $x$ quelconque et traduis « $x\\in\\ldots$ » avec $\\land$ et $\\lor$, puis utilise la distributivité logique.",
   sol:"Soit $x\\in E$. $x\\in A\\cap(B\\cup C)\\iff (x\\in A)\\land\\big((x\\in B)\\lor(x\\in C)\\big)$. Par distributivité de $\\land$ sur $\\lor$ : $\\iff\\big((x\\in A)\\land(x\\in B)\\big)\\lor\\big((x\\in A)\\land(x\\in C)\\big)\\iff x\\in (A\\cap B)\\cup(A\\cap C)$. Les deux ensembles ont les mêmes éléments, donc ils sont égaux." },
 { niv:"Moyen",
   en:"Soit $f:\\mathbb{R}\\to\\mathbb{R}$ définie par $f(x)=2x-3$. Montrer que $f$ est bijective et déterminer $f^{-1}$.",
   hint:"Résous l'équation $f(x)=y$ d'inconnue $x$ : si elle a une solution unique pour tout $y$, $f$ est bijective.",
   sol:"Soit $y\\in\\mathbb{R}$. $f(x)=y\\iff 2x-3=y\\iff x=\\frac{y+3}{2}$. Pour tout $y$ il existe un <b>unique</b> $x$ : $f$ est bijective. Sa réciproque est $f^{-1}(x)=\\frac{x+3}{2}$." },
 { niv:"Défi",
   en:"Soit $f:\\mathbb{R}\\to\\mathbb{R},\\ f(x)=x^2$. (a) $f$ est-elle injective ? surjective ? (b) Mêmes questions pour $g:[0,+\\infty[\\to[0,+\\infty[,\\ g(x)=x^2$.",
   hint:"Pour l'injectivité, cherche deux antécédents distincts ; pour la surjectivité, cherche si tout élément de l'arrivée a un antécédent.",
   sol:"(a) $f(-1)=f(1)=1$ : deux antécédents distincts $\\Rightarrow f$ <b>non injective</b>. Et $-1$ n'a pas d'antécédent ($x^2=-1$ impossible dans $\\mathbb{R}$) $\\Rightarrow f$ <b>non surjective</b>.<br>(b) Sur $[0,+\\infty[$ : si $a,b\\ge0$ et $a^2=b^2$ alors $a=b$ : $g$ est <b>injective</b>. Pour tout $y\\ge0$, $x=\\sqrt y\\ge0$ donne $g(x)=y$ : $g$ est <b>surjective</b>. Donc $g$ est <b>bijective</b>, de réciproque $g^{-1}(x)=\\sqrt x$." }
],

"Généralités sur les fonctions numériques": [
 { niv:"Application",
   en:"Déterminer l'ensemble de définition de $f(x)=\\dfrac{\\sqrt{x-1}}{x-3}$.",
   hint:"Il faut à la fois $x-1\\ge 0$ (racine) et $x-3\\ne 0$ (dénominateur).",
   sol:"Conditions : $x-1\\ge0\\iff x\\ge1$ et $x-3\\ne0\\iff x\\ne3$. Donc $D_f=[1,3[\\,\\cup\\,]3,+\\infty[$." },
 { niv:"Application",
   en:"Étudier la parité de $f(x)=x^3-x$ et de $g(x)=x^2+\\cos x$ sur $\\mathbb{R}$.",
   hint:"Calcule $f(-x)$ et $g(-x)$, puis compare à $f(x)$ et $-f(x)$.",
   sol:"$\\mathbb{R}$ est symétrique par rapport à $0$. $f(-x)=-x^3+x=-(x^3-x)=-f(x)$ : $f$ est <b>impaire</b>. $g(-x)=x^2+\\cos(-x)=x^2+\\cos x=g(x)$ : $g$ est <b>paire</b>." },
 { niv:"Moyen",
   en:"Soit $f(x)=\\dfrac{2x+1}{x-1}$ sur $]1,+\\infty[$. Étudier son sens de variation.",
   hint:"Écris $f$ sous la forme $2+\\dfrac{3}{x-1}$.",
   sol:"$f(x)=\\frac{2(x-1)+3}{x-1}=2+\\frac{3}{x-1}$. Sur $]1,+\\infty[$, $x\\mapsto x-1$ est croissante et strictement positive, donc $x\\mapsto\\frac{3}{x-1}$ est <b>décroissante</b>, donc $f$ est <b>strictement décroissante</b>. (Vérif : $f(2)=5$, $f(4)=3$.)" },
 { niv:"Moyen",
   en:"Soit $f(x)=x^2-4x+5$. Écrire $f$ sous forme canonique, puis déterminer son minimum et le point où il est atteint.",
   hint:"$x^2-4x=(x-2)^2-4$.",
   sol:"$f(x)=(x-2)^2-4+5=(x-2)^2+1$. Comme $(x-2)^2\\ge0$, on a $f(x)\\ge1$ avec égalité ssi $x=2$. Le <b>minimum</b> de $f$ vaut $\\boxed{1}$, atteint en $x=2$." },
 { niv:"Défi",
   en:"Montrer que $f(x)=\\dfrac{x}{1+x^2}$ vérifie $-\\dfrac12\\le f(x)\\le \\dfrac12$ pour tout $x\\in\\mathbb{R}$ (donc $f$ est bornée).",
   hint:"Étudie le signe de $\\dfrac12-f(x)$ et de $f(x)+\\dfrac12$ ; pense à $(1\\mp x)^2\\ge0$.",
   sol:"Pour tout $x$, $1+x^2>0$. On a $\\frac12-f(x)=\\frac{(1+x^2)-2x}{2(1+x^2)}=\\frac{(1-x)^2}{2(1+x^2)}\\ge0$, donc $f(x)\\le\\frac12$. De même $f(x)+\\frac12=\\frac{(1+x)^2}{2(1+x^2)}\\ge0$, donc $f(x)\\ge-\\frac12$. Ainsi $-\\frac12\\le f(x)\\le\\frac12$ ; les bornes sont atteintes en $x=1$ et $x=-1$." }
],

"Le barycentre dans le plan": [
 { niv:"Application",
   en:"Soient $A$ et $B$ deux points et $G$ le barycentre de $(A,2)$ et $(B,3)$. Exprimer $\\vec{AG}$ en fonction de $\\vec{AB}$.",
   hint:"Par définition $2\\vec{GA}+3\\vec{GB}=\\vec0$. Écris $\\vec{GB}=\\vec{GA}+\\vec{AB}$.",
   sol:"$2\\vec{GA}+3\\vec{GB}=\\vec0$ et $\\vec{GB}=\\vec{GA}+\\vec{AB}$, donc $5\\vec{GA}+3\\vec{AB}=\\vec0\\Rightarrow\\vec{GA}=-\\frac35\\vec{AB}$, d'où $\\vec{AG}=\\frac35\\vec{AB}$. $G$ est aux $\\frac35$ de $[AB]$ à partir de $A$." },
 { niv:"Application",
   en:"Soit $ABC$ un triangle et $G$ l'isobarycentre de $A,B,C$. Montrer que $\\vec{AG}=\\dfrac13(\\vec{AB}+\\vec{AC})$.",
   hint:"$\\vec{GA}+\\vec{GB}+\\vec{GC}=\\vec0$, puis $\\vec{GB}=\\vec{GA}+\\vec{AB}$ et $\\vec{GC}=\\vec{GA}+\\vec{AC}$.",
   sol:"$\\vec{GA}+\\vec{GB}+\\vec{GC}=\\vec0$. En remplaçant : $3\\vec{GA}+\\vec{AB}+\\vec{AC}=\\vec0\\Rightarrow\\vec{AG}=\\frac13(\\vec{AB}+\\vec{AC})$. $G$ est le <b>centre de gravité</b> du triangle." },
 { niv:"Moyen",
   en:"Réduire, pour tout point $M$ du plan, le vecteur $\\vec{u}(M)=2\\vec{MA}+3\\vec{MB}$ en faisant apparaître le barycentre $G$ de $(A,2),(B,3)$.",
   hint:"Introduis $G$ : $\\vec{MA}=\\vec{MG}+\\vec{GA}$, etc., puis utilise $2\\vec{GA}+3\\vec{GB}=\\vec0$.",
   sol:"$2\\vec{MA}+3\\vec{MB}=2(\\vec{MG}+\\vec{GA})+3(\\vec{MG}+\\vec{GB})=5\\vec{MG}+(2\\vec{GA}+3\\vec{GB})=5\\vec{MG}$. Donc $\\vec{u}(M)=5\\vec{MG}$ pour tout $M$." },
 { niv:"Moyen",
   en:"Avec $G$ le barycentre de $(A,2),(B,3)$, déterminer l'ensemble des points $M$ tels que $\\lVert 2\\vec{MA}+3\\vec{MB}\\rVert=10$.",
   hint:"Utilise la réduction de l'exercice précédent : $2\\vec{MA}+3\\vec{MB}=5\\vec{MG}$.",
   sol:"$\\lVert5\\vec{MG}\\rVert=10\\iff 5\\,MG=10\\iff MG=2$. L'ensemble cherché est le <b>cercle de centre $G$ et de rayon $2$</b>." },
 { niv:"Défi",
   en:"Soit $ABC$ un triangle, $I$ le milieu de $[BC]$ et $G$ l'isobarycentre de $A,B,C$. Montrer que $A$, $G$, $I$ sont alignés et préciser la position de $G$ sur $[AI]$.",
   hint:"$I$ est le barycentre de $(B,1),(C,1)$ ; utilise l'associativité du barycentre pour regrouper $B$ et $C$.",
   sol:"$I$ est le barycentre de $(B,1),(C,1)$. Par <b>associativité</b>, $G$ (barycentre de $(A,1),(B,1),(C,1)$) est le barycentre de $(A,1)$ et $(I,2)$. Donc $\\vec{AG}=\\frac{2}{1+2}\\vec{AI}=\\frac23\\vec{AI}$ : $A,G,I$ sont <b>alignés</b> et $G$ est aux deux tiers de $[AI]$ à partir de $A$." }
],

"Produit scalaire et applications": [
 { niv:"Application",
   en:"Dans un repère orthonormé, on donne $\\vec u(1,2)$ et $\\vec v(3,-1)$. Calculer $\\vec u\\cdot\\vec v$ et dire si $\\vec u$ et $\\vec v$ sont orthogonaux.",
   hint:"En repère orthonormé, $\\vec u\\cdot\\vec v=x_ux_v+y_uy_v$ ; orthogonaux $\\iff$ produit scalaire nul.",
   sol:"$\\vec u\\cdot\\vec v=1\\times3+2\\times(-1)=3-2=1$. Comme $\\vec u\\cdot\\vec v=1\\ne0$, les vecteurs ne sont <b>pas orthogonaux</b>." },
 { niv:"Application",
   en:"Soit $ABC$ un triangle tel que $AB=5$, $AC=3$ et $\\widehat{A}=60^\\circ$. Calculer $\\vec{AB}\\cdot\\vec{AC}$.",
   hint:"$\\vec{AB}\\cdot\\vec{AC}=AB\\times AC\\times\\cos\\widehat{A}$.",
   sol:"$\\vec{AB}\\cdot\\vec{AC}=AB\\times AC\\times\\cos 60^\\circ=5\\times3\\times\\frac12=\\frac{15}{2}=7{,}5$." },
 { niv:"Moyen",
   en:"Dans un triangle $ABC$, on a $AB=7$, $AC=5$ et $\\widehat{A}=60^\\circ$. Calculer $BC$ (relation d'Al-Kashi).",
   hint:"$BC^2=AB^2+AC^2-2\\,AB\\cdot AC\\cos\\widehat{A}$.",
   sol:"$BC^2=7^2+5^2-2\\times7\\times5\\times\\cos60^\\circ=49+25-70\\times\\frac12=74-35=39$. Donc $BC=\\sqrt{39}\\approx6{,}24$." },
 { niv:"Moyen",
   en:"Soient $A$ et $B$ deux points fixes. Déterminer l'ensemble des points $M$ du plan tels que $\\vec{MA}\\cdot\\vec{MB}=0$.",
   hint:"$\\vec{MA}\\cdot\\vec{MB}=0$ signifie que les vecteurs sont orthogonaux, donc que l'angle $\\widehat{AMB}$ est droit.",
   sol:"$\\vec{MA}\\cdot\\vec{MB}=0\\iff \\vec{MA}\\perp\\vec{MB}\\iff \\widehat{AMB}=90^\\circ$ (ou $M\\in\\{A,B\\}$). L'ensemble cherché est le <b>cercle de diamètre $[AB]$</b>." },
 { niv:"Défi",
   en:"Soit $I$ le milieu de $[AB]$. Démontrer le théorème de la médiane : pour tout point $M$, $MA^2+MB^2=2\\,MI^2+\\dfrac{AB^2}{2}$.",
   hint:"Écris $\\vec{MA}=\\vec{MI}+\\vec{IA}$ et $\\vec{MB}=\\vec{MI}+\\vec{IB}$, avec $\\vec{IB}=-\\vec{IA}$, puis développe les carrés scalaires.",
   sol:"Comme $I$ est le milieu de $[AB]$, $\\vec{IB}=-\\vec{IA}$. Donc $MA^2=\\lVert\\vec{MI}+\\vec{IA}\\rVert^2=MI^2+2\\vec{MI}\\cdot\\vec{IA}+IA^2$ et $MB^2=\\lVert\\vec{MI}-\\vec{IA}\\rVert^2=MI^2-2\\vec{MI}\\cdot\\vec{IA}+IA^2$. En additionnant, les doubles produits s'éliminent : $MA^2+MB^2=2MI^2+2IA^2$. Or $IA=\\frac{AB}{2}$, donc $2IA^2=\\frac{AB^2}{2}$, d'où $MA^2+MB^2=2MI^2+\\frac{AB^2}{2}$." }
],

"Calcul trigonométrique": [
 { niv:"Application",
   en:"Résoudre dans $[0,2\\pi[$ l'équation $\\cos x=\\dfrac12$.",
   hint:"$\\cos x=\\cos\\frac{\\pi}{3}$ ; les solutions sont $x=\\frac{\\pi}{3}+2k\\pi$ ou $x=-\\frac{\\pi}{3}+2k\\pi$.",
   sol:"$\\cos x=\\frac12=\\cos\\frac{\\pi}{3}\\iff x\\equiv\\pm\\frac{\\pi}{3}\\ [2\\pi]$. Sur $[0,2\\pi[$ : $x=\\frac{\\pi}{3}$ ou $x=2\\pi-\\frac{\\pi}{3}=\\frac{5\\pi}{3}$. $S=\\left\\{\\frac{\\pi}{3},\\ \\frac{5\\pi}{3}\\right\\}$." },
 { niv:"Application",
   en:"Résoudre dans $[0,2\\pi[$ l'équation $\\sin x=\\dfrac{\\sqrt3}{2}$.",
   hint:"$\\sin x=\\sin\\frac{\\pi}{3}$ ; solutions $x=\\frac{\\pi}{3}+2k\\pi$ ou $x=\\pi-\\frac{\\pi}{3}+2k\\pi$.",
   sol:"$\\sin x=\\frac{\\sqrt3}{2}=\\sin\\frac{\\pi}{3}\\iff x\\equiv\\frac{\\pi}{3}\\ [2\\pi]$ ou $x\\equiv\\pi-\\frac{\\pi}{3}=\\frac{2\\pi}{3}\\ [2\\pi]$. Sur $[0,2\\pi[$ : $S=\\left\\{\\frac{\\pi}{3},\\ \\frac{2\\pi}{3}\\right\\}$." },
 { niv:"Moyen",
   en:"Simplifier l'expression $A=\\cos\\!\\left(\\dfrac{\\pi}{2}-x\\right)+\\sin(\\pi-x)$.",
   hint:"Utilise les angles associés : $\\cos\\!\\left(\\frac{\\pi}{2}-x\\right)=\\sin x$ et $\\sin(\\pi-x)=\\sin x$.",
   sol:"$\\cos\\!\\left(\\frac{\\pi}{2}-x\\right)=\\sin x$ et $\\sin(\\pi-x)=\\sin x$, donc $A=\\sin x+\\sin x=2\\sin x$." },
 { niv:"Moyen",
   en:"Démontrer l'identité : $\\cos(a+b)\\cos(a-b)=\\cos^2 a-\\sin^2 b$.",
   hint:"Développe chaque facteur avec les formules d'addition, puis utilise $\\cos^2 b=1-\\sin^2 b$ et $\\sin^2 a=1-\\cos^2 a$.",
   sol:"$\\cos(a+b)\\cos(a-b)=(\\cos a\\cos b-\\sin a\\sin b)(\\cos a\\cos b+\\sin a\\sin b)=\\cos^2 a\\cos^2 b-\\sin^2 a\\sin^2 b$. On remplace $\\cos^2 b=1-\\sin^2 b$ et $\\sin^2 a=1-\\cos^2 a$ : $=\\cos^2 a(1-\\sin^2 b)-(1-\\cos^2 a)\\sin^2 b=\\cos^2 a-\\cos^2 a\\sin^2 b-\\sin^2 b+\\cos^2 a\\sin^2 b=\\cos^2 a-\\sin^2 b.$" },
 { niv:"Défi",
   en:"Résoudre dans $[0,2\\pi[$ l'équation $2\\cos^2 x-3\\cos x+1=0$.",
   hint:"Pose $c=\\cos x$ et résous l'équation du second degré $2c^2-3c+1=0$, puis reviens à $x$ (avec $-1\\le c\\le1$).",
   sol:"Avec $c=\\cos x$ : $2c^2-3c+1=0$, discriminant $\\Delta=9-8=1$, donc $c=\\frac{3\\pm1}{4}$ : $c=1$ ou $c=\\frac12$. <br>$\\cos x=1\\iff x=0$. $\\cos x=\\frac12\\iff x=\\frac{\\pi}{3}$ ou $x=\\frac{5\\pi}{3}$. D'où $S=\\left\\{0,\\ \\frac{\\pi}{3},\\ \\frac{5\\pi}{3}\\right\\}$." }
],

"Suites numériques": [
 { niv:"Application",
   en:"Soit la suite définie par $u_n=3n-2$ pour $n\\in\\mathbb{N}$. Calculer $u_0,u_1,u_2$ et montrer que $(u_n)$ est arithmétique en précisant sa raison.",
   hint:"Calcule $u_{n+1}-u_n$ : si c'est une constante, la suite est arithmétique.",
   sol:"$u_0=-2$, $u_1=1$, $u_2=4$. $u_{n+1}-u_n=[3(n+1)-2]-[3n-2]=3$ (constante) : $(u_n)$ est <b>arithmétique</b> de raison $r=3$ et de premier terme $u_0=-2$." },
 { niv:"Application",
   en:"Soit $v_n=2\\times 3^{\\,n}$ pour $n\\in\\mathbb{N}$. Montrer que $(v_n)$ est géométrique et donner sa raison.",
   hint:"Calcule le quotient $\\dfrac{v_{n+1}}{v_n}$.",
   sol:"$\\frac{v_{n+1}}{v_n}=\\frac{2\\times3^{\\,n+1}}{2\\times3^{\\,n}}=3$ (constante) : $(v_n)$ est <b>géométrique</b> de raison $q=3$ et de premier terme $v_0=2$." },
 { niv:"Moyen",
   en:"Soit $(u_n)$ définie par $u_0=1$ et $u_{n+1}=2u_n+3$. On pose $w_n=u_n+3$. Montrer que $(w_n)$ est géométrique, puis exprimer $u_n$ en fonction de $n$.",
   hint:"Calcule $w_{n+1}=u_{n+1}+3$ et factorise pour faire apparaître $w_n=u_n+3$.",
   sol:"$w_{n+1}=u_{n+1}+3=2u_n+3+3=2u_n+6=2(u_n+3)=2w_n$ : $(w_n)$ est géométrique de raison $2$, $w_0=u_0+3=4$. Donc $w_n=4\\times2^{\\,n}=2^{\\,n+2}$, d'où $u_n=w_n-3=2^{\\,n+2}-3$." },
 { niv:"Moyen",
   en:"Calculer la somme $S=1+2+3+\\cdots+100$, puis démontrer que la somme des $n$ premiers nombres impairs vaut $1+3+5+\\cdots+(2n-1)=n^2$.",
   hint:"Pour $S$, utilise $1+2+\\cdots+n=\\frac{n(n+1)}{2}$. Pour les impairs, écris la somme comme (somme jusqu'à $2n$) moins (somme des pairs).",
   sol:"$S=\\frac{100\\times101}{2}=5050$.<br>Somme des impairs : $\\sum_{k=1}^{n}(2k-1)=2\\sum_{k=1}^{n}k-\\sum_{k=1}^{n}1=2\\cdot\\frac{n(n+1)}{2}-n=n(n+1)-n=n^2.$" },
 { niv:"Défi",
   en:"Soit $(u_n)$ définie par $u_0=0$ et $u_{n+1}=\\dfrac12 u_n+1$. On pose $t_n=u_n-2$. Montrer que $(t_n)$ est géométrique, exprimer $u_n$, puis étudier le sens de variation de $(u_n)$.",
   hint:"Le nombre $2$ est le point fixe ($\\ell=\\frac12\\ell+1$). Calcule $t_{n+1}=u_{n+1}-2$.",
   sol:"$t_{n+1}=u_{n+1}-2=\\frac12u_n+1-2=\\frac12u_n-1=\\frac12(u_n-2)=\\frac12 t_n$ : $(t_n)$ est géométrique de raison $\\frac12$, $t_0=u_0-2=-2$. Donc $t_n=-2\\left(\\frac12\\right)^{n}$ et $u_n=2+t_n=2-2\\left(\\frac12\\right)^{n}=2-\\left(\\frac12\\right)^{n-1}$.<br>Comme $t_n=-\\frac{2}{2^{n}}$ croît (vers $0$), $(u_n)$ est <b>strictement croissante</b> et majorée par $2$." }
],

"Limite d'une fonction numérique": [
 { niv:"Application",
   en:"Calculer $\\displaystyle\\lim_{x\\to 2}\\frac{x^2-4}{x-2}$.",
   hint:"Forme indéterminée $\\frac00$ : factorise le numérateur avec l'identité $x^2-4=(x-2)(x+2)$.",
   sol:"$\\frac{x^2-4}{x-2}=\\frac{(x-2)(x+2)}{x-2}=x+2$ (pour $x\\ne2$). Donc $\\displaystyle\\lim_{x\\to2}\\frac{x^2-4}{x-2}=2+2=4$." },
 { niv:"Application",
   en:"Calculer $\\displaystyle\\lim_{x\\to+\\infty}\\frac{3x^2-5}{x^2+1}$.",
   hint:"En $+\\infty$, mets en facteur le terme dominant $x^2$ au numérateur et au dénominateur.",
   sol:"$\\frac{3x^2-5}{x^2+1}=\\frac{x^2\\left(3-\\frac{5}{x^2}\\right)}{x^2\\left(1+\\frac{1}{x^2}\\right)}=\\frac{3-\\frac{5}{x^2}}{1+\\frac{1}{x^2}}\\xrightarrow[x\\to+\\infty]{}\\frac{3}{1}=3.$" },
 { niv:"Moyen",
   en:"Calculer $\\displaystyle\\lim_{x\\to 0}\\frac{\\sqrt{x+1}-1}{x}$.",
   hint:"Multiplie par la quantité conjuguée $\\sqrt{x+1}+1$.",
   sol:"$\\frac{\\sqrt{x+1}-1}{x}=\\frac{(\\sqrt{x+1}-1)(\\sqrt{x+1}+1)}{x(\\sqrt{x+1}+1)}=\\frac{(x+1)-1}{x(\\sqrt{x+1}+1)}=\\frac{x}{x(\\sqrt{x+1}+1)}=\\frac{1}{\\sqrt{x+1}+1}.$ D'où la limite $\\displaystyle\\lim_{x\\to0}=\\frac{1}{1+1}=\\frac12.$" },
 { niv:"Moyen",
   en:"Calculer $\\displaystyle\\lim_{x\\to+\\infty}\\left(\\sqrt{x^2+x}-x\\right)$.",
   hint:"Forme $\\infty-\\infty$ : multiplie par le conjugué $\\sqrt{x^2+x}+x$.",
   sol:"$\\sqrt{x^2+x}-x=\\frac{(x^2+x)-x^2}{\\sqrt{x^2+x}+x}=\\frac{x}{\\sqrt{x^2+x}+x}=\\frac{x}{x\\left(\\sqrt{1+\\frac1x}+1\\right)}=\\frac{1}{\\sqrt{1+\\frac1x}+1}\\xrightarrow[x\\to+\\infty]{}\\frac{1}{1+1}=\\frac12.$" },
 { niv:"Défi",
   en:"Soit $n\\in\\mathbb{N}^*$. Calculer $\\displaystyle\\lim_{x\\to 1}\\frac{x^n-1}{x-1}$.",
   hint:"Rappelle la factorisation $x^n-1=(x-1)(x^{n-1}+x^{n-2}+\\cdots+x+1)$.",
   sol:"$x^n-1=(x-1)(x^{n-1}+x^{n-2}+\\cdots+x+1)$, donc pour $x\\ne1$ : $\\frac{x^n-1}{x-1}=x^{n-1}+x^{n-2}+\\cdots+x+1$ ($n$ termes). En $x=1$, chaque terme vaut $1$ : $\\displaystyle\\lim_{x\\to1}\\frac{x^n-1}{x-1}=\\underbrace{1+1+\\cdots+1}_{n}=n.$" }
],

"Dérivation": [
 { niv:"Application",
   en:"Calculer la dérivée de $f(x)=3x^2-5x+2$, puis la valeur $f'(1)$.",
   hint:"$(x^2)'=2x$, $(x)'=1$, la dérivée d'une constante est nulle.",
   sol:"$f'(x)=6x-5$. Donc $f'(1)=6-5=1$." },
 { niv:"Application",
   en:"Déterminer l'équation de la tangente à la courbe de $f(x)=x^2$ au point d'abscisse $x_0=3$.",
   hint:"L'équation de la tangente en $x_0$ est $y=f'(x_0)(x-x_0)+f(x_0)$.",
   sol:"$f'(x)=2x$ donc $f'(3)=6$ et $f(3)=9$. Tangente : $y=6(x-3)+9=6x-9$." },
 { niv:"Moyen",
   en:"Dériver $g(x)=\\dfrac{2x+1}{x-1}$ sur $\\mathbb{R}\\setminus\\{1\\}$ et déterminer le signe de $g'$.",
   hint:"Utilise $\\left(\\dfrac{u}{v}\\right)'=\\dfrac{u'v-uv'}{v^2}$ avec $u=2x+1$, $v=x-1$.",
   sol:"$g'(x)=\\frac{2(x-1)-(2x+1)\\cdot1}{(x-1)^2}=\\frac{2x-2-2x-1}{(x-1)^2}=\\frac{-3}{(x-1)^2}$. Comme $(x-1)^2>0$, on a $g'(x)<0$ : $g$ est <b>strictement décroissante</b> sur $]-\\infty,1[$ et sur $]1,+\\infty[$." },
 { niv:"Moyen",
   en:"Soit $f(x)=x^3-3x+1$. Étudier les variations de $f$ sur $\\mathbb{R}$ (signe de $f'$, extremums).",
   hint:"$f'(x)=3x^2-3=3(x-1)(x+1)$ ; étudie son signe.",
   sol:"$f'(x)=3x^2-3=3(x^2-1)=3(x-1)(x+1)$. $f'(x)>0$ sur $]-\\infty,-1[$ et $]1,+\\infty[$, $f'(x)<0$ sur $]-1,1[$. Donc $f$ est croissante puis décroissante puis croissante. <b>Maximum local</b> en $x=-1$ : $f(-1)=-1+3+1=3$ ; <b>minimum local</b> en $x=1$ : $f(1)=1-3+1=-1$." },
 { niv:"Défi",
   en:"Montrer que pour tout $x\\ge 0$, $\\sqrt{1+x}\\le 1+\\dfrac{x}{2}$.",
   hint:"Étudie la fonction $h(x)=1+\\dfrac{x}{2}-\\sqrt{1+x}$ sur $[0,+\\infty[$ : calcule $h'$, son signe, et $h(0)$.",
   sol:"Posons $h(x)=1+\\frac{x}{2}-\\sqrt{1+x}$ sur $[0,+\\infty[$. Alors $h'(x)=\\frac12-\\frac{1}{2\\sqrt{1+x}}=\\frac{\\sqrt{1+x}-1}{2\\sqrt{1+x}}$. Pour $x\\ge0$, $\\sqrt{1+x}\\ge1$ donc $h'(x)\\ge0$ : $h$ est croissante. Comme $h(0)=1-1=0$, on a $h(x)\\ge h(0)=0$ pour tout $x\\ge0$, c'est-à-dire $1+\\frac{x}{2}\\ge\\sqrt{1+x}$." }
]

});
