/* ===== Dossiers d'œuvres — Français 1ère Bac (programme marocain) =====
   Contenu original rédigé pour Brio (résumés, analyses, fiches) : PAS le texte intégral des œuvres.
   Sert de base structurée pour les cours de Français, le Tuteur IA (contexte/RAG), les QCM et les flashcards.
   Clé = titre EXACT du chapitre (window.EDU_SUBJECTS.francais.chapters).
   Schéma : { titre, auteur, genre, publication, cadre, narration, contexte,
     resume:[{ch,titre,texte}], personnages:[{nom,role}], themes:[{t,d}], citations:[{c,note}], methodo:[..] } */
window.PB_OEUVRES = window.PB_OEUVRES || {};
Object.assign(window.PB_OEUVRES, {
"Œuvre : La Boîte à Merveilles (étude et thèmes)": {
  titre:"La Boîte à merveilles",
  auteur:"Ahmed Sefrioui",
  genre:"Roman autobiographique",
  publication:"1954",
  cadre:"Fès (médina), dans les années 1920, autour de Dar Chouafa.",
  narration:"Récit à la 1ʳᵉ personne : un narrateur adulte se souvient de son enfance et prête sa voix à l'enfant de six ans qu'il était, Sidi Mohamed. Double regard : celui de l'enfant (naïf, sensible) et celui de l'adulte (nostalgique, lucide).",
  contexte:"Œuvre fondatrice de la littérature marocaine d'expression française. Sefrioui y peint la vie populaire de la médina de Fès et le monde de l'enfance, sans revendication politique explicite : c'est une autobiographie romancée, centrée sur la mémoire, la solitude et le merveilleux.",
  resume:[
    {ch:1, titre:"La solitude, Dar Chouafa et le bain maure", texte:"Le <b>narrateur adulte</b> ouvre le récit sur sa solitude (« Ma solitude ne date pas d'hier ») et revoit l'enfant de six ans qu'il était, dressant dans une impasse un piège pour attraper un moineau — qu'il veut pour compagnon et qui ne vient jamais. Il présente <b>Dar Chouafa</b>, « la maison de la voyante » : au rez-de-chaussée vit la <b>Chouafa</b> (voyante et quelque peu sorcière, de la confrérie des Gnaoua, qui offre une fois par mois une séance de musique et de danses nègres dans des nuages de benjoin) ; au premier étage <b>Driss El Aouad</b>, sa femme <b>Rahma</b> et leur fille <b>Zineb</b> (d'un an son aînée, qu'il n'aime pas) ; au deuxième, la famille du narrateur et <b>Fatma Bziouya</b>. L'enfant, rêveur, « ne veut rien imiter, il veut connaître » ; il évoque <b>Abdallah l'épicier</b> et ses histoires. Longue <b>scène du bain maure (hammam)</b> où sa mère l'emmène : il prend la vapeur, les cris et les femmes qui courent avec des seaux pour l'<b>Enfer</b>, suce une orange et un œuf dur, est lavé brutalement puis abandonné sur l'estrade. Inventaire de la <b>Boîte à Merveilles</b> (boutons de porcelaine, boules de verre, clous à tête dorée, cadenas sans clef…), seuls amis de l'enfant. Le chapitre se clôt sur la <b>première grande querelle</b> : Rahma a fait sa lessive un lundi, jour réservé à la mère ; la dispute éclate (la mère se targue de nobles origines montagnardes, « descendants du Prophète »), reprend le soir devant le père silencieux, et l'enfant s'évanouit de détresse aux pieds de sa mère."},
    {ch:2, titre:"Le mardi au Msid et le pèlerinage à Sidi Ali Boughaleb", texte:"Le <b>mardi</b>, « jour néfaste », l'enfant subit le <b>fqih</b> et sa baguette de cognassier. À la maison, sa mère souffre d'une migraine (tempes garnies de rondelles de papier à la colle de farine). <b>Lalla Aïcha</b>, ancienne voisine et amie de la mère, rend visite et, voyant l'enfant pâle, propose d'aller tous les trois au sanctuaire de <b>Sidi Ali Boughaleb</b> lui faire boire de l'eau bénite. Récit détaillé de la <b>sortie</b> : les deux femmes à petits pas dans la cohue, l'enfant porté à bout de bras par-dessus les têtes, le cimetière, les marchands de sucreries. Au mausolée, les deux femmes supplient le saint ; la Moqadma reçoit une offrande de deux francs et explique que Sidi Ali Boughaleb, patron des médecins et des barbiers, aimait les chats (plus de cinquante au sanctuaire). L'enfant va caresser un gros matou qui lui lacère la main d'un <b>coup de griffe</b> ; le sang gicle, il hurle. Retour, coucher. Le lendemain, le père demande qu'on ne l'envoie pas au Msid ; dialogue imaginaire des deux moineaux sur « les figues sèches » ; salutations matinales des voisines (Rahma gifle Zineb qui mouille son lit ; la chouafa prédit à l'enfant un grand avenir, « un sabre parmi les sabres »). Fatma Bziouya offre des beignets (<b>sfenj</b>) ; portrait du père <b>tisserand</b>, monté de la montagne à Fès. En redescendant, <b>Rahma</b> glisse à l'enfant un cadeau de réconciliation : un gros <b>cabochon de verre taillé en diamant</b>, nouveau trésor pour sa Boîte."},
    {ch:3, titre:"La lampe à pétrole et la disparition de Zineb", texte:"Retour au Msid le vendredi. Un soir, la chambre de <b>Fatma Bziouya</b> brille d'un éclat nouveau : elle a acheté une <b>lampe à pétrole</b> (avec glace réfléchissante). La mère, émerveillée et jalouse, feint le dédain puis, dès le lendemain, se fait acheter par Driss le teigneux une lampe identique : joie immense, félicitations de tante Kanza. Le même jour, <b>Rahma rentre en pleurs</b> : partie avec sa fille <b>Zineb</b> à un baptême à Kalklyine, elle l'a <b>perdue</b> dans la foule du Rsif. Branle-bas général, pleureuses, crieurs publics. L'enfant pleure aussi — non pour Zineb qu'il n'aime pas, mais « parce qu'il a faim ». <b>Zineb est retrouvée</b> saine et sauve à Dar Kitoun, la maison des Idrissides, grâce à Fatma Bziouya et une vieille femme. Le jeudi suivant, pour remercier Dieu, Rahma offre un grand <b>repas de charité</b> aux pauvres : arrivée du cortège de mendiants aveugles conduits par leur patriarche, psalmodie du Coran, bénédictions sur la maison, puis festin et fête entre voisines. Le soir, l'enfant vide sa Boîte mais ses trésors « ne lui parlent plus »."},
    {ch:4, titre:"Chez Lalla Aïcha : le conflit Moulay Larbi / Abdelkader et Abdallah le conteur", texte:"Au printemps, la mère et l'enfant passent la journée chez <b>Lalla Aïcha</b> (impasse Zankat Hajjama) ; description de son logis, témoin d'une aisance passée. Sur la terrasse, l'enfant joue à la <b>mariée</b> avec les enfants de la maison, jeu qui tourne au drame. Les femmes bavardent ; revient plusieurs fois le mot inquiétant « <b>pacha</b> » ; Lalla Aïcha finit par pleurer. Le lendemain vendredi, la mère révèle au père l'affaire : <b>Moulay Larbi</b>, mari de Lalla Aïcha et fabricant de babouches, s'est brouillé avec son associé <b>Abdelkader</b> — un ancien ouvrier qu'il avait aidé, à qui il avait prêté 80 rials pour sa dot sans reconnaissance de dette et qu'il avait pris comme associé. Abdelkader a tout nié, prétendant même avoir versé la moitié du capital ; le pacha, puis les experts de la corporation, tranchent en sa faveur : « il n'y a plus de justice ». Le père enchaîne alors sur le long <b>récit d'Abdallah l'épicier</b>, conteur énigmatique de Haffarine (la querelle entre Lahbib le forgeron et Abdennebi le médisant), qui hante l'imagination de l'enfant."},
    {ch:5, titre:"Le sacrifice de Lalla Aïcha et la mort du coiffeur", texte:"Un mercredi, le fqih annonce joyeusement la préparation de l'<b>Achoura</b> (quinze jours) : chacun apportera de l'huile d'olive, l'école sera blanchie à la chaux et garnie de nattes neuves. La mère étant sortie avec Lalla Aïcha, l'enfant reste seul, terrifié par les objets. Au retour, la mère chuchote la nouvelle : <b>Lalla Aïcha a tout vendu</b> (bijoux et mobilier) pour que Moulay Larbi remonte son atelier et ne « perde pas la face » devant la corporation. Soudain, des hurlements : <b>Sidi Mohammed ben Tahar, le coiffeur</b> voisin, vient de mourir après deux mois de maladie. La mère passe par-dessus le mur « pleurer un peu » ; l'enfant l'y suit, et, ne parvenant pas à pleurer, assène un coup de poing à Zineb pour la faire crier. Obsédé par la mort, il imagine son propre enterrement escorté d'anges, tombe fiévreux ; le père récite des versets. Le lendemain, la mère lui donne une <b>chaînette de cuivre</b> qu'il astique en « or » ; le <b>chat de Zineb</b> s'enfuit avec cette chaîne-collier, déclenchant une violente bagarre entre l'enfant et Zineb."},
    {ch:6, titre:"Le nettoyage du Msid et les emplettes à la Kissaria", texte:"Préparatifs de l'Achoura au Msid : badigeon à la chaux (réservé aux grands), puis lavage du sol où l'enfant, nommé « <b>chef des frotteurs</b> », se dépense et rentre fier et épuisé. Le lendemain, sa mère l'emmène à la <b>Kissaria</b> (marché des tissus) choisir ses habits de fête : une cotonnade de qualité « <b>Poisson</b> » pour la chemise et un <b>gilet rouge cerise à soutaches</b> obtenu après un long marchandage (le marchand finit par céder en la flattant de « chérifa »). En chemin, elle doit aussi acheter la <b>satinette noire</b> de la chouafa Lalla Kanza pour ses robes de confréries (destinées aux génies Bel Lahmer, Lalla Mira, Sidi Moussa). De retour, chez Rahma, l'enfant se rengorge de son gilet, se dispute encore avec Zineb. Rahma raconte alors l'<b>histoire comique de Si Othman</b>, vieux mari dominé par sa jeune femme Lalla Khadija, qui revient bredouille du marché, offre une rose en guise d'excuse et se fait jeter dehors turban compris."},
    {ch:7, titre:"Les tambourins, le coiffeur Si Abderrahman et la nuit de l'Achoura", texte:"Toutes les femmes s'achètent tambourins et bendirs ; l'enfant reçoit une <b>trompette</b> en fer-blanc. Le fqih le fait venir aider à préparer les <b>lustres et veilleuses</b> (mèches, verres d'eau et d'huile colorée) pour illuminer le Msid. Le père l'emmène ensuite acheter des jouets (tambour en sablier, chariot, trompette) et un <b>cierge</b> pour le maître, puis chez le barbier <b>Si Abderrahman</b> (Chemaïne) : scène de la saignée aux ventouses, l'oncle Hammad malade, le jeune Sidi Ahmed promis à la fille de Si Omar le notaire, et surtout le coiffeur bavard, « poète de la rue ». <b>Détail capital</b> : Si Abderrahman suggère que Moulay Larbi, sans enfant, devrait prendre une seconde épouse, et parle de sa propre <b>fille à marier</b> — ce qui annonce le drame à venir. L'enfant est rasé (il s'endort, la lame le mord), essaie sa chemise neuve, mène un concert de tambours. Enfin, la <b>nuit de l'Achoura</b> : réveillé à trois heures, vêtu de neuf, il découvre le Msid métamorphosé en féerie de lumières, récite le Coran, offre son cierge et sa pièce au fqih, qui accorde quatre jours de congé. L'après-midi, Lalla Aïcha, mystérieuse, laisse entendre qu'elle « a beaucoup à raconter » et se méfie désormais des hommes."},
    {ch:8, titre:"Le souk des bijoux et le drame des bracelets", texte:"Après l'Achoura, retour à la grisaille : chaleur, mouches, punaises ; le Msid est transféré dans un petit sanctuaire plus frais, où l'enfant se met à <b>aimer l'école</b> et fait des progrès. Longue méditation : « les bijoux, c'est beau comme les fleurs ». Le père emmène toute la maisonnée au <b>souk des bijoux</b> pour offrir à la mère les bracelets « <b>soleil et lune</b> » (or et argent) promis. Le <b>dellal</b> (courtier) disparaît interminablement avec les bijoux ; l'attente dégénère en <b>bagarre</b> entre le père et le courtier (le père y perd son turban, le dellal saigne à la joue). De retour, le père pose les bracelets ; la mère, terrifiée, refuse de les porter — « <b>bijoux de mauvais augure</b> » — et les jette dans son coffre. La nuit, l'enfant fait un cauchemar (monstres, père à cheval sauvant la Boîte à Merveilles). Le lendemain, visite de Lalla Aïcha : après le récit du drame, celle-ci avoue en sanglotant que <b>Moulay Larbi</b>, pour qui elle s'est dépouillée, l'a <b>abandonnée pour une seconde épouse : la fille d'Abderrahman le coiffeur</b>. L'enfant, bouleversé, tombe vraiment malade (fièvre, vomissements)."},
    {ch:9, titre:"La perte du capital et le départ du père pour la moisson", texte:"L'enfant reste plusieurs jours fiévreux ; sa mère le veille, Fatma lui fait boire le <b>tadeffi</b> (soupe à la menthe sauvage). Un soir, le père rentre sombre et, au cours d'un dîner silencieux et tragique, annonce la catastrophe : il a <b>perdu tout son fonds de roulement</b> dans la cohue du souk des haïks (le mouchoir d'argent tombé à terre). Il ne peut plus payer son ouvrier ni le loyer de l'atelier. La mère se griffe le visage de désespoir. Le père, digne, décide de <b>partir travailler à la moisson</b> (campagne à deux jours de marche) pendant un mois pour reconstituer ses économies, et de vendre les bracelets pour laisser de l'argent. Il part à l'aube avec une sacoche de berger, une faucille neuve et des provisions (olives, figues sèches, farine grillée, pains d'anis, qarchalas). Suit un tendre <b>dialogue entre la mère et l'enfant</b> sur « l'attente » et le temps. Commencent alors les journées d'angoisse et de dénuement, et les nuits d'orage où une flûte étrange semble pleurer."},
    {ch:10, titre:"Le voyant Sidi El Arafi et le messager du père", texte:"La mère emmène l'enfant chez <b>Lalla Aïcha</b> (quartier Qalqlyine), dont le logis, jadis coquet, respire maintenant la misère. Toutes trois vont consulter le <b>voyant aveugle Sidi El Arafi</b> (quartier Seffah), homme pauvre mais rayonnant de bonté. Son <b>panier d'objets</b> (qui évoque pour l'enfant sa propre Boîte à Merveilles) sert à « lire les cœurs » : l'enfant y tire une boule de verre et reçoit la belle leçon du <b>diamant « l'orphelin, le solitaire »</b> (« si les hommes t'abandonnent, regarde en dedans de toi ») ; Lalla Aïcha tire un coquillage et s'entend prédire que son « <b>nid sera reconstruit</b> » ; la mère tire une perle noire et reçoit un message d'espoir. Au retour, l'enfant, allégé, redoute pourtant d'être vu dans la rue par le fqih alors qu'il est censé être malade. La mère décide de le garder à la maison durant l'absence du père et de visiter chaque semaine les sanctuaires. Surtout, un <b>messager venu de la campagne</b> apporte, de la part du père, des œufs, du beurre, de l'huile et <b>de l'argent</b> (trois pièces) : « Nous sommes riches ! » ; la mère partage avec les voisines. Lalla Aïcha annonce une « surprise » pour le lendemain : Moulay Larbi reviendrait à la raison."},
    {ch:11, titre:"La marieuse Salama et les malheurs du second mariage", texte:"Chez Lalla Aïcha, la « surprise » est la <b>marieuse professionnelle Salama</b> (femme colossale, à la voix d'homme). Elle raconte comment <b>Moulay Larbi</b>, voulant un héritier, l'a chargée en secret de lui trouver une <b>seconde épouse</b>, et comment elle a servi d'intermédiaire au mariage avec la <b>fille du coiffeur Si Abderrahman</b>. L'enfant interrompt le récit pour aller aux cabinets ; une voisine acariâtre menace de lui « couper les oreilles » ; Salama le protège et l'amadoue de cornes de gazelle. Salama dépeint ensuite la jeune épouse : <b>capricieuse, paresseuse, dépensière</b> (elle réclame bracelets d'or et argent, organise des thés, joue du tam-tam), poussée par une mère qui s'immisce sans cesse ; Moulay Larbi en est malheureux et regrette Lalla Aïcha. Survient <b>Zhor</b>, jeune voisine très maquillée, qui relate une scène récente : la fille du coiffeur a jeté à terre un foulard grenat jugé vulgaire, a menacé de se couper la gorge avec un verre cassé, accuse son mari devant les voisins ; elle ne cuisine pas, dort jusqu'à midi, si bien que Moulay Larbi dort désormais à son atelier. Les femmes médisent longuement de la famille du coiffeur ; l'enfant, grisé par « la musique des syllabes », renverse son verre de thé sous les regards furieux."},
    {ch:12, titre:"Le retour du père, le divorce de Moulay Larbi et la Boîte à Merveilles", texte:"Un matin baigné de gaieté, toute la maison chante (Kanza, Rahma, Fatma, la mère) ; l'enfant improvise ses propres chansons (« Ô nuit ! Ô lune ! ») et pense à Zhor. Un coup à la porte : <b>Allal El Yacoubi</b>, élève envoyé par le fqih prendre des nouvelles ; l'enfant, pris de panique, se cache derrière le lit tandis que la mère répond qu'il n'est pas encore remis. La mère le gourmande, puis <b>Zineb</b> arrive en courant annoncer la grande nouvelle : elle a vu dans la rue le <b>Maâlem Abdeslem</b>, deux poulets à la main. <b>Le père revient</b> (visage hâlé couleur terre cuite, djellaba sentant la campagne), rapportant poulets, œufs, beurre, huile, olives et galette paysanne ; joie générale, you-you des voisines. L'enfant, sur ses genoux, raconte « à sa façon » l'absence. <b>Driss El Aouad</b> monte et annonce que le <b>divorce entre Moulay Larbi et la fille du coiffeur</b> a été prononcé la veille devant notaire — la prédiction de Sidi El Arafi s'accomplit, « le nid est reconstruit ». Le soir, malgré le bonheur retrouvé, l'enfant se sent « triste et seul » ; il tire de sous le lit sa <b>Boîte à Merveilles</b>, l'ouvre religieusement : « Toutes les figures de mes rêves m'y attendaient. » — <i>Fès, 1952.</i>"}
  ],
  personnages:[
    {nom:"Sidi Mohamed", role:"Le narrateur-enfant (6 ans), fils unique, sensible, rêveur et solitaire. Sa boîte à merveilles est son refuge. C'est aussi le narrateur adulte qui se souvient."},
    {nom:"Lalla Zoubida", role:"La mère : superstitieuse, bavarde, aimante et protectrice ; elle rythme la vie du foyer et croit aux forces occultes."},
    {nom:"Maâlem Abdeslam", role:"Le père : tisserand, homme pieux, droit et travailleur. Sa ruine puis son départ à la campagne structurent l'intrigue."},
    {nom:"Lalla Aïcha", role:"Amie de la mère, épouse de Moulay Larbi. Ses malheurs conjugaux (l'associé, puis la seconde épouse) forment une intrigue secondaire."},
    {nom:"Moulay Larbi", role:"Mari de Lalla Aïcha, fabricant de babouches ; ses échecs et sa seconde union illustrent les épreuves du monde adulte."},
    {nom:"La Chouafa", role:"Voyante qui occupe le rez-de-chaussée de Dar Chouafa ; incarne le monde de la superstition et du merveilleux populaire."},
    {nom:"Rahma", role:"Voisine (1ᵉʳ étage), mère de Zineb ; l'épisode de Zineb perdue puis retrouvée la met en avant."},
    {nom:"Le fqih", role:"Maître du Msid (école coranique), sévère ; représente l'éducation religieuse traditionnelle."},
    {nom:"Fatma Bziouya", role:"Voisine, épouse d'Allal le jardinier ; participe à la vie collective et aux querelles de Dar Chouafa."}
  ],
  themes:[
    {t:"L'enfance et la solitude", d:"L'enfant, unique et incompris, se réfugie dans l'imaginaire et dans sa boîte à merveilles. La solitude est le fil conducteur du récit."},
    {t:"Le merveilleux et la superstition", d:"Voyance, amulettes, croyances populaires, visions de la fièvre : le réel se mêle sans cesse au surnaturel dans le regard de l'enfant et le monde des femmes."},
    {t:"La vie populaire de la médina de Fès", d:"Peinture ethnographique : Dar Chouafa, le hammam, le Msid, les souks, l'Achoura, les métiers artisanaux. Sefrioui fixe un patrimoine et un art de vivre."},
    {t:"La famille et les liens", d:"Tendresse maternelle, dignité du père, solidarité et querelles du voisinage : la cellule familiale et la communauté soutiennent l'enfant."},
    {t:"L'argent et l'épreuve", d:"La ruine du père, son départ pour la moisson, la gêne de la mère : le récit montre la précarité et la façon d'y faire face avec dignité."},
    {t:"La mémoire et la nostalgie", d:"Le narrateur adulte recompose son enfance : le récit est un acte de mémoire, teinté de nostalgie et de tendresse."}
  ],
  citations:[
    {c:"« Le sommeil peuple mes nuits de rêves, mes journées de fantômes. »", note:"Incipit : pose d'emblée la solitude du narrateur et l'importance du rêve/de l'imaginaire."},
    {c:"La « boîte à merveilles »", note:"Objet-titre et symbole : le coffret où l'enfant garde ses trésors (billes, boutons, clous…) est son refuge contre la solitude et la porte de son imaginaire."},
    {c:"« Dar Chouafa »", note:"La maison de la voyante : microcosme de la médina, elle réunit tous les personnages et ancre le merveilleux populaire."},
    {c:"Le « Msid »", note:"L'école coranique : lieu de l'apprentissage, de la discipline et de la peur du fqih ; cadre récurrent de la vie de l'enfant."}
  ],
  methodo:[
    "Pour situer un extrait : identifie le moment du récit (avant/après l'Achoura, avant/après le départ du père) et le lieu (Dar Chouafa, Msid, hammam, chez Lalla Aïcha).",
    "Questions fréquentes au régional : genre de l'œuvre (roman autobiographique), narrateur (Sidi Mohamed), procédés (le double regard enfant/adulte), tonalité (souvent lyrique), champ lexical des sentiments.",
    "Pour la production écrite liée à l'œuvre : appuie-toi sur les thèmes (enfance, solitude, métiers, superstition) et illustre par un exemple précis tiré du récit."
  ]
},
"Œuvre : Antigone (étude et thèmes)": {
  titre:"Antigone",
  auteur:"Jean Anouilh",
  genre:"Tragédie moderne (en un acte)",
  publication:"1944",
  cadre:"Thèbes, cité du mythe grec, dans un décor neutre et intemporel : réécriture de l'Antigone de Sophocle, créée à Paris (théâtre de l'Atelier) le 4 février 1944, sous l'Occupation.",
  narration:"Œuvre théâtrale (et non récit) : il n'y a pas de narrateur mais une énonciation dramatique. Un personnage, <b>le Prologue</b>, présente d'emblée les personnages et annonce le dénouement ; <b>le Chœur</b> commente l'action et théorise la tragédie. Le registre est tragique, mais Anouilh modernise le mythe par des <b>anachronismes volontaires</b> (cartes à jouer, cigarettes, voitures, langage familier) qui rapprochent la fable antique du spectateur de 1944.",
  resume:[
    {ch:1, titre:"Le Prologue", texte:"Tous les personnages sont en scène. <b>Le Prologue</b> se détache et les présente un à un : <b>Antigone</b> (« la petite maigre » assise à l'écart, qui va se dresser seule contre Créon et mourir), <b>Ismène</b> (sa sœur, « la blonde, la belle, l'heureuse »), <b>Hémon</b> (fils de Créon et fiancé d'Antigone), <b>Créon</b> (le roi aux cheveux blancs, fatigué, qui « a retroussé ses manches » à la mort d'Œdipe), <b>Eurydice</b> (sa femme, qui tricote), <b>le Messager</b> (pâle, qui annoncera la mort d'Hémon) et les trois <b>Gardes</b> qui jouent aux cartes. Le Prologue rappelle le <b>contexte</b> : Étéocle et Polynice, les deux fils d'Œdipe, devaient régner un an chacun ; Étéocle l'aîné a refusé de céder la place, et les deux frères se sont entre-tués sous les murs de Thèbes. Créon, devenu roi, a ordonné des funérailles solennelles pour Étéocle « le bon frère », mais a interdit, <b>sous peine de mort</b>, d'enterrer Polynice « le vaurien », laissé en pâture aux corbeaux et aux chacals."},
    {ch:2, titre:"Antigone et la nourrice (l'aube)", texte:"Dans une aube grise, <b>Antigone rentre furtivement</b>, pieds nus, ses souliers à la main. <b>La nourrice</b> la surprend et l'interroge ; croyant à un rendez-vous amoureux, elle la gronde et menace de prévenir Créon. Antigone, tour à tour grave et câline, la rassure : elle n'a « pas d'autre amoureux qu'Hémon ». Le spectateur devine qu'elle revient d'avoir tenté d'<b>enterrer son frère Polynice</b> en bravant l'édit."},
    {ch:3, titre:"Premier affrontement des deux sœurs", texte:"<b>Ismène</b>, raisonnable et prudente, a « bien réfléchi toute la nuit » et tente de <b>dissuader</b> Antigone : Créon est le roi, il les ferait mourir ; elle évoque la foule hostile, le supplice, la peur et la douleur. Antigone refuse de « comprendre » et campe sur sa décision. Ismène lance : « C'est bon pour les hommes de croire aux idées et de mourir pour elles. Toi tu es une fille. » Antigone, elle, ne veut pas de ce bonheur raisonnable."},
    {ch:4, titre:"Antigone et la nourrice (le café, la chienne Douce)", texte:"Moment de tendresse et de régression vers l'enfance : Antigone réclame la chaleur et la main de sa nourrice (« nounou plus forte que la mort »). Par des demandes qui sont autant d'<b>adieux voilés</b>, elle lui fait promettre de ne plus gronder sa chienne <b>Douce</b>, de lui parler « comme à une vraie personne », et, si la bête était trop triste, de la faire tuer « sans qu'elle ait mal ». La nourrice ne comprend pas le sens de ces recommandations."},
    {ch:5, titre:"Les adieux à Hémon", texte:"<b>Hémon</b> paraît. Antigone lui demande pardon pour leur dispute de la veille, puis lui fait <b>jurer de sortir sans la questionner</b>. Elle lui avoue qu'elle était venue chez lui la veille « pour être sa femme », évoque le petit garçon qu'ils auraient eu, puis lui déclare brutalement qu'elle ne pourra <b>jamais l'épouser</b> et le chasse en menaçant de se jeter par la fenêtre. Restée seule, elle murmure : « C'est fini pour Hémon, Antigone. »"},
    {ch:6, titre:"Second passage d'Ismène", texte:"<b>Ismène</b> revient supplier sa sœur de renoncer, de ne pas aller « là-bas cette nuit ». Antigone lui révèle qu'il est <b>déjà trop tard</b> : « Ce matin, quand tu m'as rencontrée, j'en venais. » — elle a donc déjà recouvert le corps de Polynice une première fois."},
    {ch:7, titre:"Créon et le garde : la première découverte", texte:"<b>Le garde Jonas</b>, vert de peur, vient annoncer à Créon que le cadavre de Polynice a été <b>recouvert d'un peu de terre</b>, « selon les rites », par une main inconnue (on a trouvé une petite pelle d'enfant). Créon, incrédule, y voit d'abord un <b>complot politique</b> contre lui. Il ordonne de dégager le corps, de doubler la garde et de <b>garder le secret sous peine de mort</b>."},
    {ch:8, titre:"Le Chœur : la mécanique tragique", texte:"<b>Le Chœur</b> s'avance et commente : « le ressort est bandé », la machine tragique n'a plus qu'à « se dérouler toute seule ». Il livre une célèbre <b>définition de la tragédie</b>, opposée au drame : elle est « propre », « reposante » et « sûre » parce qu'il n'y a plus d'espoir — on est « pris comme un rat », il ne reste qu'à crier ce qu'on a à dire. C'est une pause réflexive avant le nœud de l'action."},
    {ch:9, titre:"L'arrestation d'Antigone", texte:"Les gardes amènent <b>Antigone, prise en flagrant délit</b> : elle est revenue et a recommencé à recouvrir le corps, cette fois <b>à mains nues</b> (ses ongles sont pleins de terre), refusant de fuir. Les trois gardes, vulgaires et indifférents à son sort, bavardent de leur futur « gueuleton » et de la récompense qu'ils espèrent, tandis qu'elle demande humblement à s'asseoir."},
    {ch:10, titre:"Le grand affrontement Créon / Antigone", texte:"Cœur de la pièce. Créon, apprenant que c'est sa nièce, veut la <b>sauver</b> : il propose d'étouffer l'affaire (personne ne sait). Antigone refuse : « Puisque vous savez bien que je recommencerai. » S'engage un long <b>débat</b> : le devoir fraternel contre la loi de la cité ; Créon <b>démystifie les rites funèbres</b> (« ce bredouillage en série sur sa dépouille », cette « pantomime »). Antigone finit par avouer qu'elle n'agit « ni pour les autres, ni pour son frère », mais « pour personne. Pour moi ». Elle lance : « Je suis là pour vous dire non et pour mourir. »"},
    {ch:11, titre:"Le secret des deux frères", texte:"Pour la détourner de la mort, Créon lui révèle la vérité « effroyable » que lui seul connaît : <b>Étéocle et Polynice étaient deux voyous équivalents</b>, deux « larrons en foire » qui avaient tous deux trahi et tenté de faire assassiner leur père. Après la bataille, leurs corps étaient <b>méconnaissables</b> ; Créon a fait ramasser au hasard l'un d'eux pour les funérailles nationales et laissé pourrir l'autre — il ne sait même pas lequel. Antigone, ébranlée, demande : « Pourquoi m'avez-vous raconté cela ? » Elle semble renoncer et s'apprête à <b>remonter dans sa chambre</b>."},
    {ch:12, titre:"Le retournement : le refus du bonheur", texte:"Croyant l'avoir sauvée, Créon évoque le <b>bonheur</b> et la vie (« la vie… ferme tes mains, retiens-la »). Le mot « bonheur » <b>révolte</b> Antigone : elle refuse le bonheur « modeste » et quotidien, cette vie où Hémon deviendrait « le monsieur Hémon » qui apprendrait à dire « oui ». Elle veut « <b>tout, tout de suite — et que ce soit entier — ou alors je refuse</b> ». Elle insulte Créon (« cuisinier »), lui renvoie son « vous avez dit oui », et le pousse à bout en exigeant qu'il appelle ses gardes."},
    {ch:13, titre:"Ismène et l'ordre fatal", texte:"<b>Ismène</b> réapparaît, prête cette fois à <b>mourir avec sa sœur</b>. Antigone la repousse durement : « Tu as choisi la vie et moi la mort. » Poussé à bout et sachant désormais que « tout Thèbes sait », Créon crie « <b>Gardes !</b> » et fait emmener Antigone. Celle-ci pousse alors un grand cri <b>soulagé</b> : « Enfin, Créon ! »"},
    {ch:14, titre:"Créon et Hémon", texte:"<b>Le Chœur</b> supplie Créon d'épargner Antigone ; le roi répond qu'« elle voulait mourir » et que Polynice « n'était qu'un prétexte ». <b>Hémon</b> entre, éperdu, et supplie son père de ne pas laisser emmener sa fiancée. Il découvre l'<b>impuissance</b> de ce père qu'il admirait (« Ce dieu géant qui m'enlevait dans ses bras… c'était toi ? ») et s'enfuit en criant le nom d'Antigone, « touché à mort »."},
    {ch:15, titre:"Antigone et le garde : la lettre", texte:"Antigone reste seule avec un <b>garde</b>, son « dernier visage d'homme ». Prosaïque et indifférent, il ne lui parle que de sa <b>solde et de son avancement</b>. Il lui apprend qu'on va la <b>murer vivante</b> dans un trou. Contre sa bague en or, elle lui <b>dicte une lettre</b> pour Hémon : elle y avoue son doute (« Créon avait raison… je ne sais plus pourquoi je meurs. J'ai peur »), puis, par pudeur, efface tout pour ne garder que : « <b>Pardon.</b> » Le garde empoche la bague et l'emmène."},
    {ch:16, titre:"Le récit du Messager", texte:"<b>Le Messager</b> rapporte le dénouement sanglant : à peine Antigone murée, on a entendu des plaintes dans le tombeau. Antigone s'était <b>pendue</b> aux fils de sa ceinture (bleus, verts, rouges, « comme un collier d'enfant ») ; <b>Hémon</b>, la tenant dans ses bras, a <b>craché au visage de son père</b> accouru, puis s'est <b>enfoncé l'épée dans le ventre</b>, s'étendant contre Antigone « dans une immense flaque rouge »."},
    {ch:17, titre:"La mort d'Eurydice et la solitude de Créon", texte:"Créon revient et fait coucher les deux amants côte à côte. Le Chœur lui apprend alors la dernière nouvelle : <b>Eurydice</b>, sa femme, en apprenant la mort de son fils, a tranquillement posé son tricot puis s'est <b>tranché la gorge</b>. Créon reste <b>absolument seul</b> avec son petit page. Malgré tout, l'heure sonne (cinq heures) : il a <b>conseil</b>, et il y va — « il faut bien que quelqu'un le fasse »."},
    {ch:18, titre:"L'épilogue du Chœur", texte:"<b>Le Chœur</b> conclut : tous ceux qui devaient mourir sont morts ; « sans la petite Antigone, ils auraient tous été bien tranquilles ». Un « grand apaisement triste » tombe sur Thèbes, et Créon va « commencer à attendre la mort ». Seuls restent les <b>gardes</b>, indifférents à tout, qui reprennent leur <b>partie de cartes</b> tandis que le rideau tombe."}
  ],
  personnages:[
    {nom:"Antigone", role:"L'héroïne tragique, fille d'Œdipe, « la petite maigre », noire et maigre face à sa sœur. Révoltée absolue, elle refuse tout compromis et toute explication, dit « non » au nom de l'exigence et de la pureté, et préfère mourir plutôt que de renoncer à enterrer son frère. Fiancée d'Hémon."},
    {nom:"Créon", role:"Roi de Thèbes, oncle d'Antigone et frère de Jocaste. Homme vieillissant, lucide et pragmatique, qui « a retroussé ses manches » pour gouverner. Il incarne la raison d'État et le « métier » de roi (dire « oui »). Il tente désespérément de sauver Antigone et finit seul, ayant perdu son fils et sa femme."},
    {nom:"Ismène", role:"Sœur aînée d'Antigone : belle, blonde, amoureuse de la vie, raisonnable et craintive. Elle refuse d'abord de suivre sa sœur, puis, trop tard, veut mourir avec elle."},
    {nom:"Hémon", role:"Fils de Créon et fiancé d'Antigone. Amoureux absolu et idéaliste, il renie son père (« ce n'est pas toi ») et se suicide près du corps d'Antigone dans le tombeau."},
    {nom:"La Nourrice", role:"Figure maternelle et terre-à-terre, toute de tendresse et de langage quotidien (le café, les lainages, la chienne Douce). Elle incarne la chaleur de l'enfance et la vie simple qu'Antigone quitte."},
    {nom:"Eurydice", role:"Femme de Créon, « la vieille dame qui tricote » pour les pauvres : bonté silencieuse et digne. Elle se tranche la gorge en apprenant la mort de son fils Hémon."},
    {nom:"Le Chœur / Le Prologue", role:"Voix de l'auteur et commentateur : le Prologue présente les personnages et annonce le dénouement ; le Chœur théorise la tragédie (« c'est propre, la tragédie ») et tente en vain de fléchir Créon."},
    {nom:"Le Messager", role:"Jeune homme pâle et solitaire, pressenti dès le Prologue. Il vient annoncer la mort d'Antigone et le suicide d'Hémon."},
    {nom:"Les Gardes (Jonas, Durand, Boudousse)", role:"Brutes insensibles « sentant l'ail, le cuir et le vin rouge », obsédées par la solde, l'avancement et les récompenses. « Auxiliaires toujours innocents de la justice », ils jouent aux cartes, indifférents, jusqu'à la dernière scène."},
    {nom:"Polynice et Étéocle", role:"Les deux frères ennemis, fils d'Œdipe, entre-tués sous les murs de Thèbes : l'un honoré, l'autre privé de sépulture. Créon révèle qu'ils étaient en réalité deux voyous équivalents — le « prétexte » du conflit."},
    {nom:"Œdipe et Jocaste", role:"Le père et la mère disparus, évoqués tout au long : ils incarnent le poids de la malédiction familiale et « l'orgueil d'Œdipe » dont Antigone hérite."}
  ],
  themes:[
    {t:"Le refus et la révolte", d:"Antigone incarne le « non » absolu face à l'ordre établi : elle refuse de « comprendre », de transiger, de vieillir. Son refus est le ressort même de la tragédie."},
    {t:"La liberté face au devoir et à la loi", d:"Conflit central entre la loi de la cité (Créon, l'édit) et la loi morale et intime (Antigone, le devoir envers le frère) : jusqu'où la liberté individuelle peut-elle dire non au pouvoir ?"},
    {t:"Le pouvoir et la raison d'État", d:"Créon défend le « métier » de roi : gouverner, c'est accepter de dire « oui », de se salir les mains pour que « la barque » ne coule pas. L'image du bateau dans la tempête résume cette nécessité."},
    {t:"Le bonheur refusé", d:"À l'idéal du bonheur quotidien et « modeste » que lui vante Créon, Antigone oppose son exigence d'absolu : « je veux tout, tout de suite — ou alors je refuse »."},
    {t:"La tragédie et le destin", d:"La fatalité est annoncée dès le Prologue ; le Chœur décrit la mécanique « bien huilée » de la tragédie, où tout est joué d'avance et où il n'y a « plus d'espoir »."},
    {t:"La pureté et l'enfance contre la compromission", d:"Antigone veut rester fidèle à l'enfant qu'elle était, pure et entière, face au monde adulte des compromis, de l'usure et des « petites pauvretés » quotidiennes."},
    {t:"L'engagement (contexte de 1944)", d:"Créée sous l'Occupation, la pièce se prête à une double lecture : Antigone comme figure de la Résistance face au pouvoir, Créon comme l'homme de l'ordre — ambiguïté voulue qui fait sa richesse."}
  ],
  citations:[
    {c:"« Je suis là pour vous dire non et pour mourir. »", note:"Antigone — la formule qui résume son refus absolu et son choix de la mort contre la soumission."},
    {c:"« Vous avez dit oui. »", note:"Antigone renvoie à Créon le consentement au pouvoir qui le condamne à « payer » toujours : l'opposition oui / non structure toute la pièce."},
    {c:"« Il faut pourtant qu'il y en ait qui disent oui. »", note:"Créon — la défense du « métier » de roi et de la raison d'État (image du bateau à gouverner dans la tempête)."},
    {c:"« Moi, je veux tout, tout de suite — et que ce soit entier. »", note:"Antigone — son exigence d'absolu et son refus du bonheur partiel et quotidien."},
    {c:"« C'est propre, la tragédie. C'est reposant, c'est sûr… »", note:"Le Chœur — définition de la tragédie opposée au drame : tout est joué d'avance, il n'y a plus d'espoir."},
    {c:"« Sans la petite Antigone, vous auriez tous été bien tranquilles. »", note:"Mot d'Antigone (sa lettre) repris par le Chœur à la fin : l'héroïne comme grain de sable qui enraye l'ordre du monde."}
  ],
  methodo:[
    "Pour situer un passage : repère le moment dans la progression dramatique (le Prologue ; les scènes du matin avec la nourrice, Ismène et Hémon ; le grand débat Créon / Antigone ; le dénouement et l'épilogue) et les personnages en présence.",
    "Questions fréquentes au régional : le genre (tragédie moderne, réécriture du mythe de Sophocle), le rôle du Prologue et du Chœur, les anachronismes volontaires (cartes, cigarettes, voitures) qui modernisent le mythe, le registre tragique, l'opposition des personnages (Antigone / Ismène, Antigone / Créon).",
    "Pour la production écrite liée à l'œuvre : appuie-toi sur les thèmes (révolte, liberté, bonheur, devoir, destin) et illustre par un épisode précis (le débat Antigone-Créon, les adieux à Hémon, la lettre dictée au garde).",
    "Contexte à mobiliser : pièce créée en 1944, sous l'Occupation ; sa double lecture possible (résistance / ordre établi) explique la richesse et l'ambiguïté de son interprétation."
  ]
},
"Œuvre : Le Dernier Jour d'un Condamné (étude et thèmes)": {
  titre:"Le Dernier Jour d'un Condamné",
  auteur:"Victor Hugo",
  genre:"Roman à thèse — journal intime d'un condamné",
  publication:"1829 (préface engagée ajoutée en 1832)",
  cadre:"Paris, vers 1829 : la prison de Bicêtre, puis la Conciergerie, enfin l'Hôtel de Ville et la place de Grève, lieu des exécutions publiques.",
  narration:"Récit à la <b>1ʳᵉ personne</b> : un homme condamné à mort tient le <b>journal</b> de ses dernières semaines, « heure par heure », jusqu'à l'instant du supplice (le texte s'interrompt net). Le <b>héros n'a pas de nom et son crime n'est jamais révélé</b> (les feuillets de « Mon histoire » sont perdus) : Hugo veut plaider la cause d'« un condamné quelconque ». L'œuvre alterne <b>chapitres-récits</b> (le procès, le ferrage des forçats, le transfert, la visite de Marie) et <b>chapitres-méditations</b> (angoisse, souvenirs, visions). La <b>préface de 1832</b> en fait un <b>plaidoyer explicite contre la peine de mort</b>.",
  resume:[
    {ch:1, titre:"Bicêtre — l'idée fixe", texte:"Le narrateur vit depuis cinq semaines dans son cachot de <b>Bicêtre</b>, obsédé par une seule pensée : « <b>Condamné à mort !</b> ». Autrefois libre et l'esprit plein de fantaisies, il n'est plus que le captif de cette idée qui le hante éveillé et le poursuit jusque dans ses rêves, sous la forme d'un couteau."},
    {ch:2, titre:"Le procès (retour en arrière)", texte:"Il revit son <b>procès</b> par une belle matinée d'août : trois jours de débats, la foule avide « comme des corbeaux ». Pendant que les jurés délibéraient, il dormait. Son avocat espère les travaux forcés ; lui s'écrie « plutôt cent fois la mort ! ». Le greffier lit le verdict, le président l'<b>arrêt de mort</b>. Une « révolution » se fait en lui : une cloison le sépare désormais du monde. Deux jeunes filles : « ce sera dans six semaines »."},
    {ch:3, titre:"Méditation sur la mort", texte:"Il médite : « les hommes sont tous condamnés à mort avec des sursis indéfinis ». Qu'y a-t-il de si changé ? Que regrette-t-il de la vie misérable du cachot ? Et pourtant, conclut-il, « c'est horrible »."},
    {ch:4, titre:"Bicêtre vu de près", texte:"Retour sur son arrivée à <b>Bicêtre</b> : de loin, l'édifice a la majesté d'un château de roi ; de près, ce n'est qu'une masure lépreuse aux barreaux de fer. « C'est la vie vue de près. »"},
    {ch:5, titre:"Les premiers jours de détention", texte:"On multiplie les précautions (camisole, ni couteau ni fourchette). Il s'est pourvu en <b>cassation</b>. D'abord traité avec une douceur « horrible » (« les égards d'un guichetier sentent l'échafaud »), il est ensuite confondu avec les autres détenus. Sa docilité et quelques mots de latin lui valent la promenade hebdomadaire, de l'encre et du papier. Au préau, les prisonniers lui apprennent l'<b>argot</b>."},
    {ch:6, titre:"Pourquoi écrire ce journal", texte:"Il décide de tenir le <b>journal de ses souffrances</b>, « heure par heure, minute par minute ». Ce « procès-verbal de la pensée agonisante », cette « autopsie intellectuelle d'un condamné », pourrait être, une fois publié, « une leçon pour ceux qui condamnent »."},
    {ch:7, titre:"La révolte : « c'est moi qu'il faudrait sauver »", texte:"Il doute de l'utilité de son journal : à quoi bon sauver d'autres têtes quand la sienne tombera ? Révolte devant tout ce qu'il va perdre — le soleil, le printemps, la liberté, la vie : « <b>c'est moi qu'il faudrait sauver !</b> »."},
    {ch:8, titre:"Le compte des jours", texte:"Il calcule froidement les délais de la procédure (trois jours pour le pourvoi, huit au parquet, quinze chez le ministre, la cassation un jeudi…) et aboutit au total : « <b>En tout six semaines. La petite fille avait raison.</b> »"},
    {ch:9, titre:"Le testament — Marie", texte:"Il fait son testament. Il laisse une <b>mère</b> de soixante-quatre ans, une <b>femme</b> de santé fragile et une <b>fille de trois ans, Marie</b> : « trois veuves du fait de la loi ». C'est sa petite fille, « qui rit, qui joue », qui lui fait le plus mal."},
    {ch:10, titre:"Description du cachot", texte:"Il décrit son <b>cachot</b> : huit pieds carrés, une botte de paille, une voûte en ogive, pas de fenêtre mais un judas grillagé, un factionnaire jour et nuit. Ces cachots datent du XVᵉ siècle, du cardinal de Winchester « qui fit brûler Jeanne d'Arc »."},
    {ch:11, titre:"Les inscriptions sur les murs", texte:"La nuit, il lit à la lampe les <b>écritures laissées par les condamnés précédents</b> (cœurs enflammés, « Vive l'empereur ! 1824 », Papavoine, Bories de La Rochelle…). Puis il découvre, crayonnée au coin du mur, l'<b>image d'un échafaud</b> : la lampe lui tombe presque des mains."},
    {ch:12, titre:"Les noms des criminels et la vision", texte:"Il arrache une toile d'araignée et met au jour d'autres noms de grands criminels (Dautun, Poulain, Jean Martin, Castaing, Papavoine). Pris de fièvre, il a une <b>vision hallucinée</b> : le cachot plein d'hommes portant leur tête dans la main. Une araignée frôlant son pied nu le réveille."},
    {ch:13, titre:"Le ferrage des forçats", texte:"D'une cellule-observatoire, il assiste au <b>ferrage de la chaîne</b> qui part pour Toulon : les prisonniers aux fenêtres, l'arrivée des argousins, les forçats hideux et bravaches (un jeune baladin de dix-sept ans acclamé), la visite médicale, puis les <b>carcans rivés à froid</b> sous une averse glaciale, et la ronde-« sabbat ». Les forçats le repèrent : « Le condamné ! il sera rogné ! ». Il s'évanouit."},
    {ch:14, titre:"Le départ de la chaîne", texte:"Réveillé à l'infirmerie, il voit, le lendemain, partir sous la pluie les <b>cinq charrettes de forçats</b> vers Toulon (vingt-cinq jours de route). Il préfère mille fois l'échafaud au bagne : « plutôt le néant que l'enfer »."},
    {ch:15, titre:"Retour au cachot — plus d'espoir", texte:"Sorti de l'infirmerie, le cachot le reprend. Il n'est pas malade, sauf d'« une maladie faite de la main des hommes ». Idée poignante : il aurait pu s'évader de l'infirmerie. Il n'espère plus : « Je n'ai plus que trois pas à faire : <b>Bicêtre, la Conciergerie, la Grève</b>. »"},
    {ch:16, titre:"La chanson de la jeune fille", texte:"À l'infirmerie, il espérait un oiseau ; vient à la place la <b>voix d'une jeune fille de quinze ans</b> chantant une complainte en argot (un vol, le guet, la guillotine). Contraste déchirant entre la douceur de la voix et l'horreur des paroles : « on eût dit la bave d'une limace sur une rose »."},
    {ch:17, titre:"Rêverie d'évasion", texte:"Il imagine une <b>évasion</b> : courir à travers champs, se déguiser en maraîcher, se cacher près d'Arcueil, gagner l'Angleterre… mais un gendarme, un passeport demandé : « Je suis perdu ! ». Retour au réel : le mur épais de trois pieds. « La mort ! la mort ! »"},
    {ch:18, titre:"« Est-ce pour aujourd'hui ? »", texte:"Le jour se lève, six heures sonnent. Le guichetier entre, le salue et lui demande ce qu'il veut à déjeuner. Un frisson le prend : « Est-ce que ce serait pour aujourd'hui ? »"},
    {ch:19, titre:"« C'est pour aujourd'hui ! »", texte:"Le directeur de la prison lui rend visite, s'informe de sa santé et, en le quittant, l'appelle « <b>monsieur</b> » — signe fatal : « C'est pour aujourd'hui ! »"},
    {ch:20, titre:"La prison faite homme", texte:"Il voit dans le geôlier obséquieux « la prison incarnée », « Bicêtre qui s'est fait homme ». Tout autour de lui est prison, sous forme de pierre, de bois, ou de chair. « Que vais-je devenir ? »"},
    {ch:21, titre:"Le rejet du pourvoi", texte:"Un vieux <b>prêtre</b> entre (« êtes-vous préparé ? »), puis un <b>huissier</b> lui lit le <b>rejet de son pourvoi</b> : l'arrêt sera exécuté le jour même en place de Grève ; départ à sept heures et demie pour la Conciergerie. Il cherche désespérément, et en vain, un moyen de fuir."},
    {ch:22, titre:"Le transfert à la Conciergerie", texte:"Récit du <b>transfert</b> dans une voiture grillée, sous la pluie, escorté de huit hommes. L'huissier bavarde futilement (la garde nationale, « la nouvelle de Paris ») ; le condamné répond avec une amère ironie (« chaque quart d'heure me vieillit d'une année »). Les tours de Notre-Dame ; arrivée à la Conciergerie à huit heures et demie."},
    {ch:23, titre:"Le friauche", texte:"Dans un cabinet, surgit un autre condamné : un <b>vieux forçat repoussant</b> (« un friauche »), le condamné du jour, son « héritier ». Long <b>monologue en argot</b> retraçant sa vie de misère, de bagne et de crimes — l'enfant abandonné devenu assassin. Plus fort que le narrateur, il lui <b>prend sa redingote</b> et lui laisse sa veste infâme."},
    {ch:24, titre:"La rage", texte:"Resté seul, le narrateur est plein de rage contre le vieux voleur qui lui a pris sa redingote : il aurait voulu l'étrangler. « La mort rend méchant. »"},
    {ch:25, titre:"La cellule de la Conciergerie", texte:"On l'installe dans une cellule nue ; il réclame une table, de quoi écrire et un lit. Un gendarme vient s'asseoir dans « sa chambre » — par crainte, sans doute, qu'il ne s'étrangle."},
    {ch:26, titre:"Pensée à sa fille", texte:"Dix heures. Pensée déchirante à <b>Marie</b> : « encore six heures et je serai mort », un corps qu'on disséquera et qui ira à Clamart. Qui l'aimera désormais ? Elle rougira un jour de son nom « sanglant »."},
    {ch:27, titre:"L'ignorance de la guillotine", texte:"Il ne sait même pas comment fonctionne la <b>guillotine</b> ni comment on meurt dessus ; le mot hideux « de dix lettres », la bascule, le couperet le hantent. « Mes cheveux blanchiront avant que ma tête ne tombe ! »"},
    {ch:28, titre:"Le souvenir de la place de Grève", texte:"Il se rappelle avoir un jour entrevu l'<b>échafaud</b> qu'on dressait place de Grève, et une femme disant à un enfant : « le couteau coule mal, ils vont graisser la rainure ». « Cette fois, je ne détournerai pas la tête. »"},
    {ch:29, titre:"Le cri de la grâce", texte:"Élan d'espoir : « Ô ma grâce ! » Il accepterait les galères, le fer rouge, la perpétuité — « mais grâce de la vie ! ». « Un forçat, cela voit encore le soleil. »"},
    {ch:30, titre:"L'aumônier usé", texte:"L'<b>aumônier</b> revient : bon vieillard, mais qui récite ses consolations « comme une leçon déjà vingt fois récitée », sans émotion. Le condamné reste froid et le repousse, rêvant d'un vrai prêtre bouleversé. On lui apporte un repas fin qu'il ne peut avaler."},
    {ch:31, titre:"Le sous-architecte", texte:"Un <b>sous-architecte</b> entre et mesure les murs à voix haute, indifférent : « dans six mois cette prison sera beaucoup mieux ». Le gendarme le rabroue : « on ne parle pas si haut dans la chambre d'un mort »."},
    {ch:32, titre:"Le gendarme et la loterie", texte:"Un gendarme stupide lui demande de lui révéler, une fois mort, trois <b>numéros de loterie</b> gagnants. Fol espoir du condamné : il propose d'<b>échanger les habits</b> pour s'évader ; mais le gendarme comprend et refuse (« pour qu'ils soient bons, il faut que vous soyez mort »). L'espoir s'effondre."},
    {ch:33, titre:"Souvenirs de jeunesse — Pepa", texte:"Il se réfugie dans ses <b>souvenirs d'enfance et de jeunesse</b> : le jardin du Val-de-Grâce, la petite Espagnole <b>Pepa (Pepita)</b>, et le <b>premier baiser</b> échangé un soir d'été sous les marronniers. « J'avais le paradis dans le cœur. »"},
    {ch:34, titre:"Le remords impossible", texte:"De retour au présent, il voudrait se repentir davantage, mais « il n'y a plus de place que pour les pensées de mort ». « Ma belle enfance ! ma belle jeunesse ! étoffe dorée dont l'extrémité est sanglante. » « Je n'étais pas un méchant ! »"},
    {ch:35, titre:"La vie indifférente des autres", texte:"Tout près de lui, dans Paris, des hommes vont et viennent, causent, rient, vendent ; des jeunes filles préparent leur robe de bal, des mères jouent avec leurs enfants — tandis que lui va mourir."},
    {ch:36, titre:"Le bourdon de Notre-Dame", texte:"Souvenir d'enfance : monté au <b>bourdon de Notre-Dame</b>, il avait été saisi de vertige et de terreur quand l'énorme cloche avait tinté. « Il me semble que je suis encore dans la tour du bourdon » — un étourdissement où la vie des autres n'apparaît plus que « à travers les crevasses d'un abîme »."},
    {ch:37, titre:"L'Hôtel de Ville sinistre", texte:"Bref tableau de l'<b>Hôtel de Ville</b>, édifice lugubre « si noir qu'il est noir au soleil », qui « vomit des gendarmes » les jours d'exécution et regarde le condamné « avec toutes ses fenêtres »."},
    {ch:38, titre:"Les symptômes de l'angoisse", texte:"Une heure et quart. Il décrit ses <b>symptômes physiques</b> : violente douleur de tête, front brûlant, tressaillements convulsifs, la plume qui tombe. « Encore deux heures et quarante-cinq minutes, et je serai guéri. »"},
    {ch:39, titre:"« On ne souffre pas » ?", texte:"On prétend que la mort par la guillotine « ne fait pas souffrir ». Mais, objecte-t-il, et l'agonie de six semaines ? Et qui peut affirmer qu'une tête coupée ne souffre pas ? « Horreur ! »"},
    {ch:40, titre:"L'obsession du roi", texte:"Il pense sans cesse au <b>roi</b> : un homme « aussi haut que tu es bas », entouré de gloire, qui d'un trait de plume — « les sept lettres de son nom » — pourrait tout lui rendre, la vie, la liberté, la famille. « Et il n'en sera rien ! »"},
    {ch:41, titre:"Regarder la mort en face", texte:"Il veut affronter l'idée de la mort et sonder l'<b>au-delà</b> : visions successives d'une grande clarté, d'un gouffre de ténèbres, ou d'une tête qui roule ; les morts de la Grève se rassemblant les nuits d'hiver. « Ah ! un prêtre ! un crucifix à baiser ! »"},
    {ch:42, titre:"Le cauchemar de la vieille", texte:"Il s'endort une heure et fait un <b>cauchemar</b> : la nuit, chez lui, un bruit, une vieille femme muette cachée dans l'armoire ; approchant la bougie de son menton, il la voit souffler la flamme et lui <b>mordre la main</b> de trois dents aiguës. Il se réveille en sueur : l'aumônier lui annonce que sa fille est là."},
    {ch:43, titre:"La visite de Marie", texte:"<b>Marie</b>, trois ans, fraîche et rose, est amenée — mais elle <b>ne reconnaît pas son père</b> (la barbe, la pâleur) : « un monsieur ». Elle affirme que son papa « est mort » et qu'elle prie pour lui. Déchirement. Puis elle épelle un papier que sa bonne a acheté un sou : c'est la <b>sentence de mort</b> de son père (« ARRÊT »). Il la fait emmener, « sombre, désert, désespéré »."},
    {ch:44, titre:"Se roidir", texte:"Après le départ de l'enfant, il doit « se roidir » et penser fermement au bourreau, à la charrette, à la foule, à la place de Grève. « Je crois que j'ai encore une heure. »"},
    {ch:45, titre:"La foule et les têtes prédestinées", texte:"Dans cette foule qui rira et applaudira, songe-t-il, il y aura « plus d'une tête prédestinée » qui suivra la sienne « tôt ou tard dans le panier rouge » : la place de Grève est un piège fatal."},
    {ch:46, titre:"Écrire pour Marie", texte:"« Ma petite Marie ! » — on l'a remmenée jouer, elle ne pense déjà plus à « ce monsieur ». Il veut lui laisser son <b>histoire</b>, pour qu'elle la lise un jour et comprenne « pourquoi le nom que je lui laisse est sanglant »."},
    {ch:47, titre:"« Mon histoire » (feuillets perdus)", texte:"Le chapitre s'ouvre sur « Mon histoire », mais une <b>note de l'éditeur</b> indique que les feuillets n'ont pu être retrouvés : le condamné n'a pas eu le temps de les écrire. Le <b>crime reste donc inconnu</b> — c'est l'universalité voulue par Hugo."},
    {ch:48, titre:"L'Hôtel de Ville — la toilette du condamné", texte:"Transféré à l'<b>Hôtel de Ville</b>, il subit la « <b>toilette du condamné</b> » : cheveux coupés, mains liées, col de chemise tranché, par le bourreau <b>Samson</b> et ses valets « très doux ». Sur la charrette (dos tourné au cheval), le trajet vers la Grève au milieu de la foule qui crie « Chapeaux bas ! comme pour le roi » — « <b>Eux les chapeaux, moi la tête.</b> » À l'arrivée, il demande une dernière déclaration pour gagner du temps."},
    {ch:49, titre:"Quatre heures", texte:"Dans une chambre de l'Hôtel de Ville, il supplie à genoux un magistrat de lui accorder sa <b>grâce</b>, ou « cinq minutes encore ». Le bourreau presse (il pleut, « cela risque de se rouiller »). « Ma grâce ! ma grâce ! » Il croit entendre monter l'escalier… « <b>QUATRE HEURES.</b> » — le récit s'interrompt net, sur l'exécution."}
  ],
  personnages:[
    {nom:"Le Condamné (narrateur)", role:"Le héros anonyme : jeune homme d'une quarantaine d'années, instruit et raffiné, qui tient le journal de ses dernières semaines. Son nom et son crime ne sont jamais révélés, afin qu'il incarne « un condamné quelconque » et, à travers lui, tous les condamnés."},
    {nom:"Marie", role:"Sa fille de trois ans, douce et rose. Lors de leur dernière entrevue, elle ne reconnaît plus son père et le croit mort. Elle symbolise l'innocence frappée et la famille brisée par la peine de mort."},
    {nom:"La mère et la femme du condamné", role:"Évoquées dans le testament : une mère de soixante-quatre ans et une épouse de santé fragile. Avec Marie, elles forment « trois veuves du fait de la loi »."},
    {nom:"L'aumônier de la prison", role:"Vieux prêtre bon mais usé par son office, qui récite ses consolations sans émotion. Le condamné le repousse, rêvant d'un prêtre réellement bouleversé qui le prendrait par le cœur."},
    {nom:"Le friauche", role:"Vieux forçat repoussant rencontré à la Conciergerie, condamné à mort à son tour. Son récit de misère et de crimes (en argot) fait de lui le double social du héros : le crime né de la pauvreté et de l'abandon."},
    {nom:"Le bourreau (Samson) et ses valets", role:"Les exécuteurs, prosaïques et « très doux », qui procèdent à la toilette du condamné ; ils incarnent la banalité administrative de la mise à mort."},
    {nom:"La foule", role:"Personnage collectif, avide et cruel, « buveuse de sang », qui se presse aux exécutions comme à un spectacle et applaudit le supplice."},
    {nom:"Les figures de l'indifférence", role:"L'huissier bavard, le gendarme qui réclame des numéros de loterie, le sous-architecte qui mesure les murs, le directeur, les guichetiers : tous illustrent l'indifférence de la société face à l'agonie d'un homme."},
    {nom:"Pepa (Pepita)", role:"La petite Espagnole des souvenirs de jeunesse du narrateur ; le premier amour et le premier baiser, image lumineuse du bonheur perdu."}
  ],
  themes:[
    {t:"Le plaidoyer contre la peine de mort", d:"Thèse centrale et engagée de Hugo, explicitée dans la préface de 1832 : le roman est « un plaidoyer, direct ou indirect, pour l'abolition de la peine de mort »."},
    {t:"L'angoisse de la mort et l'idée fixe", d:"Le leitmotiv « condamné à mort » obsède le narrateur jour et nuit ; tout le récit est la montée de cette angoisse, de plus en plus hideuse à mesure que l'échéance approche."},
    {t:"La souffrance morale plus forte que la souffrance physique", d:"Le vrai supplice n'est pas le coup du couperet mais l'attente, « cette agonie de six semaines », « cette échelle de tortures qui aboutit à l'échafaud »."},
    {t:"La solitude et l'enfermement", d:"Le cachot, la camisole, le factionnaire, « la prison faite homme » : le condamné est séparé du monde par une cloison invisible, seul face à son idée."},
    {t:"L'anonymat et l'universalité", d:"L'absence de nom et de crime (feuillets perdus) dépouille le cas de tout particulier : Hugo plaide la cause de tous les condamnés, présents et à venir."},
    {t:"La critique de la société et de la justice", d:"La misère conduit au crime (le friauche, et Claude Gueux dans le même volume), la justice se cache et bâcle, la foule fait de la mort un spectacle : la société est aussi coupable que le criminel."},
    {t:"La famille brisée et l'innocence frappée", d:"En tuant un homme, la loi décapite toute sa famille : la mère, la femme et surtout la petite Marie, « orphelines du fait de la loi »."},
    {t:"Le souvenir et le contraste", d:"Face à l'horreur présente, le narrateur se réfugie dans les souvenirs lumineux de l'enfance et de la jeunesse (Pepa, le jardin) : contraste tragique entre le bonheur passé et l'échafaud."}
  ],
  citations:[
    {c:"« Condamné à mort ! »", note:"Le leitmotiv obsédant qui ouvre le récit et en scande les chapitres : l'idée fixe qui résume tout le supplice moral."},
    {c:"« Les hommes sont tous condamnés à mort avec des sursis indéfinis. »", note:"Chapitre III : méditation sur la condition humaine, qui universalise le sort du héros."},
    {c:"« C'est la vie vue de près. »", note:"Chapitre IV, sur Bicêtre : la désillusion face au réel, quand la majesté lointaine devient misère."},
    {c:"« C'est moi qu'il faudrait sauver ! »", note:"Chapitre VII : le cri de révolte contre l'inutilité et l'injustice de son supplice."},
    {c:"« Eux les chapeaux, moi la tête. »", note:"Chapitre XLVIII : mot amer du condamné devant la foule qui crie « Chapeaux bas ! comme pour le roi »."},
    {c:"« Un plaidoyer […] pour l'abolition de la peine de mort. »", note:"Préface de 1832 : Hugo y avoue enfin la visée politique et sociale de son livre."}
  ],
  methodo:[
    "Pour situer un passage : repère l'étape du parcours (le procès rappelé au ch. II ; Bicêtre ; le transfert et la Conciergerie ; l'Hôtel de Ville et la Grève) et distingue les chapitres-récits (événements : procès, ferrage, visite de Marie, toilette) des chapitres-méditations (réflexion et visions intérieures).",
    "Questions fréquentes au régional : le genre (roman à thèse, journal intime d'un condamné), le point de vue (narration à la 1ʳᵉ personne, focalisation interne), l'anonymat du héros et de son crime (universalité), le registre pathétique et tragique, la visée argumentative contre la peine de mort.",
    "Contexte à citer : œuvre publiée en 1829, préface engagée de 1832 ; Hugo milite pour l'abolition de la peine de mort (voir aussi Claude Gueux, publié dans le même volume).",
    "Pour la production écrite liée à l'œuvre : appuie-toi sur les thèmes (peine de mort, souffrance morale, solitude, misère et justice, famille) et illustre par un épisode précis (le ferrage des forçats, la visite de Marie, la toilette du condamné)."
  ]
}
});
