/* ===== Dossiers d'œuvres — Français 1ère Bac (programme marocain) =====
   Contenu original rédigé pour Brio (résumés, analyses, fiches) : PAS le texte intégral des œuvres.
   Sert de base structurée pour les cours de Français, le Tuteur IA (contexte/RAG), les QCM et les flashcards.
   Clé = titre EXACT du chapitre (window.EDU_SUBJECTS.francais.chapters).
   Schéma : { titre, auteur, genre, publication, cadre, narration, contexte,
     resume:[{ch,titre,texte}], personnages:[{nom,role}], themes:[{t,d}], citations:[{c,note}], methodo:[..] } */
window.PB_OEUVRES = window.PB_OEUVRES || {};
Object.assign(window.PB_OEUVRES, {
"Œuvre : La Boîte à Merveilles (étude et thèmes)": {
  titre:"La Boîte à merveilles",
  auteur:"Ahmed Sefrioui",
  genre:"Roman autobiographique",
  publication:"1954",
  cadre:"Fès (médina), dans les années 1920, autour de Dar Chouafa.",
  narration:"Récit à la 1ʳᵉ personne : un narrateur adulte se souvient de son enfance et prête sa voix à l'enfant de six ans qu'il était, Sidi Mohamed. Double regard : celui de l'enfant (naïf, sensible) et celui de l'adulte (nostalgique, lucide).",
  contexte:"Œuvre fondatrice de la littérature marocaine d'expression française. Sefrioui y peint la vie populaire de la médina de Fès et le monde de l'enfance, sans revendication politique explicite : c'est une autobiographie romancée, centrée sur la mémoire, la solitude et le merveilleux.",
  resume:[
    {ch:1, titre:"La solitude, Dar Chouafa et le bain maure", texte:"Le <b>narrateur adulte</b> ouvre le récit sur sa solitude (« Ma solitude ne date pas d'hier ») et revoit l'enfant de six ans qu'il était, dressant dans une impasse un piège pour attraper un moineau — qu'il veut pour compagnon et qui ne vient jamais. Il présente <b>Dar Chouafa</b>, « la maison de la voyante » : au rez-de-chaussée vit la <b>Chouafa</b> (voyante et quelque peu sorcière, de la confrérie des Gnaoua, qui offre une fois par mois une séance de musique et de danses nègres dans des nuages de benjoin) ; au premier étage <b>Driss El Aouad</b>, sa femme <b>Rahma</b> et leur fille <b>Zineb</b> (d'un an son aînée, qu'il n'aime pas) ; au deuxième, la famille du narrateur et <b>Fatma Bziouya</b>. L'enfant, rêveur, « ne veut rien imiter, il veut connaître » ; il évoque <b>Abdallah l'épicier</b> et ses histoires. Longue <b>scène du bain maure (hammam)</b> où sa mère l'emmène : il prend la vapeur, les cris et les femmes qui courent avec des seaux pour l'<b>Enfer</b>, suce une orange et un œuf dur, est lavé brutalement puis abandonné sur l'estrade. Inventaire de la <b>Boîte à Merveilles</b> (boutons de porcelaine, boules de verre, clous à tête dorée, cadenas sans clef…), seuls amis de l'enfant. Le chapitre se clôt sur la <b>première grande querelle</b> : Rahma a fait sa lessive un lundi, jour réservé à la mère ; la dispute éclate (la mère se targue de nobles origines montagnardes, « descendants du Prophète »), reprend le soir devant le père silencieux, et l'enfant s'évanouit de détresse aux pieds de sa mère."},
    {ch:2, titre:"Le mardi au Msid et le pèlerinage à Sidi Ali Boughaleb", texte:"Le <b>mardi</b>, « jour néfaste », l'enfant subit le <b>fqih</b> et sa baguette de cognassier. À la maison, sa mère souffre d'une migraine (tempes garnies de rondelles de papier à la colle de farine). <b>Lalla Aïcha</b>, ancienne voisine et amie de la mère, rend visite et, voyant l'enfant pâle, propose d'aller tous les trois au sanctuaire de <b>Sidi Ali Boughaleb</b> lui faire boire de l'eau bénite. Récit détaillé de la <b>sortie</b> : les deux femmes à petits pas dans la cohue, l'enfant porté à bout de bras par-dessus les têtes, le cimetière, les marchands de sucreries. Au mausolée, les deux femmes supplient le saint ; la Moqadma reçoit une offrande de deux francs et explique que Sidi Ali Boughaleb, patron des médecins et des barbiers, aimait les chats (plus de cinquante au sanctuaire). L'enfant va caresser un gros matou qui lui lacère la main d'un <b>coup de griffe</b> ; le sang gicle, il hurle. Retour, coucher. Le lendemain, le père demande qu'on ne l'envoie pas au Msid ; dialogue imaginaire des deux moineaux sur « les figues sèches » ; salutations matinales des voisines (Rahma gifle Zineb qui mouille son lit ; la chouafa prédit à l'enfant un grand avenir, « un sabre parmi les sabres »). Fatma Bziouya offre des beignets (<b>sfenj</b>) ; portrait du père <b>tisserand</b>, monté de la montagne à Fès. En redescendant, <b>Rahma</b> glisse à l'enfant un cadeau de réconciliation : un gros <b>cabochon de verre taillé en diamant</b>, nouveau trésor pour sa Boîte."},
    {ch:3, titre:"La lampe à pétrole et la disparition de Zineb", texte:"Retour au Msid le vendredi. Un soir, la chambre de <b>Fatma Bziouya</b> brille d'un éclat nouveau : elle a acheté une <b>lampe à pétrole</b> (avec glace réfléchissante). La mère, émerveillée et jalouse, feint le dédain puis, dès le lendemain, se fait acheter par Driss le teigneux une lampe identique : joie immense, félicitations de tante Kanza. Le même jour, <b>Rahma rentre en pleurs</b> : partie avec sa fille <b>Zineb</b> à un baptême à Kalklyine, elle l'a <b>perdue</b> dans la foule du Rsif. Branle-bas général, pleureuses, crieurs publics. L'enfant pleure aussi — non pour Zineb qu'il n'aime pas, mais « parce qu'il a faim ». <b>Zineb est retrouvée</b> saine et sauve à Dar Kitoun, la maison des Idrissides, grâce à Fatma Bziouya et une vieille femme. Le jeudi suivant, pour remercier Dieu, Rahma offre un grand <b>repas de charité</b> aux pauvres : arrivée du cortège de mendiants aveugles conduits par leur patriarche, psalmodie du Coran, bénédictions sur la maison, puis festin et fête entre voisines. Le soir, l'enfant vide sa Boîte mais ses trésors « ne lui parlent plus »."},
    {ch:4, titre:"Chez Lalla Aïcha : le conflit Moulay Larbi / Abdelkader et Abdallah le conteur", texte:"Au printemps, la mère et l'enfant passent la journée chez <b>Lalla Aïcha</b> (impasse Zankat Hajjama) ; description de son logis, témoin d'une aisance passée. Sur la terrasse, l'enfant joue à la <b>mariée</b> avec les enfants de la maison, jeu qui tourne au drame. Les femmes bavardent ; revient plusieurs fois le mot inquiétant « <b>pacha</b> » ; Lalla Aïcha finit par pleurer. Le lendemain vendredi, la mère révèle au père l'affaire : <b>Moulay Larbi</b>, mari de Lalla Aïcha et fabricant de babouches, s'est brouillé avec son associé <b>Abdelkader</b> — un ancien ouvrier qu'il avait aidé, à qui il avait prêté 80 rials pour sa dot sans reconnaissance de dette et qu'il avait pris comme associé. Abdelkader a tout nié, prétendant même avoir versé la moitié du capital ; le pacha, puis les experts de la corporation, tranchent en sa faveur : « il n'y a plus de justice ». Le père enchaîne alors sur le long <b>récit d'Abdallah l'épicier</b>, conteur énigmatique de Haffarine (la querelle entre Lahbib le forgeron et Abdennebi le médisant), qui hante l'imagination de l'enfant."},
    {ch:5, titre:"Le sacrifice de Lalla Aïcha et la mort du coiffeur", texte:"Un mercredi, le fqih annonce joyeusement la préparation de l'<b>Achoura</b> (quinze jours) : chacun apportera de l'huile d'olive, l'école sera blanchie à la chaux et garnie de nattes neuves. La mère étant sortie avec Lalla Aïcha, l'enfant reste seul, terrifié par les objets. Au retour, la mère chuchote la nouvelle : <b>Lalla Aïcha a tout vendu</b> (bijoux et mobilier) pour que Moulay Larbi remonte son atelier et ne « perde pas la face » devant la corporation. Soudain, des hurlements : <b>Sidi Mohammed ben Tahar, le coiffeur</b> voisin, vient de mourir après deux mois de maladie. La mère passe par-dessus le mur « pleurer un peu » ; l'enfant l'y suit, et, ne parvenant pas à pleurer, assène un coup de poing à Zineb pour la faire crier. Obsédé par la mort, il imagine son propre enterrement escorté d'anges, tombe fiévreux ; le père récite des versets. Le lendemain, la mère lui donne une <b>chaînette de cuivre</b> qu'il astique en « or » ; le <b>chat de Zineb</b> s'enfuit avec cette chaîne-collier, déclenchant une violente bagarre entre l'enfant et Zineb."},
    {ch:6, titre:"Le nettoyage du Msid et les emplettes à la Kissaria", texte:"Préparatifs de l'Achoura au Msid : badigeon à la chaux (réservé aux grands), puis lavage du sol où l'enfant, nommé « <b>chef des frotteurs</b> », se dépense et rentre fier et épuisé. Le lendemain, sa mère l'emmène à la <b>Kissaria</b> (marché des tissus) choisir ses habits de fête : une cotonnade de qualité « <b>Poisson</b> » pour la chemise et un <b>gilet rouge cerise à soutaches</b> obtenu après un long marchandage (le marchand finit par céder en la flattant de « chérifa »). En chemin, elle doit aussi acheter la <b>satinette noire</b> de la chouafa Lalla Kanza pour ses robes de confréries (destinées aux génies Bel Lahmer, Lalla Mira, Sidi Moussa). De retour, chez Rahma, l'enfant se rengorge de son gilet, se dispute encore avec Zineb. Rahma raconte alors l'<b>histoire comique de Si Othman</b>, vieux mari dominé par sa jeune femme Lalla Khadija, qui revient bredouille du marché, offre une rose en guise d'excuse et se fait jeter dehors turban compris."},
    {ch:7, titre:"Les tambourins, le coiffeur Si Abderrahman et la nuit de l'Achoura", texte:"Toutes les femmes s'achètent tambourins et bendirs ; l'enfant reçoit une <b>trompette</b> en fer-blanc. Le fqih le fait venir aider à préparer les <b>lustres et veilleuses</b> (mèches, verres d'eau et d'huile colorée) pour illuminer le Msid. Le père l'emmène ensuite acheter des jouets (tambour en sablier, chariot, trompette) et un <b>cierge</b> pour le maître, puis chez le barbier <b>Si Abderrahman</b> (Chemaïne) : scène de la saignée aux ventouses, l'oncle Hammad malade, le jeune Sidi Ahmed promis à la fille de Si Omar le notaire, et surtout le coiffeur bavard, « poète de la rue ». <b>Détail capital</b> : Si Abderrahman suggère que Moulay Larbi, sans enfant, devrait prendre une seconde épouse, et parle de sa propre <b>fille à marier</b> — ce qui annonce le drame à venir. L'enfant est rasé (il s'endort, la lame le mord), essaie sa chemise neuve, mène un concert de tambours. Enfin, la <b>nuit de l'Achoura</b> : réveillé à trois heures, vêtu de neuf, il découvre le Msid métamorphosé en féerie de lumières, récite le Coran, offre son cierge et sa pièce au fqih, qui accorde quatre jours de congé. L'après-midi, Lalla Aïcha, mystérieuse, laisse entendre qu'elle « a beaucoup à raconter » et se méfie désormais des hommes."},
    {ch:8, titre:"Le souk des bijoux et le drame des bracelets", texte:"Après l'Achoura, retour à la grisaille : chaleur, mouches, punaises ; le Msid est transféré dans un petit sanctuaire plus frais, où l'enfant se met à <b>aimer l'école</b> et fait des progrès. Longue méditation : « les bijoux, c'est beau comme les fleurs ». Le père emmène toute la maisonnée au <b>souk des bijoux</b> pour offrir à la mère les bracelets « <b>soleil et lune</b> » (or et argent) promis. Le <b>dellal</b> (courtier) disparaît interminablement avec les bijoux ; l'attente dégénère en <b>bagarre</b> entre le père et le courtier (le père y perd son turban, le dellal saigne à la joue). De retour, le père pose les bracelets ; la mère, terrifiée, refuse de les porter — « <b>bijoux de mauvais augure</b> » — et les jette dans son coffre. La nuit, l'enfant fait un cauchemar (monstres, père à cheval sauvant la Boîte à Merveilles). Le lendemain, visite de Lalla Aïcha : après le récit du drame, celle-ci avoue en sanglotant que <b>Moulay Larbi</b>, pour qui elle s'est dépouillée, l'a <b>abandonnée pour une seconde épouse : la fille d'Abderrahman le coiffeur</b>. L'enfant, bouleversé, tombe vraiment malade (fièvre, vomissements)."},
    {ch:9, titre:"La perte du capital et le départ du père pour la moisson", texte:"L'enfant reste plusieurs jours fiévreux ; sa mère le veille, Fatma lui fait boire le <b>tadeffi</b> (soupe à la menthe sauvage). Un soir, le père rentre sombre et, au cours d'un dîner silencieux et tragique, annonce la catastrophe : il a <b>perdu tout son fonds de roulement</b> dans la cohue du souk des haïks (le mouchoir d'argent tombé à terre). Il ne peut plus payer son ouvrier ni le loyer de l'atelier. La mère se griffe le visage de désespoir. Le père, digne, décide de <b>partir travailler à la moisson</b> (campagne à deux jours de marche) pendant un mois pour reconstituer ses économies, et de vendre les bracelets pour laisser de l'argent. Il part à l'aube avec une sacoche de berger, une faucille neuve et des provisions (olives, figues sèches, farine grillée, pains d'anis, qarchalas). Suit un tendre <b>dialogue entre la mère et l'enfant</b> sur « l'attente » et le temps. Commencent alors les journées d'angoisse et de dénuement, et les nuits d'orage où une flûte étrange semble pleurer."},
    {ch:10, titre:"Le voyant Sidi El Arafi et le messager du père", texte:"La mère emmène l'enfant chez <b>Lalla Aïcha</b> (quartier Qalqlyine), dont le logis, jadis coquet, respire maintenant la misère. Toutes trois vont consulter le <b>voyant aveugle Sidi El Arafi</b> (quartier Seffah), homme pauvre mais rayonnant de bonté. Son <b>panier d'objets</b> (qui évoque pour l'enfant sa propre Boîte à Merveilles) sert à « lire les cœurs » : l'enfant y tire une boule de verre et reçoit la belle leçon du <b>diamant « l'orphelin, le solitaire »</b> (« si les hommes t'abandonnent, regarde en dedans de toi ») ; Lalla Aïcha tire un coquillage et s'entend prédire que son « <b>nid sera reconstruit</b> » ; la mère tire une perle noire et reçoit un message d'espoir. Au retour, l'enfant, allégé, redoute pourtant d'être vu dans la rue par le fqih alors qu'il est censé être malade. La mère décide de le garder à la maison durant l'absence du père et de visiter chaque semaine les sanctuaires. Surtout, un <b>messager venu de la campagne</b> apporte, de la part du père, des œufs, du beurre, de l'huile et <b>de l'argent</b> (trois pièces) : « Nous sommes riches ! » ; la mère partage avec les voisines. Lalla Aïcha annonce une « surprise » pour le lendemain : Moulay Larbi reviendrait à la raison."},
    {ch:11, titre:"La marieuse Salama et les malheurs du second mariage", texte:"Chez Lalla Aïcha, la « surprise » est la <b>marieuse professionnelle Salama</b> (femme colossale, à la voix d'homme). Elle raconte comment <b>Moulay Larbi</b>, voulant un héritier, l'a chargée en secret de lui trouver une <b>seconde épouse</b>, et comment elle a servi d'intermédiaire au mariage avec la <b>fille du coiffeur Si Abderrahman</b>. L'enfant interrompt le récit pour aller aux cabinets ; une voisine acariâtre menace de lui « couper les oreilles » ; Salama le protège et l'amadoue de cornes de gazelle. Salama dépeint ensuite la jeune épouse : <b>capricieuse, paresseuse, dépensière</b> (elle réclame bracelets d'or et argent, organise des thés, joue du tam-tam), poussée par une mère qui s'immisce sans cesse ; Moulay Larbi en est malheureux et regrette Lalla Aïcha. Survient <b>Zhor</b>, jeune voisine très maquillée, qui relate une scène récente : la fille du coiffeur a jeté à terre un foulard grenat jugé vulgaire, a menacé de se couper la gorge avec un verre cassé, accuse son mari devant les voisins ; elle ne cuisine pas, dort jusqu'à midi, si bien que Moulay Larbi dort désormais à son atelier. Les femmes médisent longuement de la famille du coiffeur ; l'enfant, grisé par « la musique des syllabes », renverse son verre de thé sous les regards furieux."},
    {ch:12, titre:"Le retour du père, le divorce de Moulay Larbi et la Boîte à Merveilles", texte:"Un matin baigné de gaieté, toute la maison chante (Kanza, Rahma, Fatma, la mère) ; l'enfant improvise ses propres chansons (« Ô nuit ! Ô lune ! ») et pense à Zhor. Un coup à la porte : <b>Allal El Yacoubi</b>, élève envoyé par le fqih prendre des nouvelles ; l'enfant, pris de panique, se cache derrière le lit tandis que la mère répond qu'il n'est pas encore remis. La mère le gourmande, puis <b>Zineb</b> arrive en courant annoncer la grande nouvelle : elle a vu dans la rue le <b>Maâlem Abdeslem</b>, deux poulets à la main. <b>Le père revient</b> (visage hâlé couleur terre cuite, djellaba sentant la campagne), rapportant poulets, œufs, beurre, huile, olives et galette paysanne ; joie générale, you-you des voisines. L'enfant, sur ses genoux, raconte « à sa façon » l'absence. <b>Driss El Aouad</b> monte et annonce que le <b>divorce entre Moulay Larbi et la fille du coiffeur</b> a été prononcé la veille devant notaire — la prédiction de Sidi El Arafi s'accomplit, « le nid est reconstruit ». Le soir, malgré le bonheur retrouvé, l'enfant se sent « triste et seul » ; il tire de sous le lit sa <b>Boîte à Merveilles</b>, l'ouvre religieusement : « Toutes les figures de mes rêves m'y attendaient. » — <i>Fès, 1952.</i>"}
  ],
  personnages:[
    {nom:"Sidi Mohamed", role:"Le narrateur-enfant (6 ans), fils unique, sensible, rêveur et solitaire. Sa boîte à merveilles est son refuge. C'est aussi le narrateur adulte qui se souvient."},
    {nom:"Lalla Zoubida", role:"La mère : superstitieuse, bavarde, aimante et protectrice ; elle rythme la vie du foyer et croit aux forces occultes."},
    {nom:"Maâlem Abdeslam", role:"Le père : tisserand, homme pieux, droit et travailleur. Sa ruine puis son départ à la campagne structurent l'intrigue."},
    {nom:"Lalla Aïcha", role:"Amie de la mère, épouse de Moulay Larbi. Ses malheurs conjugaux (l'associé, puis la seconde épouse) forment une intrigue secondaire."},
    {nom:"Moulay Larbi", role:"Mari de Lalla Aïcha, fabricant de babouches ; ses échecs et sa seconde union illustrent les épreuves du monde adulte."},
    {nom:"La Chouafa", role:"Voyante qui occupe le rez-de-chaussée de Dar Chouafa ; incarne le monde de la superstition et du merveilleux populaire."},
    {nom:"Rahma", role:"Voisine (1ᵉʳ étage), mère de Zineb ; l'épisode de Zineb perdue puis retrouvée la met en avant."},
    {nom:"Le fqih", role:"Maître du Msid (école coranique), sévère ; représente l'éducation religieuse traditionnelle."},
    {nom:"Fatma Bziouya", role:"Voisine, épouse d'Allal le jardinier ; participe à la vie collective et aux querelles de Dar Chouafa."}
  ],
  themes:[
    {t:"L'enfance et la solitude", d:"L'enfant, unique et incompris, se réfugie dans l'imaginaire et dans sa boîte à merveilles. La solitude est le fil conducteur du récit."},
    {t:"Le merveilleux et la superstition", d:"Voyance, amulettes, croyances populaires, visions de la fièvre : le réel se mêle sans cesse au surnaturel dans le regard de l'enfant et le monde des femmes."},
    {t:"La vie populaire de la médina de Fès", d:"Peinture ethnographique : Dar Chouafa, le hammam, le Msid, les souks, l'Achoura, les métiers artisanaux. Sefrioui fixe un patrimoine et un art de vivre."},
    {t:"La famille et les liens", d:"Tendresse maternelle, dignité du père, solidarité et querelles du voisinage : la cellule familiale et la communauté soutiennent l'enfant."},
    {t:"L'argent et l'épreuve", d:"La ruine du père, son départ pour la moisson, la gêne de la mère : le récit montre la précarité et la façon d'y faire face avec dignité."},
    {t:"La mémoire et la nostalgie", d:"Le narrateur adulte recompose son enfance : le récit est un acte de mémoire, teinté de nostalgie et de tendresse."}
  ],
  citations:[
    {c:"« Le sommeil peuple mes nuits de rêves, mes journées de fantômes. »", note:"Incipit : pose d'emblée la solitude du narrateur et l'importance du rêve/de l'imaginaire."},
    {c:"La « boîte à merveilles »", note:"Objet-titre et symbole : le coffret où l'enfant garde ses trésors (billes, boutons, clous…) est son refuge contre la solitude et la porte de son imaginaire."},
    {c:"« Dar Chouafa »", note:"La maison de la voyante : microcosme de la médina, elle réunit tous les personnages et ancre le merveilleux populaire."},
    {c:"Le « Msid »", note:"L'école coranique : lieu de l'apprentissage, de la discipline et de la peur du fqih ; cadre récurrent de la vie de l'enfant."}
  ],
  methodo:[
    "Pour situer un extrait : identifie le moment du récit (avant/après l'Achoura, avant/après le départ du père) et le lieu (Dar Chouafa, Msid, hammam, chez Lalla Aïcha).",
    "Questions fréquentes au régional : genre de l'œuvre (roman autobiographique), narrateur (Sidi Mohamed), procédés (le double regard enfant/adulte), tonalité (souvent lyrique), champ lexical des sentiments.",
    "Pour la production écrite liée à l'œuvre : appuie-toi sur les thèmes (enfance, solitude, métiers, superstition) et illustre par un exemple précis tiré du récit."
  ]
}
});
